### ISSUE TITLE
Creation of incident storage failed

### ISSUE THREAD

**Issue by sv233** [Netflix/dispatch#1037]
Hi Team,

We are facing below issue while reporting an incident from "Report Incident" section

When we are trying to report an incident, observed below issue in logs

**Adding screenshots for reference**

 INFO:Dispatch Core App: Creation of incident storage failed. Reason: Request failed. Errors: {'error': {'errors': [{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: .', 'locationType': 'parameter', 'location': 'fileId'}], 'code': 404, 'message': 'File not found: .'}}:/usr/local/lib/python3.8/site-packages/dispatch/event/service.py:log:154
web_1        | ERROR:Request failed. Errors: {'error': {'errors': [{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: .', 'locationType': 'parameter', 'location': 'fileId'}], 'code': 404, 'message': 'File not found: .'}}:/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py:incident_create_flow:549
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/drive.py", line 84, in make_call
web_1        |     return getattr(client, func)(**kwargs).execute()
web_1        |   File "/usr/local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
web_1        |     return wrapped(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 920, in execute
web_1        |     raise HttpError(resp, content, uri=self.uri)
web_1        | googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?fields=id%2C+name%2C+parents%2C+webViewLink&supportsAllDrives=true&key="*API_KEY"&alt=json returned "File not found: .". Details: "File not found: .">
web_1        | 
web_1        | During handling of the above exception, another exception occurred:
web_1        | 
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 522, in incident_create_flow
web_1        |     storage = create_incident_storage(
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 270, in create_incident_storage
web_1        |     storage = plugin.instance.create_file(
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 58, in wrapper
web_1        |     result = func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 74, in wrapper
web_1        |     return func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/plugin.py", line 79, in create_file
web_1        |     response = create_file(client, parent_id, name, participants, role, file_type)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/drive.py", line 191, in create_file
web_1        |     file_data = make_call(
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 339, in wrapped_f
web_1        |     return self(f, *args, **kw)
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 430, in __call__
web_1        |     do = self.iter(retry_state=retry_state)
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 367, in iter
web_1        |     return fut.result()
web_1        |   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
web_1        |     return self.__get_result()
web_1        |   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
web_1        |     raise self._exception
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 433, in __call__
web_1        |     result = fn(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/drive.py", line 94, in make_call
web_1        |     raise Exception(f"Request failed. Errors: {errors}")
web_1        | Exception: Request failed. Errors: {'error': {'errors': [{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: .', 'locationType': 'parameter', 'location': 'fileId'}], 'code': 404, 'message': 'File not found: .'}}
web_1        | INFO:Dispatch Core App: Creation of incident documents failed. Reason: 'NoneType' object has no attribute 'resource_id':/usr/local/lib/python3.8/site-packages/dispatch/event/service.py:log:154
web_1        | ERROR:'NoneType' object has no attribute 'resource_id':/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py:incident_create_flow:579
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 553, in incident_create_flow
web_1        |     collab_documents = create_collaboration_documents(incident, db_session)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 289, in create_collaboration_documents
web_1        |     incident.storage.resource_id,
web_1        | AttributeError: 'NoneType' object has no attribute 'resource_id'
web_1        | DEBUG:URL being requested: POST https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1&key="API_KEY"&alt=json:/usr/local/lib/python3.8/site-packages/googleapiclient/discovery.py:method:1142
web_1        | DEBUG:Making request: POST https://oauth2.googleapis.com/token:/usr/local/lib/python3.8/site-packages/google_auth_httplib2.py:__call__:118
web_1        | INFO:Dispatch Core App: Creation of incident conference failed. Reason: ('unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.', '{\n  "error": "unauthorized_client",\n  "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes ### requested."\n}'):/usr/local/lib/python3.8/site-packages/dispatch/event/service.py:log:154
web_1        | ERROR:('unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.', '{\n  "error": "unauthorized_client",\n  "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."\n}'):/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py:incident_create_flow:616
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 590, in incident_create_flow
web_1        |     conference = create_conference(incident, participants, db_session)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 235, in create_conference
web_1        |     conference = plugin.instance.create(incident.name, participants=participants)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 58, in wrapper
web_1        |     result = func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 74, in wrapper
web_1        |     return func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/calendar/plugin.py", line 137, in create
web_1        |     conference = create_event(
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/calendar/plugin.py", line 113, in create_event
web_1        |     return make_call(
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 339, in wrapped_f
web_1        |     return self(f, *args, **kw)
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 430, in __call__
web_1        |     do = self.iter(retry_state=retry_state)
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 367, in iter
web_1        |     return fut.result()
web_1        |   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
web_1        |     return self.__get_result()
web_1        |   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
web_1        |     raise self._exception
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 433, in __call__
web_1        |     result = fn(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/calendar/plugin.py", line 35, in make_call
web_1        |     data = getattr(client, func)(**kwargs).execute()
web_1        |   File "/usr/local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
web_1        |     return wrapped(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 905, in execute
web_1        |     resp, content = _retry_request(
web_1        |   File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 176, in _retry_request
web_1        |     resp, content = http.request(uri, method, *args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/google_auth_httplib2.py", line 209, in request
web_1        |     self.credentials.before_request(self._request, method, uri, request_headers)
web_1        |   File "/usr/local/lib/python3.8/site-packages/google/auth/credentials.py", line 133, in before_request
web_1        |     self.refresh(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 376, in refresh
web_1        |     access_token, expiry, _ = _client.jwt_grant(
web_1        |   File "/usr/local/lib/python3.8/site-packages/google/oauth2/_client.py", line 153, in jwt_grant
web_1        |     response_data = _token_endpoint_request(request, token_uri, body)
web_1        |   File "/usr/local/lib/python3.8/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
web_1        |     _handle_error_response(response_body)
web_1        |   File "/usr/local/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
web_1        |     raise exceptions.RefreshError(error_details, response_body)
web_1        | google.auth.exceptions.RefreshError: ('unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.', '{\n  "error": "unauthorized_client",\n  "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."\n}')

**Kindly help us what needs to be done to resolve the issue**

Environment :

Netflix Dispatch Docker container 
Linux fcdeda9e2a46 5.4.0-1038-aws #40-Ubuntu
<img width="1790" alt="Screenshot 2021-04-16 at 6 06 38 AM" src="https://user-images.githubusercontent.com/82622062/114955574-9d77b980-9e7a-11eb-8506-a2c10d5cfb3b.png">
<img width="435" alt="Screenshot 2021-04-16 at 6 12 05 AM" src="https://user-images.githubusercontent.com/82622062/114955618-b7190100-9e7a-11eb-9b39-4cf0e7cdeb29.png">

**Comment by mvilanova** [comment]
Did you complete all the steps to set up G suite described [here](https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-g-suite)? Did you specify the `INCIDENT_STORAGE_FOLDER_ID` in your `.env` file, as described [here](https://hawkins.gitbook.io/dispatch/configuration/app#incident_storage_folder_id)?

**Comment by sv233** [comment]
Hi Team,

Thanks for the response.

Kindly let me know where can we get the value of INCIDENT_STORAGE_FOLDER_ID.?. Is it From service account linked G suite account of the organization? or anywhere else 


and  kindly let us know any clue about ERROR:'NoneType' object has no attribute 'resource_id':/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py:incident_create_flow:579  ,  Dispatch Core App: Creation of incident conference failed. Reason: ('unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.', '{\n "error": "unauthorized_client",\n "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes ### requested."\n}

why it is occurring and how to resolve those errors

Thanks in advance

**Comment by mvilanova** [comment]
>Kindly let me know where can we get the value of INCIDENT_STORAGE_FOLDER_ID.?. Is it From service account linked G suite account of the organization? or anywhere else

It's described [here](https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-g-suite) as I mentioned in my previous comment.

> Dispatch Core App: Creation of incident conference failed. Reason: ('unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.', '{\n "error": "unauthorized_client",\n "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes ### requested."\n}

Did you follow the steps described [here](https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-g-suite#enable-required-apis-in-google-cloud-platform) to enable and add all the necessary APIs and scopes, so Dispatch can created resources on the G suite side?

**Comment by tarunm97** [comment]
@mvilanova , not able to access this:- https://app.gitbook.com/s/-Lb8PtMc6pK_s8P1rpOr/dispatch/configuration/app#incident_storage_folder_id

getting error:- You don't have permissions to access this space. Contact the organization administrator to configure access.

can you please help

**Comment by mvilanova** [comment]
@tarunm97 Dispatch docs where moved here: https://netflix.github.io/dispatch/
