### ISSUE TITLE
Does dispatch still work?

### ISSUE THREAD

**Issue by stefanm8** [Netflix/dispatch#1074]
**Describe the bug**

The title is ambigous but I have encountered multiple issues trying to install for the first time.

**To Reproduce**

1. clone the project
2. Install dependencies
3. run database init

**Expected behavior**
Success.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WSL

**Smartphone (please complete the following information):**

**Additional context**

There are few issues that I've resolved but it seems that I might do something wrong and that's why I'm asking for help.

- Upon running database init, it fails to create org and project because the models have not been updated to include the field default.
- After creating a user you cannot give it Admin rights with current setup, because it does not changes the roles from org and project.
- Creating terms and definitions does not work because project attribute does not exist on these entities

Am I doing something wrong or I'm playing with a prototype that has not gone production yet?

Thank you!

**Comment by kevgliss** [comment]
> Am I doing something wrong or I'm playing with a prototype that has not gone production yet?

I think you've hit the nail on the head. Generally speaking, for the dispatch project, the master branch is full of things that are "almost" ready but still require additional testing and validation. Once we're generally "happy" we then create a release tag that can be relied upon. 

If the changes between releases are minor this usually isn't a big deal. But this next release includes some pretty fundamental changes as you noticed (e.g the inclusion of organizations and projects) that will likely take a bit of time to iron out. 

Well, be working for the next few weeks to update the documentation for projects as well as hopefully iron out any issues we find (such as starting a new application from scratch). 

It looks as though you've found at least one issue where we need to go and create some default entities if they don't exist (which I will add as a task for myself). 

Let me know if you have any other questions.

**Comment by stefanm8** [comment]
Hi @kevgliss thank you for such a fast answer.

Just wanted to make sure that I'm not omitting some step, thank you for clarifying that.

Regarding the issues I mentioned above, I will open a PR just trying to help :)
