### ISSUE TITLE
Failure deserializing service account private key

### ISSUE THREAD

**Issue by rvandegrift** [Netflix/dispatch#1138]
The docs at [1] say that `GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY` should be the value of the `private_key` field from a json-formatted exported service account key.  I did that, but dispatch fails to load the key:
> ERROR:dispatch.incident.flows:Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

Just to be clear, my env file looks like:
```GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQ...```

Maybe I need to do something different with the escaped newlines?

The full traceback is at [2] - the stack trace makes it look like it is trying to load credentials from a file.

[1] - https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-g-suite#enable-required-apis-in-google-cloud-platform
[2] - https://gist.github.com/rvandegrift/78c2fad8cc24fa646fed3bd8c0df33cf

**Comment by mvilanova** [comment]
@rvandegrift can you try after following the suggestions mentioned [here](https://github.com/Netflix/dispatch/issues/113#issuecomment-602538189)?

**Comment by rvandegrift** [comment]
@mvilanova - I got it working using the format that the other poster mentioned.  But I don't know if that was my actual problem.  This is the first time I've used docker-compose, and it turns out `docker-compose restart` isn't enough to reload the env file's values.  `docker-compose down && docker-compose up -d` is required.
