### ISSUE TITLE
Microsoft 365 Support

### ISSUE THREAD

**Issue by redstonedesigner** [Netflix/dispatch#1163]
**Is your feature request related to a problem? Please describe.**

I've recently stumbled across Dispatch, and I must say that I'm absolutely loving the concept.  As someone who loves Open-Source projects, I believe that this is an amazing system.  Well done to Netflix for releasing this amazing tool into the open-source ecosystem.
Currently, however, it seems like there is a vendor lock-in to G Suite.  As an MS 365 user, this is an issue for my organisation as I'm keen to put this in front of my colleagues however I can't currently, given that there is no integration with MS 365.

**Describe the solution you'd like**

Ideally, a full similarity of the features available within G Suite.  I.e. SharePoint/OneDrive for managing groups and MS Teams for incident communication.

**Describe alternatives you've considered**

The only alternative I can think of is suggesting that the organisation switch from MS 365 to G Suite, which I believe will face extreme backlash as everyone is quite keen on MS 365.

**Comment by kevgliss** [comment]
Hi @redstonedesigner, we'd love to support MS365 and we thought of those users when developing Dispatch and its plugin system. Dispatch doesn't require _any_ plugins to be enabled so you can mix and match which plugins are right for your organization. By the same token, you can easily swap out any part of the system/plugin you want.

Unfortunately, we don't have access to an MS365 account/environment. So we would have to rely on the community to develop and maintain plugins pertaining to that environment. That said, we'd be more than happy to merge in such a contribution and help the development in any way that we can.

**Comment by redstonedesigner** [comment]
We did discover the Microsoft 365 Developer Program, which I will link below.  This appears to grant you a subscription for development purposes only with up to 25 users and one admin user.  This could be helpful with regard to supporting MS365 within Dispatch.

Link: https://docs.microsoft.com/en-us/office/developer-program/microsoft-365-developer-program
