### ISSUE TITLE
Database initialisation failed

### ISSUE THREAD

**Issue by JGroselle** [Netflix/dispatch#1165]
**Describe the bug**
I cannot initialise the database via the CLI.

**To Reproduce**
1. Run the command `dispatch database init` inside the dispatch container within the pod

**Expected behavior**
Database populated by all the needed objects

**Actual behavior**
The script fail all the time with the following message:
`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "dispatch_user" does not exist`

The problem here is the name of the wanted db is the name of the actual user (dispatch_user).
It should be DATABASE_HOSTNAME env var. But it is the _DATABASE_CREDENTIAL_USER.
I checked the code and especially the config.py, and everything seems good:
```
# database
DATABASE_HOSTNAME = config("DATABASE_HOSTNAME")
DATABASE_CREDENTIALS = config("DATABASE_CREDENTIALS", cast=Secret)

# this will support special chars for credentials
_DATABASE_CREDENTIAL_USER, _DATABASE_CREDENTIAL_PASSWORD = str(DATABASE_CREDENTIALS).split(":")
_QUOTED_DATABASE_PASSWORD = parse.quote(str(_DATABASE_CREDENTIAL_PASSWORD))
DATABASE_NAME = config("DATABASE_NAME", default="dispatch")
DATABASE_PORT = config("DATABASE_PORT", default="5432")
SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{_DATABASE_CREDENTIAL_USER}:{_QUOTED_DATABASE_PASSWORD}@{DATABASE_HOSTNAME}:{DATABASE_PORT}/{DATABASE_NAME}"
```

**Additional context**
- Dispatch is deployed in a Kubernetes cluster as a pod with a service attached.
- Database named `dispatch` already exist

**Comment by kevgliss** [comment]
I'm not quite sure, but it seems that somehow `DATABASE_NAME` is being set to `dispatch_user` in your env. Are you able to print the envvars of that pod to see if that's the case? Depending on your setup and how you name things you may have mistakenly set that envvar.

**Comment by JGroselle** [comment]
Thank you very much for your quick answer. But it seems not.

1. If I create the database's objects "manually" using sample dump, dispatch is working a bit better.
2. Here are the env variables: 

```
$ env |grep DATABASE
DATABASE_CREDENTIALS=dispatch_user:xxxxxxxxxxxxxxxx
DATABASE_NAME=dispatch
DATABASE_HOSTNAME=postgresql.my.domain
```

**Comment by kevgliss** [comment]
I believe you encountering a similar issue to: https://github.com/Netflix/dispatch-docker/issues/95, following the various threads in that issue it looks like we may need to pin `sqlalchemy-utils==0.36.7` can you see if that fixes your issue? I think there were multiple issues contained in that issue and the pinning may have been overlooked.

**Comment by JGroselle** [comment]
FYI, I decided to use "dispatch" for my DB user.
