### ISSUE TITLE
Add black as a separate github action instead of running it under build workflow

### ISSUE THREAD

**Issue by vj-codes** [Netflix/dispatch#1207]
**Is your feature request related to a problem? Please describe.**
Currently, the python.yml runs black under the `build job`, instead we should run black as a separate action and build dependent on it, so if black is successful then only build will be trigged and if it is not then build should be skipped.

**Comment by vj-codes** [comment]
@kevgliss @mvilanova I would like to work on this

**Comment by kevgliss** [comment]
@vj-codes that sounds good to me. Thanks!
