### ISSUE TITLE
send executive report

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#1228]
**Is your feature request related to a problem? Please describe.**
As for now the only way to send an executive report is to send the link to it manually. there is no way to create a mailing list that is used to automatically send a notification to exec once exec repost is created.

**Describe the solution you'd like**
configurable exec mailing lists for different incident types, then during an incident as soon as exec report is created, people from that list will get an email with a link to that report

**Describe alternatives you've considered**
Send exec report manually

**Comment by kevgliss** [comment]
Today, the executive report is sent to the `incident notification group`. This group main purpose is to contain those that need a high level of knowledge about the incident but are not directly involved.

 Within an incident, you can add other distribution lists or individuals to this group via the `/dispatch-notifications-group` command. This group only receives executive reports and does not receive tactical reports. 

If you which to have DLs added to this group automatically, you can create a new "Team" in the UI and then create a filter such that they will be added to the incident notification group for any incident matching the filter:

![2021-05-26_10-30](https://user-images.githubusercontent.com/2262214/119705320-73b49980-be0d-11eb-8d5a-ec2eccf93bb8.png)

That said this isn't probably well documented and/or could be better presented.
