### ISSUE TITLE
Make tasks creation dialog configurable

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#1229]
**Is your feature request related to a problem? Please describe.**
We use dispatch task in a different way. We're creating Wrike task via custom integration. Unfortinutely this makes some fields redundant. For example "owner" field does nothing and only frustrates users

**Describe the solution you'd like**
we want to have the ability to configure dialog window, add fields and delete them

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.**Additional context**

**Comment by kevgliss** [comment]
Are you creating Tasks via the UI? Or are you relying on the Google Docs/Tasks integration to then create Wrike tasks?

While not impossible to support, that level of UI customizability would be a big change.
