### ISSUE TITLE
 impossible to change incident commander through dispatch menu

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#1230]
**Describe the bug**
Sometimes it's impossible to change incident commander within incident through Dispatch incident menu

**To Reproduce**
Go to Dispatch Incidents 
Click on 3 dots on the right of an incident and then View/Edit
Click on commander field and try to change it to someone else
See that no changes were made after page reload, soemtimes commander changes back instantly after change

**Expected behavior**
Incident commander suppose to change

**Comment by kevgliss** [comment]
What release/tag of dispatch are you currently running? I believe this bug has been fixed in the most recent releases.
