### ISSUE TITLE
Fail incident creation if artefacts are not created

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#1231]
**Is your feature request related to a problem? Please describe.**
Sometimes when incident is created some artefacts are not created, but there is no notification or errors if this happens, so there is no way to say for sure wether or not we need to create new one on the spot. If it is possible to automatically fail incident creation in case of errors dring incident creation we could be certain that incident is created properly

**Describe the solution you'd like**
Configure Dispatch so it fails incident creation if there are any errors during arteffact creation

**Comment by kevgliss** [comment]
I agree we can do better here. Ideally, resource creation wouldn't fail. But that's not always the case. I have some ideas around how we might improve this by looking for failures in the event timeline.
