### ISSUE TITLE
Timeline update command in Slack should generate message in the channel

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#1232]
**Is your feature request related to a problem? Please describe.**
By using /dispatch-update-timeline Slack command it's possible to send any message to Dispatch timeline. But this message is only visible in Dispatch timeline, there is no notification of any kind in Slack incident channel. Update-timeline is very handy to make marks on the timeline for the future incident review, but it also can be used during a incident to communicate information between incident participants.

**Describe the solution you'd like**
When new timeline event is added send notification to the slack channel

DoD:
When /dispatch-update-timeline is used generate a message in the slack channel, with the text of the message

**Comment by kevgliss** [comment]
Yes, that is a good suggestion that we can easily add.
