### ISSUE TITLE
Show participant roles when new participant added

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#1233]
**Is your feature request related to a problem? Please describe.**
When new participant is added to the incident in slack he gets no information about other participants roles, he needs to run /dispatch-list-participants in order to see that info

**Describe the solution you'd like**
Get /dispatch-list-participants  in welcoming message for new participants. 

**Describe alternatives you've considered**
Triggering /dispatch-list-participants manually

**Comment by mvilanova** [comment]
The welcome ephemeral message includes contact information for the reporter and incident commander. We could consider including the liaison and scribe ones in the message if those have been assigned when the participant joins the incident.

The main reason why I don't think it would be a good idea to trigger the /dispatch-list-participants command when a new participant joins the incident conversation is that if the incident has lots of participants the ephemeral message that the /dispatch-list-participant command sends could end up being very long, requiring the participant to scroll up a lot to see the welcome ephemeral.
