### ISSUE TITLE
Add Geo-location field for incident

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#1235]
Description:
**Is your feature request related to a problem? Please describe.**
For now there is no geo location field in Dispatch when creating an incident. Is it possible to add new fields in incident creation?

**Describe the solution you'd like**
Additional filed during incident creation with geolocations list. Geolocations can be added in settings, along with UTC preferences for each location

**Describe alternatives you've considered**
Using tags as geolocation field, but we want to use tags for different purposes, additionally there is no GMT options

DoD:
Find a way to add geolocations that can be chosen during incident creation

**Comment by kevgliss** [comment]
> Geolocations can be added in settings, along with UTC preferences for each location

We store all times as UTC and present these times to the user in their local time in the UI (with the UTC time as a tooltip). Is that different than what you would expect?

> Using tags as geolocation field, but we want to use tags for different purposes, additionally there is no GMT options

We've had this request from others as well. In the past, we've suggested the use of tags (perhaps with a tag-type of 'location/region'). 

This would enable folks to mark incidents as occurring in multiple regions. The only downside is if you need more accurate timeline data that is geo-dependent. e.g. appA was down in us-west as 2am, but was not down in us-east until 5am. Is that similar to your use case?
