### ISSUE TITLE
Unable to create a service

### ISSUE THREAD

**Issue by stefanm8** [Netflix/dispatch#1242]
**Describe the bug**

Unable to create a service due to missing the type of the service, and I can't find or determine where this type should be created

**To Reproduce**
go to settings -> contacts -> service

**Expected behavior**
Ability to create a type and, or service

**Comment by mvilanova** [comment]
@stefanm8 you need to enable at least one of the plugins of type oncall to then be able to select the type when you create a new oncall service.

**Comment by stefanm8** [comment]
Alright, thank you for fast reply I assume this issue is closed.

Thanks!
