### ISSUE TITLE
Typo in config read: Should be DISPATCH instead of DISPACH

### ISSUE THREAD

**Issue by mogindi** [Netflix/dispatch#126]
https://github.com/Netflix/dispatch/blob/eabd95bd205462fe1ae66ea8d4946af151dcaef8/src/dispatch/config.py#L50

Opinion: Would be a bit nicer if the python vars had same name as the env vars.
i.e. env var also be DISPATCH_AUTH_HEADER_KEY, or vice versa.

**Comment by mvilanova** [comment]
@mogindi nice catch! Bonus points if you send us a PR next time ;) Thanks!

**Comment by mogindi** [comment]
Will do. Thanks :)
