### ISSUE TITLE
Dispatch with OKTA OpenID SSO

### ISSUE THREAD

**Issue by venkatashreevaatsava** [Netflix/dispatch#1278]
We have netflix dispatch setup for our org...We are trying to integrate OKTA SSO as PKCE login method instead of basic auth
We configured below in .env 
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=""
DISPATCH_JWT_AUDIENCE=CLIENT_ID
DISPATCH_JWT_EMAIL_OVERRIDE=xxxxx
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=https://{OKTA_ORG}/oauth2/default/v1/keys
DISPATCH_PKCE_DONT_VERIFY_AT_HASH=true

When dispatch login page hit..dispatch is throwing an error with "Failed to load resource: the server responded with a status of 404 ()"

Request URL: https:/{ORG}/api/v1/auth/register
Request Method: POST
Status Code: 404 

Request URL: https:/{ORG}/api/v1/auth/login
Request Method: POST
Status Code: 404 

Kindly suggest how to resolve and provide documentation on how to configure SSO for dispatch

**Comment by kevgliss** [comment]
Sorry, it looks like the server parameter docs were dropped by accident:

Please see: 
https://hawkins.gitbook.io/dispatch/administration-guide/server#configuration-for-dispatch-auth-provider-pkce

and ensure that the following are set:
```
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
```

**Comment by venkatashreevaatsava** [comment]
Hi,

We have set the below configuration, still throwing error 404 NOT FOUND when dispatch login  button is clicked is opened on login page
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=https://{ORG}/oauth2/v1/keys
DISPATCH_JWT_AUDIENCE={CLIENT_ID}
DISPATCH_PKCE_DONT_VERIFY_AT_HASH=true
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL=https://{ORG_ADMIN}/.well-known/openid-configuration


Kindly help

**Comment by venkatashreevaatsava** [comment]
done

**Comment by mnuck-fp** [comment]
@venkatashreevaatsava What fixed your issue? We are performing a similar integration (Okta, OpenID, PKCE). 

We're also not sure if we're configured correctly on the Okta side: right now we're using Application type SPA and Grant type Authorization Code, with env vars configured identical to yours.

**Comment by venkatashreevaatsava** [comment]
Issue not yet fixed.. !! When PKCE is used in dispatch../auth/login /auth/register metrics are not available therefore, in login page , when tried to login, getting 404 not found.. which is not in the case of basic-auth provider

Any clue?

**Comment by ymatsiuk** [comment]
@kevgliss just for the record we do experience the same issue with Okta. The authentication flow succeeds but 404 is rendered.

![alt](https://i.imgur.com/G3joObF.png)

I've tried to randomly add some debug logging in the PKCE plugin [class](https://github.com/Netflix/dispatch/blob/2d7e6fb498a6f0390a06d770cefd124b6fda2178/src/dispatch/plugins/dispatch_core/plugin.py#L80) but it doesn't show up in the console.

**Comment by kevgliss** [comment]
@ymatsiuk that seems different than this issue or #1294 are you on the latest release? I will try to set up a PKCE environment this afternoon to debug.

**Comment by ymatsiuk** [comment]
@kevgliss yeap, latest `master`. I've tried the patch - doesn't help. If I set a breakpoint on the line patch introduces I see that we never hit it 🙁

**Comment by kevgliss** [comment]
@ymatsiuk take a look at #1294 again, I've added a route that should allow you to complete the flow.

**Comment by ymatsiuk** [comment]
@kevgliss I confirm that works better, though I still see bunch of errors. Not sure if those are related:

![](https://i.imgur.com/CuC0NN2.png)

**Comment by kevgliss** [comment]
Those look like a different issue, could you please open a different issue and include the server logs?

**Comment by ymatsiuk** [comment]
@venkatashreevaatsava sorry for hijacking your issue. I think you experience similar issue we've had in the very beginning where `VUE_*` variables aren't propagated from `.env` of `dispatch-docker`. That's why you get redirected to `/auth/login`. As a solution you have to clone `dispatch` repo and refer to it [here](https://github.com/Netflix/dispatch-docker/blob/d68731213a99b550b41cc30709bb290b91e8e85c/docker-compose.yml#L22), rename [this](https://github.com/Netflix/dispatch/blob/master/src/dispatch/static/dispatch/.env.example_vue_app) into `.env` and run [`install.sh`](https://github.com/Netflix/dispatch-docker/blob/master/install.sh) again. That's just my wild guess.
