### ISSUE TITLE
can't login via onelogin oidc

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#1294]
**Describe the bug**
We use Release v20210319 and after the small our fix, we can successfully login via OneLogin, but after big update #990 we can't login because we have  an error on /implicit/callback page in console I see the error:
`object Object]InvalidTokenError: Invalid token specified
`
and I don't see `authorization` in Header requset 
**Additional context**
on #989 commit everything is working

**Comment by kevgliss** [comment]
I think this should be fixed by: https://github.com/Netflix/dispatch/pull/1296 

Would you mind patching your pkceAuthProvider.js and testing it out for me? I don't have a PKCE environment setup atm.

**Comment by bender92** [comment]
yes, I have tested your patch and get an error in console 
TypeError: Cannot read property 'then' of undefined at pkceAuthProvider.js:76
in the previous our patch we changed response.accessToken to response.idToken, here it doesn't work too , if I remove "then" , I get just a white page and nothing sending to backend

**Comment by kevgliss** [comment]
@bender92 I've merged in #1296  Let me know if that resolves your issue.

**Comment by bender92** [comment]
Thank you, it is working, but we use idToken instead accessToken
