### ISSUE TITLE
(Question) Is there any plans to add async driver for postgres connection?

### ISSUE THREAD

**Issue by ericsouza** [Netflix/dispatch#1295]
**Is your feature request related to a problem? Please describe.**
Well, FastAPI is all about async with python to gain some perfomance/concurrency, so maybe adding an async driver for postgres is a good idea.

**Describe the solution you'd like**
Change psycopg2-binary to asyncpg and use new async feature from SQLAlchemy 1.4+ according to [the doc](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html)

**Comment by kevgliss** [comment]
I think we'd be open to it, but given our current request/rate performance is generally limited to the queries themselves and not the webserver connection overhead.
