### ISSUE TITLE
Okta PKCE issue

### ISSUE THREAD

**Issue by ymatsiuk** [Netflix/dispatch#1303]
**Describe the bug**
After applying the patch from #1296 we've got finally working auth flow. But now there is another issue mentioned in https://github.com/Netflix/dispatch/issues/1278#issuecomment-859771971
The config we use is mentioned here: https://github.com/Netflix/dispatch/issues/1278#issuecomment-859700621

**Screenshots**
![](https://i.imgur.com/CuC0NN2.png)

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: `master` with patch from #1296 

[Debug log](https://0x0.st/-LuT.txt)

CC: @kevgliss

**Comment by kevgliss** [comment]
Looks like our docs are a bit wrong:
https://hawkins.gitbook.io/dispatch/administration-guide/server#dispatch_authentication_provider_pkce_jwk-default-true

make sure that the following value is set:

`DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS`

not 

`DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWK` 

notice the extra 'S' at the end. I will open a PR to fix that documentation.

**Comment by ymatsiuk** [comment]
this is from the debug log I've attached: 
```bash
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_core/plugin.py", line 107, in get_current_user
    keys = requests.get(DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS).json()["keys"]
KeyError: 'keys'
```

**Comment by ymatsiuk** [comment]
Found out more details on the issue:
```python
DEBUG:key_info: {'kid': '8eQcWcc<snip>5A', 'alg': 'RS256'}:/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_core/plugin.py:get_current_user:106
DEBUG:https://<snip>.<snip>.com:443 "GET /oauth2/v1/keys HTTP/1.1" 200 None:/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:_make_request:452
DEBUG:keys: [{'kty': 'RSA', 'alg': 'RS256', 'kid': 'OKk-r<snip>TI', 'use': 'sig', 'e': 'AQAB', 'n': '<snip>'}, {'kty': 'RSA', 'alg': 'RS256', 'kid': 'JrKk<snip>bk', 'use': 'sig', 'e': 'AQAB', 'n': '<snip>'}]:/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_core/plugin.py:get_current_user:110
INFO:     172.28.0.1:47444 - "GET /api/v1/default/incident_types?itemsPerPage=-1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  ...
  <snip>
  ...
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_core/plugin.py", line 122, in get_current_user
    data = jwt.decode(token, key, audience=DISPATCH_JWT_AUDIENCE, options=jwt_opts)
UnboundLocalError: local variable 'key' referenced before assignment
```

Seems like `/keys` endpoint doesn't return the key we expect and the `key` is missing [here](https://github.com/Netflix/dispatch/blob/846535a3af461c5cb3b083046f89cc92bfb8aa9a/src/dispatch/plugins/dispatch_core/plugin.py#L118)
This is what I see from the few added debug lines:

 `DEBUG:key_info: {'kid': '8eQcWcc<snip>5A'...` 

vs 

`DEBUG:keys: [{... 'kid': 'OKk-r<snip>TI' ... 'kid': 'JrKk<snip>bk' ...`

These are the variables I use now:
```sh
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
DISPATCH_JWT_AUDIENCE=<client ID from Okta>
DISPATCH_PKCE_DONT_VERIFY_AT_HASH=true
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=https://<snip>.<snip>.com/oauth2/v1/keys
# details: https://developer.okta.com/docs/reference/api/oidc/#keys
```

**Comment by kevgliss** [comment]
I'm not sure why the `kid`s don't match but they are both coming from Okta, correct? The code here is relatively simple from a Dispatch perspective (look at all the keys from the JWKS endpoint and attempt to find a match). Unfortunately, I don't have a lot of experience with Okta so I'm not sure where things might be misconfigured.

**Comment by ymatsiuk** [comment]
I was digging deeper and found out this:
* both `/token` and `/autorize` endpoint returns:
```json
{
  "token_type": "Bearer",
  "expires_in": 3600,
  "access_token": "<access_token>",
  "scope": "openid profile email",
  "id_token": "<id_token>"
}
```
* Okta doc [suggests](https://support.okta.com/help/s/article/Signature-Validation-Failed-on-Access-Token?language=en_US) that we don't validate access token, instead we introspect it.
* every single request gets intercepted by plugin [here](https://github.com/Netflix/dispatch/blob/master/src/dispatch/plugins/dispatch_core/plugin.py#L94) and the `<access_token>` is used to get user data. This seems to be incorrect, because the data we expect (like email, claims, etc) is not part of [`<access_token>`](https://developer.okta.com/docs/reference/api/oidc/#access-token), but [`<id_token>`](https://developer.okta.com/docs/reference/api/oidc/#id-token)

The whole flow is described [here](https://developer.okta.com/docs/guides/implement-auth-code-pkce/overview/)

PS: I'm trying to connect dispatch to Okta free developer account right now. This might be that our corporate Okta account is misconfigured, not entirely sure though 🤷🏻

**Comment by kevgliss** [comment]
This seems similar to #1294 perhaps it's a difference that is up to the IdP provider? I suppose we could try to check both. Alternatively, if _most_ IdPs are relying on `<id_token>` I'm happy to rely on that instead. The thought here, is really that our internal IdP is the odd one.

**Comment by ymatsiuk** [comment]
I was actually busy with testing this 🙂 So this patch works perfectly
```patch
diff --git a/src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js b/src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js
index 5910cdc..c2eaa6d 100644
--- a/src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js
+++ b/src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js
@@ -72,7 +72,7 @@ function login(to, from, next) {
           .performTokenRequest(cfg, req)
           .then((response) => {
             // Redirect to the uri in session storage and then delete it from storage
-            store.commit("auth/SET_USER_LOGIN", response.accessToken)
+            store.commit("auth/SET_USER_LOGIN", response.idToken)
             store.dispatch("auth/loginRedirect", localStorage.getItem("redirect_uri")).then(() => {
               store.dispatch("auth/createExpirationCheck")
             })
```
I tested it on da3bdae because migrations on the master are broken, it complains about table `organization` doesn't exist (sorry didn't have time to dig into the cause, seems like it's related to the last commit)

So just for the future readers this is the config:
```env
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
DISPATCH_JWT_AUDIENCE=<client_id>
DISPATCH_PKCE_DONT_VERIFY_AT_HASH=true
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=https://<org>.okta.com/oauth2/v1/keys
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID=<client_id>
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL=https://<org>.okta.com
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
VUE_APP_DISPATCH_CLIENT_ID=<client_id>
VUE_APP_DISPATCH_OPEN_ID_CONNECT_URL=https://<org>.okta.com
```

**Comment by kevgliss** [comment]
@ymatsiuk did you want to craft a PR with that fix? Don't worry about master, I'm still working through some fixes/changes.
