### ISSUE TITLE
Cannot create new incidents

### ISSUE THREAD

**Issue by cl-ericz** [Netflix/dispatch#1325]
**Describe the bug**
Creating a new incident results in the error `Incident not updated. Reason: list index out of range`. I have created a fresh deployment (using dispatch-docker), using commit 846535a. Loaded sample data, registered a user, and used the documentation to bump them to admin role (docker exec, dispatch user update, etc).

```
web_1        | 2021-06-16T17:03:15.937978275Z INFO:     172.25.0.1:47812 - "POST /api/v1/default/incidents HTTP/1.0" 400 Bad Request
```

**To Reproduce**
1. Go to 'Incidents tab
2. Click on New
3. Fill out various incident details
4. Click save
5. See error

**Expected behavior**
Creation of an incident

**Desktop (please complete the following information):**
 - macOS, Chrome v91

![Screen Shot 2021-06-16 at 10 05 38 AM](https://user-images.githubusercontent.com/85978974/122262583-675eb200-ce8a-11eb-9c4d-37c74dd85029.png)

**Comment by cl-ericz** [comment]
Looking at debug logs, directly prior to the 400 there are calls out to PagerDuty. I have properly set the service ID, and all calls return 200. Logs seem to indicate incident was created. Unknown reporter seems to refer to auto-created individual (myself).

```
web_1        | 2021-06-16T17:14:04.849786288Z INFO:Dispatch Core App: Incident created:/usr/local/lib/python3.8/site-packages/dispatch/event/service.py:log:154
web_1        | 2021-06-16T17:14:05.115120773Z INFO:Dispatch Core App: Unknown added to incident with Reporter role:/usr/local/lib/python3.8/site-packages/dispatch/event/service.py:log:154
```

```
web_1        | 2021-06-16T17:14:05.361939820Z DEBUG:https://api.pagerduty.com:443 "GET /oncalls?limit=100&schedule_ids%5B%5D=*AAA*&escalation_policy_ids%5B%5D=*BBB*&offset=0 HTTP/1.1" 200 80:/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:_make_request:452
web_1        | 2021-06-16T17:14:05.362382677Z DEBUG:Request completed: #method=GET|#url=https://api.pagerduty.com/oncalls?limit=100&schedule_ids%5B%5D=*AAA*&escalation_policy_ids%5B%5D=*BBB*&offset=0|#status=200|#x_request_id=*XXX*|#date=Wed, 16 Jun 2021 17:14:05 GMT|#wall_time_s=0.052378:/usr/local/lib/python3.8/site-packages/pdpyras.py:postprocess:1273
web_1        | 2021-06-16T17:14:05.363999143Z INFO:     172.26.0.1:40194 - "POST /api/v1/default/incidents HTTP/1.0" 400 Bad Request
```

The schedule/escalation policy IDs are correct. Is there any constraint requiring the commander/reporter of an incident to be a member of the PagerDuty policy, or similar? I do notice, when viewing the incident page that an incident is created, but commander/reporter fields are blank (and I cannot tell if any other automation has triggered, i.e. zoom/gdocs).

**Comment by kevgliss** [comment]
What authentication method are you using? We typically get reporter from the currently logged-in user.

**Comment by kevgliss** [comment]
Oh, I see you're using the default docker image and example data, let me take a look at the example data settings to see if something needs to be changed.

**Comment by cl-ericz** [comment]
I forgot to mention, I was originally using the PKCE auth flow and encountered this same error there. I actually wiped the environment and loaded the test data to see if it would still reproduce with just the basic auth flow.

In the new env (with basic auth) I thought perhaps because my "Individual" had the name "Unknown" it wasn't populating some schema, but after updating the Name to "Eric" I now see a different error upon incident creation: `Incident not updated. Reason: [object Object] `
```
web_1        | 2021-06-16T18:45:01.176735486Z INFO:     172.26.0.1:41630 - "POST /api/v1/default/incidents HTTP/1.0" 422 Unprocessable Entity
```

This happens if I have the commander/reporter set both to myself, or both to the default dispatch user.

**Comment by kevgliss** [comment]
Can you show me the actual server response for the error? In chrome it would be under the network tab, then click on the request and then click on the response or preview tab. Typically when we get a 422 we should get some kind of error message associated telling us why our request was bad.

**Comment by cl-ericz** [comment]
It would seem something strange is going on with `Individuals`. I've edited the name to "Eric" but it reverts to "Unknown" after some period of time/action. With "Unknown" I receive HTTP 400 `{"detail":"list index out of range"}` and the incident is created, but in some weird state. Now I actually cannot reproduce the `[object Object]` error, as whenever I rename my Individual to "Eric" and create an incident, the name is reverted to "Unknown" (and I receive the list index error).

![Screen Shot 2021-06-16 at 12 16 55 PM](https://user-images.githubusercontent.com/85978974/122279300-be6d8280-ce9c-11eb-82b8-234b72be932e.png)
![Screen Shot 2021-06-16 at 11 44 46 AM](https://user-images.githubusercontent.com/85978974/122279336-c9c0ae00-ce9c-11eb-878e-b0a5fd259bbb.png)

**Comment by kevgliss** [comment]
Okay, I *think* I understand what's going on with the renaming. Can you make sure that the `dispatch-contact` plugin is enabled for this project?

When creating incidents do you have any issues creating an incident from the `Report Incident` form (button on the bottom left) or only from the table `Incidents > New`?

**Comment by cl-ericz** [comment]
The `Report Incident` button & table -> new both result in the same "list index out of range" error. I can confirm the `dispatch-contact` plugin is enabled.

Are there plugins I should disable here to reduce complexity of debugging this? Full plugin listing:
![Screen Shot 2021-06-16 at 12 51 47 PM](https://user-images.githubusercontent.com/85978974/122283639-9cc2ca00-cea1-11eb-8397-f9ed9bae263b.png)

**Comment by kevgliss** [comment]
I would disable all plugins except `dispatch-contact`, `dispatch-ticket`  and `dispatch-auth-provider-basic`

Also, I found something we should change. We're swallowing the actual exception here: 
https://github.com/Netflix/dispatch/blob/master/src/dispatch/incident/views.py#L110 

But we should also log it so we're not in the dark like we are now.

Would you be able to patch that file add logging to the line I mentioned? Something like this:

```
import logging
log = logging.getLogger(__name__)


---snip---

    try:
        incident = create(
            db_session=db_session, reporter_email=current_user.email, **incident_in.dict()
        )
    except Exception as e:
        log.exception(e)  # add some real logging
        raise HTTPException(status_code=400, detail=str(e))

---snip---
```

I will create a PR with that logging separately.

**Comment by cl-ericz** [comment]
Alright, after disabling all plugins except those 3, I can now create an incident successfully (200 response). If I re-enable the pagerduty plugin, create a pagerduty service, and associate that service with an incident type as the "commander service", the "list index out of range error occurs again. I'll patch that logging in and update shortly.

**Comment by cl-ericz** [comment]
Okay, the issue seems to be resolved. The problem is that the pagerduty service/escalation policy associated with Dispatch did not have a schedule (just statically assigned users), which caused an issue with the PD plugin on incident creation. Creating an on-call schedule and assigning that to the PD escalation policy, instead of an individual user, resolved the issue.


Full exception:
```
web_1        | 2021-06-16T21:10:50.502157213Z ERROR:list index out of range:/usr/local/lib/python3.8/site-packages/dispatch/incident/views.py:create_incident:113
web_1        | 2021-06-16T21:10:50.502180012Z Traceback (most recent call last):
web_1        | 2021-06-16T21:10:50.502187287Z   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/views.py", line 109, in create_incident
web_1        | 2021-06-16T21:10:50.502193120Z     incident = create(
web_1        | 2021-06-16T21:10:50.502198444Z   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/service.py", line 238, in create
web_1        | 2021-06-16T21:10:50.502203962Z     assign_incident_role(
web_1        | 2021-06-16T21:10:50.502209326Z   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/service.py", line 44, in assign_incident_role
web_1        | 2021-06-16T21:10:50.502215330Z     assignee_email = oncall_plugin.instance.get(service_id=service.external_id)
web_1        | 2021-06-16T21:10:50.502243970Z   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 58, in wrapper
web_1        | 2021-06-16T21:10:50.502250512Z     result = func(*args, **kwargs)
web_1        | 2021-06-16T21:10:50.502255161Z   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 74, in wrapper
web_1        | 2021-06-16T21:10:50.502259846Z     return func(*args, **kwargs)
web_1        | 2021-06-16T21:10:50.502264341Z   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_pagerduty/plugin.py", line 33, in get
web_1        | 2021-06-16T21:10:50.502269212Z     return get_oncall(client=client, service_id=service_id)
web_1        | 2021-06-16T21:10:50.502273776Z   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_pagerduty/service.py", line 28, in get_oncall
web_1        | 2021-06-16T21:10:50.502278461Z     return get_oncall_email(client, service)
web_1        | 2021-06-16T21:10:50.502283300Z   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_pagerduty/service.py", line 19, in get_oncall_email
web_1        | 2021-06-16T21:10:50.502288158Z     user_id = list(oncalls)[0]["user"]["id"]
web_1        | 2021-06-16T21:10:50.502293118Z IndexError: list index out of range
web_1        | 2021-06-16T21:10:50.503504808Z INFO:     172.27.0.1:35506 - "POST /api/v1/default/incidents HTTP/1.0" 400 Bad Request
```

**Comment by kevgliss** [comment]
Cool. Glad you got it figured out. We should probably provide a better error message for that. I'll cut a PR.
