### ISSUE TITLE
Creating incident does not work on release 20200506 

### ISSUE THREAD

**Issue by stefanm8** [Netflix/dispatch#1375]
**Describe the bug**

Upon creating a incident it throws me this error:

```bash
ERROR:dispatch.decorators:The query does not contain model `Tags`.
```

the filter spec:

print() for debugging purposes
```bash
{'and': [{'or': [{'model': 'Project', 'field': 'id', 'op': '==', 'value': 1}]}]}     
```

**To Reproduce**
1. Go to UI
2. Create an incident
3. See the logs

**Expected behavior**
Incident created succesfully?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kevgliss** [comment]
I believe this should be fixed in `master`, can you confirm? We are planning to do another release in a few weeks.

**Comment by stefanm8** [comment]
Master seems to have more than one issue which doesn't currently work.
