### ISSUE TITLE
Contributor collaboration

### ISSUE THREAD

**Issue by stefanm8** [Netflix/dispatch#1396]
**Is your feature request related to a problem? Please describe.**

Hello I would like to involve more in contributing to dispatch although it seems that there is no means of communication between contributors other than issues. 

Not everything is an issue and most of the time there are questions regarding some design pattern or about some internal functionality which would be better addressed in a slack/teams/discord channel.

**Describe the solution you'd like**

Public Jira/Teams/Discord anything where we can better collaborate as contributors

**Describe alternatives you've considered**
Github Issues

**Additional context**

**Comment by mvilanova** [comment]
@stefanm8 thanks for showing interest. It's always good to have more people helping with the app, as it's mostly @kevgliss and I at the moment. We have a Dispatch community in [Gitter](https://gitter.im/netflix-dispatch/community) if you want to reach out to us there.
