### ISSUE TITLE
Creating new incident via 'New' button is failing

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#1536]
**Describe the bug**
Creating new incident via 'New' button under 'Incident' page is failing. The error shows 'UnboundLocalError: local variable 'visibility' referenced before assignment' at the backend.

However, when we create incident from 'Report Incident' button where 'Visibility' field is not available; it is able to created the ticket. 

**To Reproduce**
1. Go to Dispatch home page
2. Click on Incident pane from top left
3. Click on 'New' button to create a new incident
4. Fill out the values in the form
5. Click on save icon
6. See error 'Something has gone wrong, please retry or let your admin know that you received this error.'
7. At the backend, we can see the following error

**Expected behavior**
Incident ticket should get created.

**Error**
web_1        | ERROR:uvicorn.error:Exception in ASGI application
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
web_1        |     result = await app(self.scope, self.receive, self.send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
web_1        |     return await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
web_1        |     await super().__call__(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
web_1        |     await self.middleware_stack(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1        |     await self.app(scope, receive, _send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        |     await response(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 224, in __call__
web_1        |     await run_until_first_complete(
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in <listcomp>
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 216, in stream_response
web_1        |     async for chunk in self.body_iterator:
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1        |     await self.app(scope, receive, sender)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
web_1        |     await route.handle(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 390, in handle
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
web_1        |     await super().__call__(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
web_1        |     await self.middleware_stack(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1        |     await self.app(scope, receive, _send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
web_1        |     response = await self.dispatch_func(request, self.call_next)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 165, in dispatch
web_1        |     response = await call_next(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
web_1        |     response = await self.dispatch_func(request, self.call_next)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 153, in dispatch
web_1        |     raise e from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 149, in dispatch
web_1        |     response = await call_next(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
web_1        |     response = await self.dispatch_func(request, self.call_next)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 126, in db_session_middleware
web_1        |     response = await call_next(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1        |     await self.app(scope, receive, sender)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
web_1        |     await route.handle(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
web_1        |     response = await func(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 219, in app
web_1        |     raw_response = await run_endpoint_function(
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 154, in run_endpoint_function
web_1        |     return await run_in_threadpool(dependant.call, **values)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
web_1        |     return await loop.run_in_executor(None, func, *args)
web_1        |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
web_1        |     result = self.fn(*self.args, **self.kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/views.py", line 113, in create_incident
web_1        |     incident = create(db_session=db_session, incident_in=incident_in)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/service.py", line 174, in create
web_1        |     visibility=visibility,
web_1        | UnboundLocalError: local variable 'visibility' referenced before assignment

**Additional context**
Using the latest release. of Dispatch.

**Comment by kevgliss** [comment]
Hey, thanks for the report. This one looks like an easy fix, I've put together #1537 to address it.
