### ISSUE TITLE
Incident creation in Dispatch via API

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#1547]
In the logs we can see that actions are being performed in Dispatch via API calls made to /api/v1/default/.... 
However, I couldn't find any documentation for the same. Hence, can I get the info on how to create an incident in Dispatch tool via API call. 

Thanks!

**Comment by kevgliss** [comment]
Hi, all of the API documentation is available by visiting the generated API documentation. On your instance navigate to:

`https://<your-host>/api/v1/docs`

**Comment by vikassinha2019** [comment]
Thanks @kevgliss for the quick response. 
1 more question. what credentials I should pass and in what format in the curl POST command? is it the SECRET_KEY value we store in .env file ?

**Comment by kevgliss** [comment]
Depending on how you login you should be presented with a JWT token in the login response. This token should be included in the Authorization header for every request you make to the Dispatch API. 

For example if you were using python requests:

```
import requests
headers = {"Authorization": "Bearer <token-from-login-request"}
print(requests.post(endpoint, data=data, headers=headers).json())
```
If you are using Basic Authentication, you must generate a random value for `DISPATCH_JWT_SECRET` this value is used to generate tokens (an only your server knows it).

**Comment by vikassinha2019** [comment]
I am able to query few GET calls. However, it seems that incident creation API is not working if we only pass the required fields (title, description, project)  in the payload as per documentation. .  I had to add type and priority as well in the payload to get the ticket created. 

Thanks a lot for the help!
