### ISSUE TITLE
Issue with /dispatch-report-incident command

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#1548]
**Describe the bug**
Running /dispatch-report-incident  command in a slack channel where the slack app is already added if failing with following error:

web_1        | INFO:     192.168.112.1:34806 - "POST /api/v1/events/slack/command HTTP/1.0" 500 Internal Server Error
web_1        | ERROR:    Exception in ASGI application
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
web_1        |     result = await app(self.scope, self.receive, self.send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
web_1        |     return await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
web_1        |     await super().__call__(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
web_1        |     await self.middleware_stack(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1        |     await self.app(scope, receive, _send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
web_1        |     await response(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 224, in __call__
web_1        |     await run_until_first_complete(
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in <listcomp>
web_1        |     [task.result() for task in done]
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 216, in stream_response
web_1        |     async for chunk in self.body_iterator:
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1        |     await self.app(scope, receive, sender)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
web_1        |     await route.handle(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 390, in handle
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
web_1        |     await super().__call__(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
web_1        |     await self.middleware_stack(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_1        |     await self.app(scope, receive, _send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
web_1        |     response = await self.dispatch_func(request, self.call_next)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 165, in dispatch
web_1        |     response = await call_next(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
web_1        |     response = await self.dispatch_func(request, self.call_next)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 153, in dispatch
web_1        |     raise e from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 149, in dispatch
web_1        |     response = await call_next(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
web_1        |     response = await self.dispatch_func(request, self.call_next)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 126, in db_session_middleware
web_1        |     response = await call_next(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
web_1        |     task.result()
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
web_1        |     raise exc from None
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
web_1        |     await self.app(scope, receive, sender)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
web_1        |     await route.handle(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
web_1        |     await self.app(scope, receive, send)
web_1        |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
web_1        |     response = await func(request)
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 219, in app
web_1        |     raw_response = await run_endpoint_function(
web_1        |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
web_1        |     return await dependant.call(**values)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/views.py", line 132, in handle_command
web_1        |     body = await handle_slack_command(
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/commands.py", line 202, in handle_slack_command
web_1        |     conversation = conversation_service.get_by_channel_id_ignoring_channel_type(
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/conversation/service.py", line 17, in get_by_channel_id_ignoring_channel_type
web_1        |     db_session.query(Conversation)
web_1        | AttributeError: 'NoneType' object has no attribute 'query'

**To Reproduce**
1. Go to any slack channel where you have added your slack app
2. Run /dispatch-report-incident command 
3. you will get '/dispatch-report-incident failed with the error "dispatch_failed"' message on slack
4. In the logs, you will see above mention trace log.

**Expected behavior**
A slack form should open 

**Additional context**
PS: The /dispatch-report-incident command is working in the channel that was created by Dispatch for some other incident.

**Comment by jwl** [comment]
I also see this issue for `/dispatch-list-incidents`. I've attached my logs which contain the same above error.
[dispatch_slack_error_logs.txt](https://github.com/Netflix/dispatch/files/6978976/dispatch_slack_error_logs.txt)

**Comment by kevgliss** [comment]
@jwl or @vagharsh could you provide a little more context on _here_ these commands are being run? Is the Dispatch bot a member of the channel your running the command in?

**Comment by jwl** [comment]
For my case, the bot is indeed a member of the channel I'm running the command in.

**Comment by jwl** [comment]
I did a bit of tracing on our end and I _think_ this might be related to this Weblink validation error that pops up when I attempt to create a new incident via the web UI.

```
web_1 | INFO: 192.168.16.1:62986 - "POST /api/v1/default/incidents HTTP/1.1" 200 OK


web_1 | /usr/local/lib/python3.8/site-packages/sqlalchemy/orm/collections.py:631: SAWarning: This collection has been invalidated.

web_1 | util.warn("This collection has been invalidated.")

web_1 | ERROR:dispatch.decorators:1 validation error for TicketCreate

web_1 | weblink

web_1 | Weblink must be a valid url. (type=value_error)

web_1 | Traceback (most recent call last):

web_1 | File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 85, in wrapper

web_1 | result = func(*args, **kwargs)

web_1 | File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 516, in incident_create_flow

web_1 | db_session=db_session, ticket_in=TicketCreate(**ticket)

web_1 | File "/usr/local/lib/python3.8/site-packages/pydantic/main.py", line 406, in __init__

web_1 | raise validation_error

web_1 | pydantic.error_wrappers.ValidationError: 1 validation error for TicketCreate

web_1 | weblink


web_1 | Weblink must be a valid url. (type=value_error)

```

**Comment by kevgliss** [comment]
hmm, that seems like a different issue. Essentially, the first issue is occurring here:

**Comment by jwl** [comment]
@kevgliss Wouldn't that imply that an incident created in the UI would have the correct organization (in this case, `default`)? I can't get `/dispatch-list-incidents` to work with UI-created incidents (as those are the only ones I'm able to create in the first place).

**Comment by kevgliss** [comment]
They likely have the correct organization, but the slack command doesn't know which organization to use (there is no URL-like identifier). The problem would be the same for both of those commands as those are the only two command we allow from outside of an incident channel.

Within the incident channel, we're able to associate the correct organization because we have the source channel id already saved in the database.

**Comment by kevgliss** [comment]
I think #1551 will fix this issue but I need to do some more testing, this would add a parameter to `/dispatch-list-incidents` and `/dispatch-create-incident` that would allow the user to specify the organization to use, e.g.:

`/dispatch-list-incident <my-org>`

If no organization is specified we will use the default organization.

**Comment by jwl** [comment]
I've rebuilt from #latest but I'm still seeing this issue. I've tried this with `/dispatch-create-incident` and `/dispatch-list-incidents` (both by itself and with specifying the default org `/dispatch-list-incidents default`). I still get the same issue with the same error message as before:

```
web_1 | return await dependant.call(**values)

web_1 | File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/views.py", line 132, in handle_command

web_1 | body = await handle_slack_command(

web_1 | File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/commands.py", line 202, in handle_slack_command

web_1 | conversation = conversation_service.get_by_channel_id_ignoring_channel_type(

web_1 | File "/usr/local/lib/python3.8/site-packages/dispatch/conversation/service.py", line 17, in get_by_channel_id_ignoring_channel_type

web_1 | db_session.query(Conversation)

web_1 | AttributeError: 'NoneType' object has no attribute 'query'
```

**Comment by kevgliss** [comment]
Please try and rebuild off of `master`. `latest` points to the latest release. The changes mentioned above have not yet been released.

**Comment by jwl** [comment]
Ah that fixed it. Thanks!
