### ISSUE TITLE
Bulk addition of Individuals in a project

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#1549]
We are using dispatch-auth-provider-pkce for authentication. Users who logs-in to Dispatch, are being created as Users in organization. However, they have to be added explicitly as Individuals under a Project. 

Is there any way to automatically add the users under Individuals in a Project. Or we have to run a script to create those individuals via API ?

**Comment by kevgliss** [comment]
Individuals (for a given project) typically get added automatically when they join their first incident within that project. Are you hoping to set up some engagement rules before they are added to their first incident?

**Comment by kevgliss** [comment]
Some additional context; at least for our usage most participants only ever directly interact with Slack/Google Docs and not the Dispatch UI. So we have many more individuals (people involved in incidents). Then we have users that have logged into the Dispatch UI and gotten user credentials.

**Comment by vikassinha2019** [comment]
Okay, so I am facing this issue because I am creating incident via UI here. And for Commander/Reporter field the users will not list until they are added as Individuals or they get added via some other incident. 

So, if I create incident via slack command (/dispatch-report-incident) or via API, will the user get added if it is not available in Individuals under a project ?

**Comment by kevgliss** [comment]
> So, if I create incident via slack command (/dispatch-report-incident) or via API, will the user get added if it is not available in Individuals under a project ?

They will get added when they _join_ the incident. If you want to manually assign the incident commander on incident creation they would have to already exist. If you create incident via report incident, those individuals are resolved and then created automatically if they don't already exist.
