### ISSUE TITLE
string does not match regex

### ISSUE THREAD

**Issue by sumansid** [Netflix/dispatch#1563]
I tried to create new organization on dispatch and now whenever the `api/v1/organizations` endpoint is called, I keep getting regex errors like the one attached here : 

<img width="483" alt="Screen Shot 2021-08-18 at 1 30 58 PM" src="https://user-images.githubusercontent.com/53033648/129968096-07569d6c-dbff-4c32-b4d0-51a034ece8e7.png">

May I know if such issue was encountered before ?

**Comment by mvilanova** [comment]
What name did you give to the organization?

**Comment by sumansid** [comment]
I think it was "testorganization".  Is there a specific requirements for organization name ?

**Comment by mvilanova** [comment]
The organization name needs to match the regular expression defined [here](https://github.com/Netflix/dispatch/blob/master/src/dispatch/models.py#L15), which yours does. Let me see if I can repro locally.

**Comment by sumansid** [comment]
I am also unable to view (and switch between) the organizations that I create : 

<img width="405" alt="Screen Shot 2021-08-18 at 4 01 38 PM" src="https://user-images.githubusercontent.com/53033648/129983019-6e73a9ab-d632-4e67-9daa-dc5037cc6361.png">

**Comment by mvilanova** [comment]
Please try my fix and let me know if you're still having issues with it.

**Comment by sumansid** [comment]
Thank you for a quick response. I am no longer having the issue.
