### ISSUE TITLE
page oncall using dispatch

### ISSUE THREAD

**Issue by sumansid** [Netflix/dispatch#1569]
I have added the service id and also the required pagerduty api key as mentioned in the documentation. However, when I report a new incident, I'm not receiving any on-call incident on pagerduty. 

Does dispatch automatically page the person on-call when an incident is reported ?

**Comment by mvilanova** [comment]
Dispatch will only page the oncall person via PagerDuty if you set the `Page Commander` checkbox when you define a new incident priority (see bottom of screenshot).

<img width="451" alt="Screen Shot 2021-08-20 at 10 41 08 AM" src="https://user-images.githubusercontent.com/39573146/130272918-cc608bfa-2982-4330-9f1e-7d1015900823.png">

**Comment by sumansid** [comment]
Thank you !

And it only pages the commander whose email matches with the person on-call for a given service id ?

**Comment by mvilanova** [comment]
It pages the person oncall for the given service regardless of their email

**Comment by sumansid** [comment]
Okay. So, I have made an incident priority with page commander checked, added service id, and also have the api key, email in the .env. 

Whenever, I report a new incident with that incident priority, I am not getting any incidents in pagerduty. Am I doing it correctly ?

**Comment by sumansid** [comment]
Also, saw in the logs that a GET request is sent to the following endpoint. 

<img width="1137" alt="Screen Shot 2021-08-20 at 11 56 25 AM" src="https://user-images.githubusercontent.com/53033648/130280921-88fb5611-f838-4ac3-a83e-e340c5a73f2f.png">

**Comment by mvilanova** [comment]
Did you specify the pagerduty-oncall service you created in Dispatch when you defined the incident type?

**Comment by sumansid** [comment]
Ah, I didn't. I specified it and it works now ! Thank you.
