### ISSUE TITLE
Integrating Slack

### ISSUE THREAD

**Issue by sumansid** [Netflix/dispatch#1574]
[https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack](https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack)

Following the above documentation, I have set the required env vars in my .env file : 

`SLACK_APP_USER_SLUG`
`SLACK_API_BOT_TOKEN`
`SLACK_SIGNING_SECRET`
`SLACK_WORKSPACE_NAME`

However, I am having issue getting Slack integrated with dispatch. 

When I try to enable events with this endpoint : https://[REDACTED]/api/v1/events/slack/event, I get the following message.

<img width="709" alt="Screen Shot 2021-08-24 at 11 13 37 AM" src="https://user-images.githubusercontent.com/53033648/130683063-f65c6d4e-ca98-4352-804d-82f8fb080d47.png">

**Comment by kevgliss** [comment]
Is that endpoint available publically? If you're behind a firewall or VPC I would recommend using socket mode instead: https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack#socket-mode

**Comment by mvilanova** [comment]
@sumansid is https://[REDACTED]/api/v1/events/slack/event publicly facing? Slack needs to be able to reach out to it.

**Comment by sumansid** [comment]
right, the endpoint isn't publicly facing. I will use the socket mode.
