### ISSUE TITLE
Not able to authenticate with Okta

### ISSUE THREAD

**Issue by dustin-cowles** [Netflix/dispatch#1597]
**Describe the bug**
We are trying to configure Dispatch with Okta and are not able to authenticate.

Docs Used: https://hawkins.gitbook.io/dispatch/administration-guide/server#authentication 
Okta: Developer account
Dispatch Commit: 39a1e99c126e270361d59e23710012ab9141946e

**To Reproduce**
0. Configure as described
Using Okta login URL:
1. Navigate to Okta login/embed URL
2. Be redirected to https://dispatch.XXXXXXXX.XXX/implicit/callback?iss=https://dev-XXXXXXXX.okta.com
3. Be redirected to https://dispatch.XXXXXXXX.XXX/default/auth/login 
4. Observe login page
4a. Observe 401 in console with no auth headers
Response: {"detail":[{"msg":"Could not validate credentials"}]}
Request URL: https://dispatch.XXXXXXXX.XXX/api/v1/organizations?itemsPerPage=50&sortBy[]=name&descending[]=false&filter={"and":[{"model":"Organization","field":"name","op":"==","value":"default"}]}

Navigating to Dispatch directly:
1. Navigate to https://dispatch.XXXXXXXX.XXX/
2. Be redirected to https://dispatch.XXXXXXXX.XXX/default/auth/login
3. Observe login page
4. Observe the same 401 described above

**Expected behavior**
I expect to be able to navigate to https://dispatch.mycompany.com/* and be redirected to login via Okta.
-or-
I expect to navigate to the Okta login url and be redirected to https://dispatch.XXXXXXXX.XXX/default/auth/login with valid authorization header.

**Configuration**
Okta (dev account):
<img width="672" alt="okta-config" src="https://user-images.githubusercontent.com/42023632/131896962-b13987d3-dd3a-46ef-a3c2-e1f5d1b446f6.png">

Dispatch:
DISPATCH_AUTHENTICATION_PROVIDER_SLUG: "dispatch-auth-provider-pkce”
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS: "https://dev-XXXXXXXX.okta.com/oauth2/default/v1/keys"
DISPATCH_PKCE_DONT_VERIFY_AT_HASH: "true"
DISPATCH_JWT_AUDIENCE: "<Client ID from Okta>"

VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG: dispatch-auth-provider-pkce
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL: "https://dev-XXXXXXXX.okta.com/oauth2/default/.well-known/openid-configuration"
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID: "<Client ID from Okta>"
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_USE_ID_TOKEN: "true"

**Client:**
 - Browser: chrome 
 - Version 92.0.4515.159, others

**Additional context**
This is being configured against an Okta dev account.
Before switching to Okta, Dispatch was working with built-in auth.

We have tried toggling DISPATCH_PKCE_DONT_VERIFY_AT_HASH and VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_USE_ID_TOKEN and did not observe any difference in behavior.

**Comment by kevgliss** [comment]
Can you try setting:

`VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce` this will need to be set when you build the javascript bundle. 

It looks like this isn't in the documentation anymore, sorry about that.

**Comment by dustin-cowles** [comment]
@kevgliss Thanks for the reply. I rebuilt the docker image with the var and redeployed but unfortunately I am still seeing the same behavior. I did confirm the env vars are being set correctly within the docker container.

**Comment by kevgliss** [comment]
Hmm, I still think it's probably an issue with those variables somehow. My reasoning is that the basic auth provider is the only provider that would redirect you to `/login` when a request responds with a 401.

See: 
https://github.com/Netflix/dispatch/blob/master/src/dispatch/static/dispatch/src/api.js#L53
and 
https://github.com/Netflix/dispatch/blob/master/src/dispatch/static/dispatch/src/auth/basicAuthProvider.js#L11

If you are able, I would double-check which auth provider is being set a build time by adding:
`console.log(authProviderSlug)` here ->
https://github.com/Netflix/dispatch/blob/master/src/dispatch/static/dispatch/src/api.js#L12

**Comment by brianlwatson** [comment]
Hey @kevgliss this was indeed our issue. Our environment variables weren't available at runtime like we thought they were. Passing in the VUE_APP vars as build-args to docker did the trick.

**Comment by kevgliss** [comment]
Thanks for following up @brianlwatson. I'm glad you got it working, if you're ever inclined, it would be great if you could add okta-specific setup instructions to our docs. We get a lot of questions that I'm only partially able to help with (we don't use okta).

**Comment by csetarun2** [comment]
@brianlwatson @kevgliss 
I could able to integrate using above steps, when I open url its redirecting to okta , once I have enter credentials it logged in, but its showing blank page always

I have added below env varibales in my .env file

DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
DISPATCH_JWT_AUDIENCE=0oaxxxxxxxx
DISPATCH_PKCE_DONT_VERIFY_AT_HASH=true
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=https://trial-2372xxx.okta.com/oauth2/v1/keys
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
VUE_APP_DISPATCH_OPEN_ID_CONNECT_URL=trial-237xxx.okta.com
VUE_APP_DISPATCH_CLIENT_ID=0oaxxxxxxx
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID=0oa2rprxxxxxxxxxxx
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL=https://trial-237xxxx.okta.com
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_USE_ID_TOKEN=true
DISPATCH_UI_URL=http://34.68.139.77:8000/
DISPATCH_JWT_EMAIL_OVERRIDE=0oa2rprxxxxxx

![image](https://user-images.githubusercontent.com/21236859/200124019-4f3dc9b0-07af-4350-914b-b259b1cbd7c5.png)
![image](https://user-images.githubusercontent.com/21236859/200124097-34f1edc3-001f-4754-af85-a4f742540f02.png)


here is the logs
![image](https://user-images.githubusercontent.com/21236859/200124111-a3bdedb4-28c6-4ece-86f2-b6ed7ae36594.png)
![image](https://user-images.githubusercontent.com/21236859/200124123-a54288ca-6c11-444a-ba21-5e806eb707e9.png)

can you please help me, what I did wrong ? 
& where should we give permission to users since its not local users.
ex: user1@company.com should get admin access to default project, user2@company.com should get read access to default organization & project ? How can we achieve this

**Comment by csetarun2** [comment]
![image](https://user-images.githubusercontent.com/21236859/200154340-790f3cc8-45e9-4672-975f-095a71a61775.png)

**Comment by manireddyk** [comment]
@brianlwatson ^^

**Comment by kevgliss** [comment]
Are you building from the latest release or from the master branch?

**Comment by csetarun2** [comment]
@kevgliss Im building from latest release

**Comment by csetarun2** [comment]
I used [v20220915](https://github.com/Netflix/dispatch/releases/tag/v20220915) (sep - release) , now I could see there is new version released, let me try and let you know

**Comment by csetarun2** [comment]
Thanks @kevgliss for ur help, finally after a lot of issue I could able to integrate okta in dispatch, 
here Im sharing steps, might be useful who are integrating okta 

1. Goto Okta Admin console  -> Applications -> create app as showed below
![image](https://user-images.githubusercontent.com/21236859/204077875-cd7e9c5a-a811-46c6-821d-f1c21235b19d.png)

`
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
DISPATCH_JWT_AUDIENCE=0oa3ewdflyStCYXZY6
DISPATCH_PKCE_DONT_VERIFY_AT_HASH=true
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=https://trial-16799.okta.com/oauth2/v1/keys
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID=0oa3ewdflyStCYXZY6
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
VUE_APP_DISPATCH_OPEN_ID_CONNECT_URL=https://trial-16799.okta.com
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL=https://trial-16799.okta.com
VUE_APP_DISPATCH_CLIENT_ID=0oa3ewdflyStCYXZY6
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID=0oa3ewdflyStCYXZY6
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL=https://trial-16799.okta.com
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_USE_ID_TOKEN=true
DISPATCH_AUTHENTICATION_PROVIDER_USE_ID_TOKEN=true
DISPATCH_UI_URL=http://34.134.20.20:8000/
`

as of now I couldnt able to access with http, so I have installed nginx , reverse proxy https to http, then I could able to redirect to okta, when I enter the https://ip

![image](https://user-images.githubusercontent.com/21236859/204078061-51a8c0a1-69b2-4625-8186-252b96071047.png)

**Comment by csetarun2** [comment]
still facing 2 issue:
1. http is not working,
2.  logout is not working, once I login into the dispatch application if I click on logout it still redirecting and giving the same screen
