### ISSUE TITLE
Integrate Prometheus/AlertManager with Dispatch

### ISSUE THREAD

**Issue by Hunter-Thompson** [Netflix/dispatch#1605]
**Describe the solution you'd like**
I'd like to create an incident every time alert manager, sends an alert.

**Describe alternatives you've considered**
Write a plugin for it using the API provided by Dispatch.

**Additional context**
Id like to know if this is already implemented or is a feature that the maintainers plan to take up.

**Comment by mvilanova** [comment]
Hi @Hunter-Thompson no we have not integrated the two nor we have plans in the near future to do so. I'm not familiar with Alertmanager from Prometheus, but based on their documentation, it sounds like what you need to do is add a [webhook](https://prometheus.io/docs/alerting/latest/configuration/#webhook_config) that will hit the Dispatch API to open an incident when an alert is received. You can find more information about the Dispatch API [here](https://hawkins.gitbook.io/dispatch/administration-guide/api).

**Comment by Hunter-Thompson** [comment]
Thanks for the quick reply. 

>  what you need to do is add a webhook that will hit the Dispatch API to open an incident when an alert is received

Il do exactly this.
