### ISSUE TITLE
FR: Could Dispatch include some of the actual GDoc selected text in the new Task?

### ISSUE THREAD

**Issue by coffeetocode** [Netflix/dispatch#1620]
**Is your feature request related to a problem? Please describe.**

As an incident commander, when assigning and reviewing tasks the default description is not super helpful. Eg, looking at one of my recent incidents, 9 out of 10 of the tasks were just "Description: Description: @<assignee email address>". One could of course re-type salient details into the comment, but that's extra time and redundant information. 

**Describe the solution you'd like**
I think a better experience would be for the incident description in Dispatch (shown automatically slack and in /dispatch-list-tasks) would be to include highlighted text. 

So if I have a bullet in the doc that's `* Gina: contact vendor for further details on foo`, highlight it, make a comment, and assign it to her (by her email addr), then how dispatch would summarize it would be:
```
Description: Gina: contact vendor for further details on foo
Creator: Patrick Thomas
Assignees: Gina Fullname
```

**Describe alternatives you've considered**
No a showstopper, so "leave as is" works.  

**Additional context**
FWIW, I checked several other incidents and they seem to have the same issue, but one (hit me up internally, I'll point you to it) seems like it was showing this behavior. Not sure what to make of it.

**Comment by kevgliss** [comment]
I believe you're describing a bug that was fixed in the latest release by PR (https://github.com/Netflix/dispatch/pull/1546) please let me know if you continue to see this issue.

**Comment by coffeetocode** [comment]
Yep, I think you're right. Darn it, even read those release notes and didn't see it.

Thanks folks!
