### ISSUE TITLE
Visibility of Incidents

### ISSUE THREAD

**Issue by AlexaKelley** [Netflix/dispatch#1627]
Hello, I am looking for a way to segregate incidents that contain sensitive information. Specifically I'm looking to be able to lock down specific incidents in google drive and dispatch so only select users have access. I am aware of the visibility option within Dispatch, but I was confused with the documentation from it.

Am I understanding correctly that the visibility setting does not impact google drive permission at incident creation? (ie. when an incident is created anyone with dispatch access is able to view all incidents in the google drive and on that dispatch tenant?)

I'm willing to create a separate tenant for segregation if necessary, but I'm hoping the visibility setting may be a good fit.

**Comment by mvilanova** [comment]
@AlexaKelley all incident folders are created with the same permissions, but when the incident type is restricted, only the commander, reporter, and participants on that incident will be able to access its contents during and _after_ the incident is closed. The only difference between open and restricted is that when it's open we change the sharing permissions of the Google folder to _all_ users in the Google domain defined in the `.env` file when the incident is closed. The Dispatch organization admin will also be able to see them (see permissions logic for incident view [here](https://github.com/Netflix/dispatch/blob/e9cf86d9de84dac5724ff1508cc4cd65f155fba5/src/dispatch/auth/permissions.py#L222)). We'll review the documentation to make sure it doesn't generate confusion.

**Comment by mvilanova** [comment]
You could also consider leveraging Dispatch projects to separate non-sensitive (open viz) vs sensitive (restricted viz) incidents if that works best for you.

**Comment by kevgliss** [comment]
In addition to what @mvilanova mentioned, it's important to note that regardless of visibility,  _during_ an incident only incident participants will have access to the incident resources (e.g. slack and google docs), but others will are aware of the incident's existence (if not the details). 

If you wish to keep _existence_ of the incident private setting the visibility to restricted ensure that no notifications are sent and only directly participants are only ever to view in the dispatch UI.

**Comment by AlexaKelley** [comment]
Sorry for the delay in getting back to you all on this. 

This was _very_ helpful and exactly what I was looking for. I was able to create the data segregation I needed successfully. If I get a chance I'll toss in a PR with suggested doc updated to clear up some of the language if you all don't get to it first.
