### ISSUE TITLE
Can't get Slack plugin to work in socket mode

### ISSUE THREAD

**Issue by jtorvald** [Netflix/dispatch#1704]
**Describe the bug**
I followed the installation instructions here
https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack
And created a bot on slack in socket mode.

I use the docker compose to start the server slack org project and it says:
Slack websocket process started...

With no further logging. And then it does not do anything. The app is installed and the commands are not visible.
I also enabled the two slack plugins and entered the bot credentials/signing etc there.

Is there an example bot config? And maybe a way to debug the connection with slack?

I also experiences another error with starting the slack daemon but I will create another issue for that.

**Comment by mvilanova** [comment]
Oh Slack, always making it confusing... Interesting that you don't have the option in the free version when you're choosing from scratch but you do when choosing from an app manifest (even if limited to 5).
