### ISSUE TITLE
Having a hard time to get it up and running

### ISSUE THREAD

**Issue by jtorvald** [Netflix/dispatch#1707]
**Describe the bug**
Not sure if this exact version is used within Netflix, but it seems to be missing things.
Maybe some of those issues come from running on a clone of master? 
$ git rev-parse HEAD
2ef240e1f5cbceecd024f61e6157891c4d7d3ca8)

A list that I ran into:
- When adding a service it says: Select a type. That type is nowhere to be found. Don't know how to add it and don't see any section under settings for that. Still they are required.
- Similar issue with workflow. I can just add a workflow but nothing happens with it. Is it only possible to start a workflow from Slack?
- After reporting an Incident, the screens with the form stays visible and there is an internal server error on the API. When I look in the database the column name is empty, therefor can not find the incident with tasks, which searches on the name column instead of the title column. AttributeError: 'IncidentCreate' object has no attribute 'commander' (I see that this is fixed in #1702

**Comment by kevgliss** [comment]
Thanks for the report, you're correct master is usually the bleeding edge and may be unstable at times. We do push release tags every few weeks ago, these are generally stable and have been deployed/tested. 

> When adding a service it says: Select a type. That type is nowhere to be found. Don't know how to add it and don't see any section under settings for that. Still they are required.

You're right we should make type optional in the UI (it's not actually required by the UI). As for why there are no dropdowns services are tied to a plugin of "-oncall" currently only pagerduty and opsgenie are available. But for them to show up in that "type" plugin field they need to be enabled and configured. If there are no "oncall" plugins available you can't really create a service. We should make this more clear in the UI. 

> Similar issue with workflow. I can just add a workflow but nothing happens with it. Is it only possible to start a workflow from Slack?

Workflows face the same issue, in that; they are inherently tied to a plugin. In the case of workflows we don't have any OSS workflows currently baked into Dispatch (we have an internal workflow engine we use). I'd be interested in what your expectations for workflows are and how we might better support other engines.
