### ISSUE TITLE
Running dispatch under a URL path

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#1719]
Following the documentation, I am able to setup and run Dispatch fine on URL like https://dispatch.abc.com. 

However, what changes we need to do, in order to run on https://abc.com/dispatch. I have tried updating the nginx config from 

location / {
proxy_pass http://127.0.0.1:8000;
proxy_set_header Host $host;
proxy_set_header        X-Real-IP       $remote_addr;
proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
}

to 

location /dispatch {
proxy_pass http://127.0.0.1:8000;
proxy_set_header Host $host;
proxy_set_header        X-Real-IP       $remote_addr;
proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
}

but hitting https://abc.com/dispatch is giving me 404 error, as it is still looking for JS files under https://abc.com/

**Comment by jtorvald** [comment]
@vikassinha2019 
You could just proxy the /static/ path to the static path on dispatch server.
But that could clash if you use /static/ for your main application.
```
location ^~ /static {
      proxy_pass http://127.0.0.1:8000/static;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
