### ISSUE TITLE
No incident channel on Slack

### ISSUE THREAD

**Issue by jtorvald** [Netflix/dispatch#1721]
**Describe the bug**
When I create an incident I don't get a slack channel. When I run a slash command on any channel or in private message I get: "I see you tried to run /dispatch-incidents in an non-incident conversation. Incident-specifc commands can only be run in incident conversations"

Is this normal? Am I missing something?

When I check logs:

```
$ docker logs dispatch_core_1
INFO:     Started server process [1]
INFO:uvicorn.error:Started server process [1]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

$ docker logs dispatch_slack_1
Slack websocket process started...

$ docker logs dispatch_scheduler_1
Starting scheduler...

WARNING:dispatch.task.scheduled:Skipping task sync no task plugin enabled. ProjectId: 1
WARNING:dispatch.task.scheduled:Skipping task sync no task plugin enabled. ProjectId: 1
WARNING:dispatch.workflow.scheduled:No workflow plugin is enabled. ProjectId: 1
WARNING:dispatch.workflow.scheduled:No workflow plugin is enabled. ProjectId: 1
WARNING:dispatch.monitor.scheduled:No monitor plugin is enabled. ProjectId: 1
WARNING:dispatch.monitor.scheduled:No monitor plugin is enabled. ProjectId: 1
WARNING:dispatch.task.scheduled:Skipping task sync no task plugin enabled. ProjectId: 1
WARNING:dispatch.task.scheduled:Skipping task sync no task plugin enabled. ProjectId: 1

```

**Comment by mvilanova** [comment]
Are you getting error Slack related errors when creating the incident? Perhaps it gets created but you're not being added for another reason? Slash commands exposed by the Slack app can only be run in incident channels with the exception of `/dispatch-list-incidents` and `/dispatch-report-incident` (see [here](https://github.com/Netflix/dispatch/blob/master/src/dispatch/plugins/dispatch_slack/commands.py#L249)).

**Comment by jtorvald** [comment]
When I create an incident through the UI I don't get Slack errors, but when I run `/dispatch-report-incident` as well as `/dispatch-list-incidents`  I get
`The server responded with: {'ok': False, 'error': 'user_not_found'}`

So that's clear. The question is, how does it try to find the user? I have the Slack contact resolver enabled with the same secrets and bot token etc as the Slack conversation.

**Comment by mvilanova** [comment]
We hit `users.conversations` to get a list of public and private channels the Slack app/ bot is a member of so we can compare it with the channel where the command was run by the user. If the channel where the command was run is not in the list of public or private channels the bot is a member of, then is when we give you the "I see you tried to run /dispatch-incidents in an non-incident conversation. Incident-specifc commands can only be run in incident conversations" message. Did you specify the app user id in the App User Slug field in the plugin config? App user id != app id. You can user this api endpoint tester to get it: https://api.slack.com/methods/bots.info/test

Also, does a user with the email address you're using to auth against Dispatch and submit the report exist in your Slack workspace?

**Comment by mvilanova** [comment]
Actually, https://api.slack.com/methods/auth.test/test is the one you want to use. Provide your bot token (e.g. xoxb-*) and use the `user_id` from the response.
