### ISSUE TITLE
Workflow: more details please

### ISSUE THREAD

**Issue by jtorvald** [Netflix/dispatch#1722]
**Is your feature request related to a problem? Please describe.**
I find it hard to wrap my head around the workflow plugin since there is no example and also not a lot of documentation around it. I'm trying to see if I can make a plugin for Temporal but I would appreciate a bit of help by understanding how workflows are used.

**Describe the solution you'd like**
1. I would appreciate a summary of how workflows work, when they get triggered and what is expected from them to return.
2. Could you give me some examples of workflows that you are running?
3. I read in the docs that the workflow system need to report back the status, but I can not really find something about that in the dispatch_test/workflow or in the base class.
4. How can I invoke a workflow?

**Describe alternatives you've considered**
I created a plugin that is visible in the UI and enabled but still it gives me in the error log:
`WARNING:dispatch.workflow.scheduled:No workflow plugin is enabled. ProjectId: 1`
Does that mean that the plugin is not fully working?

**Comment by kevgliss** [comment]
> but maybe it's possible to only accept the evergreen* fields when evergreen=true. Small detail

This is possible, let me try and add that logic. Although I'm not sure if the schema accurately reflect it.
