### ISSUE TITLE
Participants having Liason and Scribe roles are not added in slack channel automatically

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#1724]
**Describe the bug**
The Liason role gets added in the ticket participants (as per opsgenie schedule), but that member is not added in the corresponding created slack channel. Only reporter and Incident commander gets added.

**To Reproduce**
1. Configure mapping of Commander Service and Liason Service role against a Type.
 
2. Create a ticket from red button 'Report Incident'
3. Slack channel will be created
4. Requestor and Commander Service 'IC-oncall' person will only be added in the channel by automation.

**Expected behavior**
Once the slack channel is created, all the corresponding configured on-call members (IC, Liason, Scribe) and requestor should be added in slack channel automatically.

**Comment by mvilanova** [comment]
Yep, it's a bug. I'll cut a PR to fix it.
