### ISSUE TITLE
Feature request: Support limited list of slash slack commands

### ISSUE THREAD

**Issue by jtorvald** [Netflix/dispatch#1750]
**Is your feature request related to a problem? Please describe.**
When using the free tier of the Slack app you can only have 5 slash commands in an app.

**Describe the solution you'd like**
I'm looking for a solution where slash commands are combined and where the parameters indicate the action.

/dispatch-add	type (timeline-event, role, oncall)
/dispatch-list	type (incidents, tasks, my-tasks, participants, resources,  workflows)
/dispatch-report	type (incident, tactical, executive) org project
/dispatch-run 	type (workflow) in case something else gets added
/dispatch-update	type (incident, notifications, participant)

I believe these calls can even work alongside the current commands.

**Describe alternatives you've considered**
Paying for slack would be an option, but might not be needed. Specially for test / tryout setups it would be nice to have the full functionality and not be limited.

**Comment by mvilanova** [comment]
Thanks for the feature request. I can understand the frustration with this limitation. For testing purposes, I'd suggest to update the list of commands in the app manifest, so you can test all of them, 5 at a time. You have probably thought about that.

Moving from a command per action to a command that can handle more than one would require a substancial amount of refactoring given how code is architectured today. We can consider it in the future, but it's not something we will prioritize. You're welcome to submit a PR for it.

Looks like our production Slack app was migrated to app manifest and I see the same error when I view the manifest in the Slack Web UI, but everything is still working fine. I've reached out to Slack to see if it's possible to increase this limit or revert back to the old config UI for commands. I'm concerned I won't be able to make changes to the app without reducing the number of commands to 5, which would reduce the app's functionality. I'll circle back once I hear back from them.

**Comment by mvilanova** [comment]
I heard back from Slack. This issue has been resolved on their end.

**Comment by jtorvald** [comment]
@mvilanova thanks for following up. I'm a bit busy right now but planning to setup Dispatch for production in the new year.
