### ISSUE TITLE
Feature : initiating incident from slack via slack commands

### ISSUE THREAD

**Issue by vagharsh** [Netflix/dispatch#180]
**i would like to start implementing this feature if no one is already working on it.**
starting an incident from slack and invite people from previously configured to the channel and then push all the chat history to JIRA or to **dispatch** also once the incident is created the ONCALL personal in  **pagerduty** will get notified about it as well ( will get a page as well )

Slack should be configured accordingly to point the incident related commands to dispatch

**Comment by mvilanova** [comment]
@vagharsh no one is currently working on it, all yours! Here's how I would approach it:
1. Add the new command in the plugin config [here](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_slack/config.py).
2. Make this command present a dialog with the same fields in the intake form (screenshot below). Example on how to create a dialog [here](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_slack/views.py#L319).
3. Once the form is submitted, it will be processed by Dispatch as a Slack action. Add the command to [this](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_slack/views.py#L555) mapping  and create a function to handle the action (example [here](https://github.com/Netflix/dispatch/blob/37d6ce06a8b0c07e58e3e6b1455ca8cd2cad671d/src/dispatch/plugins/dispatch_slack/views.py#L527)). This function will need to call the `create` function in the incident [service](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/incident/service.py#L134) module and run the [incident_create_flow](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/incident/flows.py#L349) as a background task (example [here](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/incident/views.py#L74)).

You can configure who (individuals, on-call services, ...) will get pulled into the incident channel in the Web UI. Dispatch notifies and adds the on-call person to the incident channel, and pages them if the incident priority is high (see [here](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/incident/service.py#L49)). We will consider adding a setting in the Web UI to allow people to define when the on-call should be paged.

We're working on adding timeline support to Dispatch, which will include Slack messages reacted with a specific emoji.

<img width="618" alt="Screen Shot 2020-03-30 at 10 18 51 AM" src="https://user-images.githubusercontent.com/39573146/77942622-ba8e1a00-7270-11ea-846f-7ba24edbb53a.png">

**Comment by vagharsh** [comment]
That's somehow funny, and nice to see that all the functionalities that i had implemented are done here. I will see through the slack app requirements and let you know

**Comment by mvilanova** [comment]
@vagharsh we would like to add this feature to Dispatch soon. Before we do, I wanted to check with you to see if you have made any progress.

**Comment by vagharsh** [comment]
I had medical issues the past couple of weeks and my work got interrupted. I need a week to wrap things up and will send a commit.. let me know how to proceed

**Comment by mvilanova** [comment]
Sorry to hear that. Hope you're feeling better. No rush. Looking forward to
reviewing your PR.

Marc

**Comment by vagharsh** [comment]
hey @mvilanova is there a way we can chat somewhere ? i have couple of questions

**Comment by vagharsh** [comment]
anyone here can help me on how to test my code as a whole ? i have implemented all the requirements i can think of. i just need to run the application from my local.

**Comment by mvilanova** [comment]
@vagharsh in order to test your code locally, you need to do the following:
1. Download and start [ngrok](https://ngrok.com/) by running `./ngrok http 8000`
2. Create and configure your Slack app. Instructions [here](https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-slack). Make the Request URLs in the Slack app point to your ngrok hostname (e.g. `https://<RANDOM_HOSTNAME>.ngrok.io/api/v1/events/slack/action`)
3. Start the postgres database by running `docker-compose up` in the docker directory
4. Initialize the database and upgrade its schema
5. Start the server by running `dispatch server develop`. Make sure that `DATABASE_HOSTNAME` is pointing to `localhost` and `DATABASE_CREDENTIALS` has `postgres:dispatch`
6. Run the Slack command that creates the dialog and check that the incident and its resources are created.

Let me know if you have any other questions.

**Comment by vagharsh** [comment]
i have configured my slack , and brought the PSQL up and configured the .env ./ but it's not coming up it's asking for the UI  and then throwing exception about `botocore.exceptions.NoRegionError: You must specify a region.`

**Comment by vagharsh** [comment]
@mvilanova i have invited you to my slack workspace please accept the invitation and let's work together and deliver this.. looking forward to contribute further

**Comment by mvilanova** [comment]
Thanks, will do as soon as I can.

**Comment by kevgliss** [comment]
This was merged in #294
