### ISSUE TITLE
'undefined' error when trying to add data to UI

### ISSUE THREAD

**Issue by sarahcthekey** [Netflix/dispatch#181]
I'm in the dashboard UI now and trying to input some test incident types/services etc to populate the info for testing. As far as I know I've set up all the integrations via .env.

I'm now getting an 'undefined' error (screenshot attached) when trying to add anything into the UI. Are there any logs I can view to get to more info why it's failing? Worth mentioning I'm running as a docker container from the dispatch-docker repo.

Any pointers appreciated, thanks! 

![UI](https://user-images.githubusercontent.com/54888897/77917548-9cd1ac80-7292-11ea-94a9-6ef4f79e50aa.PNG)

**Comment by mogindi** [comment]
Having the same issue : undefined error.

Looking in the javascript console seems its getting a 500 in a couple of requests

![image](https://user-images.githubusercontent.com/44147714/77924459-f7bfcf80-72a3-11ea-93a2-13154c86b802.png)

docker logs of dispatch_web_1 show 
```
File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 81, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 4 validation errors for IncidentTypePagination
response -> items -> 0 -> template_document -> weblink
  none is not an allowed value (type=type_error.none.not_allowed)
response -> items -> 0 -> template_document -> name
  none is not an allowed value (type=type_error.none.not_allowed)
response -> items -> 1 -> template_document -> weblink
  none is not an allowed value (type=type_error.none.not_allowed)
response -> items -> 1 -> template_document -> name
  none is not an allowed value (type=type_error.none.not_allowed)
```

It looks to me the source of it is missing database entries, so UI has null values for these, and then its giving a validation error because it can't accept null values for incident types/incident priorities.

Do you actually have incident types and incident priorities in your database?

Wondering how to populate those. There used to be a `dispatch database populate` but now its gone.

**Comment by sarahcthekey** [comment]
@mogindi please can you let me know where abouts the docker logs are on dispatch_web_1 container?

Also I'm no postgres expert but I have installed pgadmin and allowed my IP to connect to the DB (in test). I can't see any relevant data/tables at all.

**Comment by mogindi** [comment]
Hi @sarahcthekey 

just `docker logs dispatch_web_1` outside container should do the trick. Adding '-f' and/or '--tail 50' with that would be helpful.

I have tables created, but no data in them. This part is not very well documented, but inside one of the dispatch containers you need to run `dispatch database init` to create the tables.
https://hawkins.gitbook.io/dispatch/cli#init

**Comment by sarahcthekey** [comment]
@kevgliss logs attached for you from docker logs, I also had the same 500 errors as @mogindi describes above.

[docker-logs.txt](https://github.com/Netflix/dispatch/files/4404991/docker-logs.txt)

**Comment by sarahcthekey** [comment]
Some more errors I didn't capture in the txt above:

```
KeyError: '""'
ERROR:    Unable to find slug: "" in self.all version 1: <generator object PluginManager.all at 0x7ffb2e5dcc80> or version 2: <generator object PluginManager.all at 0x7ffb2e5dcc80>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 22, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/sentry_asgi/middleware.py", line 19, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 197, in __call__
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
```

**Comment by mogindi** [comment]
@sarahcthekey I can also help with that issue

if your using no authentication like me, i've set in my .env file:

```
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=
DISPATCH_AUTHENTICATION_PROVIDER=
```

for some reason quotation marks get passed over as characters. So looks to me you have set `DISPATCH_AUTHENTICATION_PROVIDER_SLUG=""` that's throwing this error

**Comment by sarahcthekey** [comment]
@mogindi brilliant thank you! 

Is the general rule not to include quotation marks on the end variables?

**Comment by mogindi** [comment]
no problem :)

yes seems so. Not that its documented anywhere - just learnt the hard way.

**Comment by kevgliss** [comment]
Added a hint to the docs: https://hawkins.gitbook.io/dispatch/configuration/app

**Comment by mogindi** [comment]
Hey @kevgliss the original issue is still not resolved. Its not why we were getting 'undefined error'.

I have these correct configs and still getting undefined error. It was just a comment/fix to the latest error logs posted by @sarahcthekey.

**Comment by kevgliss** [comment]
Apologies for the premature closure. The current population of data is... bad. In general, you need to create (in order) a document, a service, an incident_type (with a template document, and service associated) and a priority. 

Let me open a PR to `database init` with some values (they can all be changed later). Initially, I was too focused on the fact that there weren't "good" defaults for these values. When in reality you just need _some_ values to get going. 

Additionally, there is also: https://github.com/Netflix/dispatch/pull/149 which may be helpful for getting you going. The goal once merged would be to give documentation on getting mock data into dispatch to play around with.

**Comment by B3lak0r** [comment]
![image](https://user-images.githubusercontent.com/54198281/77996025-c3d8be80-7324-11ea-905a-3ce1257c5350.png)



> Apologies for the premature closure. The current population of data is... bad. In general, you need to create (in order) a document, a service, an incident_type (with a template document, and service associated) and a priority.
> 
> Let me open a PR to `database init` with some values (they can all be changed later). Initially, I was too focused on the fact that there weren't "good" defaults for these values. When in reality you just need _some_ values to get going.
> 
> Additionally, there is also: #149 which may be helpful for getting you going. The goal once merged would be to give documentation on getting mock data into dispatch to play around with.

@kevgliss  I suppose this is insn't available yet, so right now every other screens / set up are functional (including savings) except for the incidents, btw there is any way to set up priority by the UI ? 'cause it's the only fiedl / value I cannot add anywhere...

![image](https://user-images.githubusercontent.com/54198281/77996330-52e5d680-7325-11ea-9c80-ac708065ec00.png)


![image](https://user-images.githubusercontent.com/54198281/77996224-2336ce80-7325-11ea-9395-c7d0f606889b.png)

**Comment by kevgliss** [comment]
@B3lak0r there isn't a way to currently set priority via the UI, we used Enums (which are then added to the database...). What is your appetite for custom priorities? Is low, medium, high enough?

**Comment by B3lak0r** [comment]
> @B3lak0r there isn't a way to currently set priority via the UI, we used Enums (which are then added to the database...). What is your appetite for custom priorities? Is low, medium, high enough?

@kevgliss ok, now I get it, and yes I was thinking in something like that... btw  do you think this 422 error could be related to that?

**Comment by sarahcthekey** [comment]
@kevgliss if you have time are you able to look at the 422 error, as @B3lak0r mentioned?

There’s a related issue about this over on the dispatch-docker repo too which you’ve been tagged in and may want to read. 

Thanks :)

https://github.com/Netflix/dispatch-docker/issues/34

**Comment by B3lak0r** [comment]
@sarahcthekey I'll testing with the g suite credentials on the .env file in order to figure it out which one then could be causing this, I think maybe is how I added GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY and GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID :  

```
GOOGLE_SERVICE_ACCOUNT_PROJECT_ID=dispatch-xxxxxxx
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID=7c8fd14b7f9xxxxxxxxxxxxxxxxxxxx
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=\nMIIEvAIBADANBgkqhkiG9xxxxxxxxxxxxxxxxxx\n
GOOGLE_SERVICE_ACCOUNT_DELEGATED_ACCOUNT=test@your-gsuite-domain
GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL=dispatch@xxxxxxx.iam.gserviceaccount.com
GOOGLE_SERVICE_ACCOUNT_CLIENT_ID=107866241xxxxxxxxxxxxxx
GOOGLE_DEVELOPER_KEY=AIxxxxxxxxxxxx
GOOGLE_DOMAIN=your-gsuite-domain                                        

```
you did it that way too?

**Comment by mogindi** [comment]
@B3lak0r i did it that way as well

except my `GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY` had `-----BEGIN PRIVATE KEY-----` and `-----END PRIVATE KEY-----`. Although there are spaces and no quotation marks.. seems to work
Unless its actually broken and I'm getting no error.

running `dispatch plugins list` should give you an indication if the plugins are authenticated or not
