### ISSUE TITLE
Installing and Running Dispatch with Docker

### ISSUE THREAD

**Issue by ceej21** [Netflix/dispatch#182]
So I have installed everything (I am following the installation guide) https://hawkins.gitbook.io/dispatch/installation. After running ./install.sh, how do you actually run the Dispatch environment using docker?

**Comment by mvilanova** [comment]
@ceej21 you run `docker-compose up -d`. Please, post docker-related questions, feedback, issues to the https://github.com/Netflix/dispatch-docker repo. Thanks
