### ISSUE TITLE
@kevgliss OK thanks, I have added this, unfortunately now receiving a different error when I try to add a new service (or other inputs):

### ISSUE THREAD

**Issue by kevgliss** [Netflix/dispatch#183]
@kevgliss OK thanks, I have added this, unfortunately now receiving a different error when I try to add a new service (or other inputs):

`IncidentType not created. Reason: undefined
`

_Originally posted by @sarahcthekey in https://github.com/Netflix/dispatch/issues/95#issuecomment-605896124_

**Comment by kevgliss** [comment]
@sarahcthekey can you provide any other logs (server, browser)? Likely the server threw a 500 (meaning JS couldn't display the actual error).

**Comment by sarahcthekey** [comment]
@kevgliss I opened a new issue earlier after I posted this apologies. 
Someone else has posted logs and chrome dev tools output :

https://github.com/Netflix/dispatch/issues/181#issue-590290407
