### ISSUE TITLE
Connecting Alertmanager to Netflix Dispatch

### ISSUE THREAD

**Issue by maghsood026** [Netflix/dispatch#1833]
Hello there and thank you for great incident management tool like dispatch,
but I have a problem with the Dispatch webhook in my project, and I couldn't find it in the documentation,
is it possible to create a webhook in dispatch and then define a receiver in Alertmanager to generate a new incident when the alert fired?

**Comment by kevgliss** [comment]
I'm not familiar with Alertmanager; but if it is able to send requests to an external service then you should be able to create incidents via the Dispatch API from Alertmanager when an alert fires.

**Comment by mvilanova** [comment]
You may want to reach out to @Hunter-Thompson to see if he managed to integrate the two. He reached out about the same here: https://github.com/Netflix/dispatch/issues/1605
