### ISSUE TITLE
Installation its done but no right to create incident or manage the apps

### ISSUE THREAD

**Issue by Hash8395** [Netflix/dispatch#188]
The application web it's done ! 
but now i can't use the web ui because i don't have create account or login web page 
can you help me ? 

thx
![image](https://user-images.githubusercontent.com/46268206/78113652-5732f200-7400-11ea-9de5-2bd76f1f53b3.png)
![image](https://user-images.githubusercontent.com/46268206/78113684-60bc5a00-7400-11ea-9ef1-718245eb6d75.png)

**Comment by mvilanova** [comment]
@Extazer583 can you elaborate a little bit more, please? You don't need to create any accounts and there's no login page. Also, please take a look at the docs about auth [here](https://hawkins.gitbook.io/dispatch/configuration/app#authentication).

**Comment by stefanm8** [comment]
Hello!

This should be fixed, now you have register/login endpoints.
