### ISSUE TITLE
Incorrect project routing upon usage of slack-plugin

### ISSUE THREAD

**Issue by olam-slack** [Netflix/dispatch#1926]
Added new organization 
Added new project 
Added slack plugin
But the server log still shows an organization that is not added to.

![image](https://user-images.githubusercontent.com/96050653/151072465-ff0c2311-b879-4013-8cd6-8dad3d7c9d32.png)

**Comment by mvilanova** [comment]
Looks like your database session is using a different database schema (`dispatch_organization_organization1` vs `dispatch_organization_slack`). Did you manually rename the schema in the database? Does it still happen if you restart all containers and connect to the UI again?

I ran into similar issues yesterday when I was testing https://github.com/Netflix/dispatch/pull/1929. I need to spend more time to see if there's a way to avoid these issues, but it feels very hacky to me.

**Comment by olam-slack** [comment]
Thanks. I did not manually rename the schema this time. Did not and would not be able to test any time soon again, as I wiped everything.

**Comment by mvilanova** [comment]
Ok, I abandoned #1929 and created #1935 to disallow org name changes.
