### ISSUE TITLE
No drop-down commander & reporter upon incident creation after dropping database

### ISSUE THREAD

**Issue by olam-slack** [Netflix/dispatch#1928]
Dropped the database & init
dispatch database drop
dispatch database init

Registered two users 1@test.com & 2@test.com
They are not being shown for choice as commander nor reporter.
No incident can be created.

![image](https://user-images.githubusercontent.com/96050653/151076795-fde68267-4914-4272-b7fe-3844fc7aa231.png)

**Comment by mvilanova** [comment]
@olam-slack Dispatch UI users are not the same as individuals who participate in incidents. These drop downs rely on individuals in the Individuals section under each project. The list of individuals will be programmatically populated as they get added to incidents or can be populated manually by clicking on the New button.

**Comment by olam-slack** [comment]
Thanks for your clarification, but I don't see a new button upon creation of the incident.

**Comment by mvilanova** [comment]
<img width="1017" alt="Screen Shot 2022-01-26 at 11 07 14 AM" src="https://user-images.githubusercontent.com/39573146/151229906-2017ffea-4684-4210-a9b8-03b248202521.png">
