### ISSUE TITLE
Problems with create Tag

### ISSUE THREAD

**Issue by sychev-a-k** [Netflix/dispatch#200]
Hello!
I have problems with create tags.

When i run all containers via docker-compose.
I run those commands:
dispatch database init
dispatch database upgrade
dispatch database restore --dump-file /dispatch-sample-data.dump

After those I cannot add some tags in UI
![image](https://user-images.githubusercontent.com/29555052/78349965-11675c80-75ad-11ea-9e49-745a4fa3ab25.png)
In logs I see this 
![image](https://user-images.githubusercontent.com/29555052/78350036-2e9c2b00-75ad-11ea-92bf-33f3bba97fa9.png)
How I can resolve this?

**Comment by kevgliss** [comment]
Please make sure you have pulled the lastest code, that error should have been fixed in: #157

**Comment by sychev-a-k** [comment]
I use latest code and i have problems with create Tag (in tag/views.py), not in cli.py

**Comment by kevgliss** [comment]
Ah sorry about that, you're right. I will put together a PR that fixes those.
