### ISSUE TITLE
Support Google Chat and Meet

### ISSUE THREAD

**Issue by ricey99** [Netflix/dispatch#202]
Any plans, or ways we can use Gsuite Chat and Meet instead of Slack and Zoom?

**Comment by kevgliss** [comment]
We don't currently have support for google chat in the work, but the google plugins already support google meet, in fact, its the default conference type. 

We're open to having Gsuit chat added, but currently don't have an internal use case as we've chosen to centralize on Slack.

**Comment by stefanm8** [comment]
If nobody is working on this I could take it.

**Comment by mvilanova** [comment]
Go for it @stefanm8!

**Comment by anm322** [comment]
@stefanm8 I am also interested in helping with this, if any additional help is needed.
