### ISSUE TITLE
Unable to perform Slack operations: Listener issue (KeyError)

### ISSUE THREAD

**Issue by Achooo** [Netflix/dispatch#2055]
**Describe the bug**

When I try to create a slack channel, or run any slack command. I see issues with a request listener.

**To Reproduce**
1. Setup Slack as documented here: https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack
2. I've set the following:

```
SLACK_WORKSPACE_NAME 
SLACK_SOCKET_MODE_APP_TOKEN
SLACK_API_BOT_TOKEN 
SLACK_SIGNING_SECRET 
SLACK_APP_USER_SLUG 
SLACK_SOCKET_MODE_APP_TOKEN 
```
I got the `SLACK_APP_USER_SLUG` from the [auth.test](https://api.slack.com/methods/auth.test/test) endpoint, the user_id of the bot.
Everything from the slack app config side looks good for the events challenge test, interactive components, etc.
I also see the request payload in the worker on the Dispatch side. Not sharing due to sensitive information.

**Expected behavior**

- No slack channel created for a newly reported incident in the Dispatch UI
- No blockits form when running the slack command, fails with the following:

**Screenshots**
## Slack messaging
<img width="759" alt="Screen Shot 2022-03-10 at 1 36 57 PM" src="https://user-images.githubusercontent.com/23405655/157731883-3a986c70-de1f-4b1e-9266-f10eb747e40b.png">

## Logs
```
ERROR:Failed to run a request listener: 'name', session: s_8750564884622:/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/async_client.py:run_message_listeners:178
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/async_client.py", line 176, in run_message_listeners
    await listener(self, request)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/socket_mode.py", line 44, in process
    response = await handle_slack_command(
  File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/commands.py", line 250, in handle_slack_command
    return await handle_non_incident_conversation_commands(
  File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/commands.py", line 171, in handle_non_incident_conversation_commands
    conversation_name = await dispatch_slack_service.get_conversation_name_by_id_async(
  File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/service.py", line 250, in get_conversation_name_by_id_async
    return (await make_call_async(client, "conversations.info", channel=conversation_id))[
KeyError: 'name'
DEBUG:Message processing completed (type: slash_commands, envelope_id: 76b4594a-86fa-43e2-a6b0-87434dae3eea, session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/async_client.py:run_message_listeners:187
DEBUG:Received message (type: PING, data: bytearray(b'Ping from applink-5d9784f894-6s9qj'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269
DEBUG:Received message (type: PONG, data: bytearray(b'sdk-ping-pong:1646936554.1264064'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269
DEBUG:Received message (type: PONG, data: bytearray(b'sdk-ping-pong:1646936559.1369495'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269
DEBUG:Received message (type: PING, data: bytearray(b'Ping from applink-5d9784f894-6s9qj'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269
DEBUG:Received message (type: PONG, data: bytearray(b'sdk-ping-pong:1646936564.1435585'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269
DEBUG:Received message (type: PONG, data: bytearray(b'sdk-ping-pong:1646936569.1528592'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269
DEBUG:Received message (type: PING, data: bytearray(b'Ping from applink-5d9784f894-6s9qj'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269
DEBUG:Received message (type: PONG, data: bytearray(b'sdk-ping-pong:1646936574.1604586'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269
DEBUG:Received message (type: PONG, data: bytearray(b'sdk-ping-pong:1646936579.168774'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269
DEBUG:Received message (type: PING, data: bytearray(b'Ping from applink-5d9784f894-6s9qj'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269
DEBUG:Received message (type: PONG, data: bytearray(b'sdk-ping-pong:1646936584.1416264'), extra: , session: s_8750564884622):/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/aiohttp/__init__.py:receive_messages:269

## Screenshot of logs
```
$
<img width="1320" alt="Screen Shot 2022-03-10 at 1 33 03 PM" src="https://user-images.githubusercontent.com/23405655/157731277-ce52cc14-f3d2-4508-b274-03460e50d5b7.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browse: chrome
 - Version Version 99.0.4844.51 (Official Build) (x86_64)

**Additional context**

I'd appreciate any guidance fixing this.

**I think the documentation may be missing some bot or user scopes?**

**Comment by mvilanova** [comment]
@Achooo sorry to hear you're having issues with Dispatch. Our Slack documentation is out of date and we're in the process of updating it. Can you answer the following questions so I can help you troubleshoot?
* Did you set the parameters in the `.env` file or the Slack plugin under Settings -> Project -> Plugins?
* What ticketing plugin are you using?
* Is the incident getting named after its creation?
* Any other server errors not provided?

**Comment by Achooo** [comment]
Hi, truly sorry for the delay here!

> Did you set the parameters in the .env file or the Slack plugin under Settings -> Project -> Plugins?

I actually did both

> What ticketing plugin are you using?

Jira plugin. Why does the ticketing plugin matter here?

> Is the incident getting named after its creation?

Yes it is!

> Any other server errors not provided?

No I think that's the only error I see


Additional thoughts:
I think the documentation may be missing some bot scopes.
Is it possible to confirm that those are the correct ones with someone's working setup? : https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack

**Comment by mvilanova** [comment]
I reviewed the bot token scopes and they're correct. In fact, `reminders:write` and `remote_files:read` were not necessary, so I have removed them. I reviewed Slack's socket mode docs and there are no mentions of additional scopes for socket mode to work. 

I'll try to carve some time this week to set up socket mode locally and see if I can repro your issue, as we don't use socket mode in our test or prod environments.

**Comment by Achooo** [comment]
@mvilanova Thank you for keeping this open and looking into it. However, I'm happy to close this issue since no one has upvoted it / nor commented saying they've experienced the same! We've since moved away from testing Dispatch

**Comment by mvilanova** [comment]
@Achooo sorry I haven't been able to get to it yet. Let's keep it open in case others experience the same issue. Would you mind sharing why you decided to not continue testing Dispatch?

**Comment by Achooo** [comment]
@mvilanova Due to time constraints mainly, we moved towards a different solution instead of self-hosting. We were missing a few integrations/features needed. I think it would have been great to contribute to the project, but we were looking for a fast solution as there is limited automation for incident management right now, causing toil for on-call

**Comment by mvilanova** [comment]
Thanks for sharing the context. I'm going to close this issue.
