### ISSUE TITLE
Request For Comment - Recommended Testing Pipeline

### ISSUE THREAD

**Issue by AlexaKelley** [Netflix/dispatch#2085]
Putting this under feature request as it isn't exactly a bug or security issue. 

# Question:
Is there a recommended testing process for upgrading Dispatch? For example is it designed around an assumption of a specific upgrade or deployment process? Is there a particular configuration or process you've had luck with, and if so could you share some of the top level details of it?

## Context
I have experienced some difficulties in finding the best way to provide rapid upgrades and maintenance with Dispatch because of how it's integrated into GSuite and Slack. I'm not in a situation where I can afford to have a duplicate GSuite environment for A/B upgrade testing, and similarly for Slack. This has made it a challenge to test that plugins are functioning properly in a non-prod setup. (for example the way it creates google groups/slack channels/etc) 

Relatedly there have been regular db schema changes and/or changes in how Dispatch was configured that it would break without adjusting configs when upgraded, which put more pressure on having a dev/prod split. 

My current approach has been to dedicate time to take down prod and test manually with creation of categorized test incidents, but this process is so overhead heavy that I've been getting pressure to look at alternatives to Dispatch.

**Comment by kevgliss** [comment]
Hi @AlexaKelley, I'm sorry to hear that the upgrade/testing process isn't as smooth as it could be. In general, I think we can always be better about describing breaking changes for folks. That said, there will probably always have to be some integration testing before rolling out an update internally; so I can try to give you some insight on what works for us.

You mentioned you aren't in a position to have a completely separate dev/test environment with regards to slack/google workspace et al. Internally, we are able to have such an environment and use it heavily to do development, but I think it's probably overkill for someone such as yourself that merely wants to do some light integration testing before pushing an update to production.

Even with a completely separate environment, some things we do that give us additional confidence are:

1) Create an organization/project/incident type within your Prod environment specifically for testing your deployment. 

At what level you wish to do this is up to you. For us, we have a special incident type "Simulation" that is ignored by metrics and does not add anyone other than the reporter to the incident. This gives us confidence core pieces are working but will potentially pollute your external namespaces (e.g. create google groups, jira, etc.,). 

2) Pull snapshots of production data and run the new release against that snapshot.

Database migrations can be tricky, often we might do a dry run on production data snapshot before modifying actual data. Depending on what your setup is like this could also be an opportunity to slightly modify some plugin configuration (e.g. a different Jira project or other naming conventions) if polluting your production namespaces is an issue. 

Hope this helps, let us know if anything is unclear.

**Comment by AlexaKelley** [comment]
Thank you for the thorough response, and this information is helpful. 

I think in my case I may need to find a different way to do testing, but it is very helpful to have clarity on the testing paradigm that the platform was developed against.
