### ISSUE TITLE
Incident dashboards fail to load in UI when user is of Member role

### ISSUE THREAD

**Issue by jeffreynn** [Netflix/dispatch#2213]
**Describe the bug**
Just upgraded to the latest version of dispatch. When logged in as a user with the Member role, the incidents Dashboard fails to load and gives an error message (Something has gone wrong, please retry or let your admin know that you received this error.). This error does not occur when logged in as a user with an Admin role. 

The error seems to be coming from a call to the backend from the incidents dashboard. This returns a 500 message as a Member:

> GET /default/incidents?itemsPerPage=-1&descending[]=false&sortBy[]=reported_at&include[]=closed_at&include[]=commanders_location&include[]=created_at&include[]=duplicates&include[]=incident_priority&include[]=incident_type&include[]=name&include[]=participants_location&include[]=participants_team&include[]=project&include[]=reported_at&include[]=reporters_location&include[]=stable_at&include[]=status&include[]=tags&include[]=title&include[]=total_cost&filter=%7B%22and%22:[%7B%22or%22:[%7B%22and%22:[%7B%22field%22:%22reported_at%22,%22op%22:%22%3E%3D%22,%22value%22:%222022-04-01T04:00:00.000%22%7D,%7B%22field%22:%22reported_at%22,%22op%22:%22%3C%3D%22,%22value%22:%222022-05-17T04:00:00.000%22%7D]%7D]%7D]%7D HTTP/1.1" 500 Internal Server Error

Upon closer inspection, I followed the error to 'src/dispatch/incident/views.py' to this line:     
```pagination = search_filter_sort_paginate(model="Incident", **common)```

**Screenshots**
When logged in as a Member:

![image](https://user-images.githubusercontent.com/91099606/169085222-efd46813-0a2d-4ac5-896b-f11d1b7d0194.png)

**Comment by mvilanova** [comment]
Can you apply https://github.com/Netflix/dispatch/pull/2214 and see if it fixes your problem?

**Comment by mvilanova** [comment]
This issue should've been fixed in https://github.com/Netflix/dispatch/pull/2215

**Comment by jeffreynn** [comment]
Thanks for the quick fix!!!
