### ISSUE TITLE
Unable to change user's role

### ISSUE THREAD

**Issue by rlevit** [Netflix/dispatch#2238]
**Describe the bug**
As an admin of the default organization I want to change another user's role from `member` to `manager` or `owner` and I get an error in the red bottom bar that reads "You don't have permissions to update your organization role." I get the same error in the REST API (see attached screenshots). I don't have Debug logging enabled so all I see in logs is 
`web        | INFO:     10.204.0.37:52367 - "PUT /default/users/4 HTTP/1.1" 403 Forbidden`.

**Expected behavior**
I can change user's role according to the Dispatch documentation [here](https://hawkins.gitbook.io/dispatch/installation#:~:text=After%20one%20owner%20user%20has%20been%20established%2C%20they%20can%20grant%20this%20role%20to%20others%20via%20the%20UI.).

**Screenshots**
![Screen Shot 2022-05-31 at 2 29 37 PM](https://user-images.githubusercontent.com/15822524/171259225-9a9fe7c2-5934-4859-bb59-39a69eee10bd.png)
![Screen Shot 2022-05-31 at 2 30 58 PM](https://user-images.githubusercontent.com/15822524/171259356-9ebd0edc-5204-43fe-9f08-f386eecc8b65.png)

**Comment by mvilanova** [comment]
Thanks for the report. I was able to reproduce it. I'll put a fix for it. In the meantime, please use the following CLI command: `dispatch user update -o <ORG_NAME> -r <ROLE> <EMAIL>`

**Comment by rlevit** [comment]
@mvilanova Thank you for your response. Yes, I can do it if I have `execute` option available but, in my case, I launched the app in AWS ECS with `docker-compose` using ECS context and don't have SSM access to the container so the API was the only non-UI option to do that.

**Comment by mvilanova** [comment]
Fixed it in #2242. Let me know if you still have issues with it.
