### ISSUE TITLE
Non-default organizations are not usable

### ISSUE THREAD

**Issue by rlevit** [Netflix/dispatch#2239]
**Describe the bug**
I want to create and use a new organization in Dispatch. I can create one but can't use it. When I switch to the new organization, regardless whether I am an owner of the default or a new one I get the same `Forbidden` error when I'm trying to browse Members or Projects (I can't see the default project after switching to another org) or trying to create a new project. I also can't find almost no documentation on organizations.

**Expected behavior**
Newly created organizations are fully usable in the same way the default is.

**Comment by mvilanova** [comment]
I wasn't able to repro. Here are the steps I followed:

1. Create new organization called `Test`
2. Used the organization switcher to switch to the new organization
3. Visited http://XXXX/test/settings/members?project=default and did not get any errors
4. Visited http://XXXX/test/settings/projects?project=default and did not get any errors

Can you please share your repro steps?

**Comment by mvilanova** [comment]
I can't see the test data in the default organization when I switch back to it from the test one, so there's clearly an issue impacting the ability to use organizations appropriately. I'll carve time to investigate what's causing the issue.

**Comment by rlevit** [comment]
Hi @mvilanova, I made a screen recording reproducing the steps and the error. Unfortunately the video is too big to be attachable to this issue so I put in on Youtube [here](https://youtu.be/Df1i53rigX4). 

To reproduce the issue, I started from scratch and only modified a few parameters in the `env` file which I believe don't have any influence on the issue. If I name the new organization "Test" everything works fine, but if I name it "Amplify" it doesn't. You will also see in the video that when I switch the org back to "default" the "Amplify" banner still showing up which is probably wrong.

I tried using REST API to manipulate organizations hoping that making the default org `"default": false` and "Amplify" `"default": true` would make the difference but it didn't. I also noticed that both organizations can be set to `"default": true` which might be like that intentionally but I would expect to see only one org marked as "default" and all others not.

**Comment by mvilanova** [comment]
Thanks for the video. There seems to be an auth issue when you're trying to login to the amplify organization. Would you mind sharing your auth provider settings in the `.env` file?

![Uploading Screen Shot 2022-06-02 at 9.42.15 AM.png…]()

**Comment by rlevit** [comment]
@mvilanova sure, theses are the values that I use in the `.env` file
```
# General
COMPOSE_PROJECT_NAME=dispatch
SECRET_KEY=YXN0cm90b29scw==
DISPATCH_JWT_SECRET=YXN0cm90b29scw==
DISPATCH_ENCRYPTION_KEY=YXN0cm90b29scw==
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic
DISPATCH_JWT_SECRET=abcdefg
DISPATCH_JWT_ALG=HS256
DISPATCH_JWT_EXP=86400
```
However, if i'm not mistaken, I experienced this issue even before I configured basic auth. In fact, I configured basic auth to try using REST API with the goal to see if I get the same `Forbidden` error there too.

**Comment by mvilanova** [comment]
The `.env` file looks good. The first error in the screenshot suggests that there's something wrong with the authorization header. Any chance there's something in between your browser and the the Dispatch web server that's altering it or stripping it out? I'm still not able to repro the `Forbidden` issue on my side.

**Comment by rlevit** [comment]
@mvilanova while I have Adblock Plus and Privacy Badger extensions in my browser they are not triggering and not blocking anything. That can be seen in the video too. When extensions block something they indicate number of blocked elements/links. 
To confirm it is not a browser related issue, I commented out all the basic auth related config in the `.env` file and launched a new set of the Dispatch app containers and used Safari to interact with the app. My experience is identical, getting `Forbidden` after creating and switching to the "Amplify" org.

**Comment by mvilanova** [comment]
I was able to repro by creating an org called `Amplify` and am working on a fix.

**Comment by mvilanova** [comment]
`strip()` [here](https://github.com/Netflix/dispatch/blob/master/src/dispatch/main.py#L83) is removing the `a` from `amplify`, which then causes [this](https://github.com/Netflix/dispatch/blob/master/src/dispatch/main.py#L127) else to be evaluated, which throws the `Forbidden` message.

**Comment by rlevit** [comment]
@mvilanova I built a new version of the app from the Dockerfile and switching to a new org doesn't show error anymore but the app version is still `dispatch, version 0.1.0.dev0`. I think you need to bump up the version in the code.

**Comment by mvilanova** [comment]
@rlevit the docker image should be published when we cut the next release today or early next week. We've been really bad at bumping the version, which is currently hardcoded at `0.1.0.dev0`.

**Comment by rlevit** [comment]
No problem. Thank you for the update.
