### ISSUE TITLE
UI issue when using plugin search

### ISSUE THREAD

**Issue by rlevit** [Netflix/dispatch#2245]
**Describe the bug**
This is probably a minor UI issue. When I select a plugin that I want to enable and click on the "Plugin" field again, a dropbox appears that reads '_No Plugins matching "plugin name here"_'.

**To Reproduce**
1. Go to 'http://localhost:8000/default/settings/projects/plugins?project=default'
2. Click on 'New'
3. Select a desired plugin
4. Click on the "Plugin" field again

**Screenshots**
<img width="473" alt="Screen Shot 2022-06-02 at 1 50 17 PM" src="https://user-images.githubusercontent.com/15822524/171695717-24e7d9f1-b474-48a6-865f-d3a910c94557.png">
<img width="485" alt="Screen Shot 2022-06-02 at 1 50 35 PM" src="https://user-images.githubusercontent.com/15822524/171695816-5f355ecd-2f20-4730-b3e7-a785f1524c5f.png">

**Comment by mvilanova** [comment]
Thanks for the report. I think this might be related to a known issue we have with syncing any required fulltext table triggers and functions. I'll look into it when I have some free cycles.
