### ISSUE TITLE
Can't see a new user

### ISSUE THREAD

**Issue by rlevit** [Netflix/dispatch#2249]
**Describe the bug**
In the newly deployed locally Dispatch app, where the `dispatch-local` image was built from Dockerfile pulled today, I created a new organization named `Amplify` with a user (rlevit@amplify.com) who is an admin of the default org. I logged out and changed URL to `http://localhost:8000/amplify/auth/register` and registered with a new user `test@amplify.com`. I ran `docker exec -it dispatch-web-1 bash -c 'dispatch user update --role Owner --organization Amplify test@amplify.com'` command and got `User successfully updated` response.

When I log in to Dispatch as `rlevit@amplify.com` and go to `Members` I see my user but don't see the test user. If I switch to Amplify org I don't see any users. If I log in to Amplify org with the test user I don't see that user in `Members` at all. I see the same thing in the API calls - the test user is not showing up regardless which user auth bearer token I use (rlevit or test). With Dispatch running from the image created by the `install.sh` I was able to see all users in the API and UI. 

**Expected behavior**
All users appear and the `Members` section.

**Screenshots**
<img width="1415" alt="Screen Shot 2022-06-03 at 12 15 43 PM" src="https://user-images.githubusercontent.com/15822524/171919849-45972a70-fd35-4ed1-85ba-d58b492d7054.png">

<img width="1276" alt="Screen Shot 2022-06-03 at 1 43 54 PM" src="https://user-images.githubusercontent.com/15822524/171919860-4417b01f-07aa-4eb3-8f76-d0b61b11ef79.png">

<img width="1275" alt="Screen Shot 2022-06-03 at 1 45 33 PM" src="https://user-images.githubusercontent.com/15822524/171919872-a0454948-e06b-4377-8dd4-33bd87338131.png">

![Screen Shot 2022-06-03 at 1 48 57 PM](https://user-images.githubusercontent.com/15822524/171919886-92fe79c6-f92b-4d60-a1bc-cf829a3b83f1.png)

![Screen Shot 2022-06-03 at 1 52 11 PM](https://user-images.githubusercontent.com/15822524/171919896-b7701cd2-c792-425f-8b0d-378ac288cfa1.png)

**Comment by mvilanova** [comment]
@rlevit thanks for the report. I'll see if I can repro and circle back probably not until next week. Sorry for the inconvenience this is causing.

**Comment by mvilanova** [comment]
@rlevit https://github.com/Netflix/dispatch/pull/2336 should've fixed this issue. Let me know if that's not the case.

**Comment by rlevit** [comment]
@mvilanova I redeployed Dispatch from the latest master and now can see all users registered to a non-default org. Thank you for fixing this.

**Comment by rlevit** [comment]
@mvilanova, oh, sorry, I have to take the previous message back. 

After the login I switched to Amplify org and went to "Settings->Members" and I saw all the user I didn't see before. But I didn't realized that I still was in the "Default" org. So now looks like the org switcher is not working because no matter how many times I click on the arrows sign next to the desired org it won't switch to it. To actually switch to Amplify org I had to replace "default" with "amplify" in the URL and now can't go back to the "default" org using the org switcher. Sorry about confusion. I can make a screen recording to demonstrate the issue.

**Comment by rlevit** [comment]
Great, thank you. Also, after switching to the Amplify org I couldn't see users registered to that org, meaning the issue persists.

**Comment by mvilanova** [comment]
I haven't forgotten about this one. I should be able to resume work on it soon.

**Comment by vijal-patel** [comment]
@mvilanova. are you looking for contributors? If so, I'd like to work on this issue

**Comment by mvilanova** [comment]
@vijal-patel sure, go ahead. Thanks!

**Comment by vijal-patel** [comment]
@rlevit I'm not able to replicate the missing user issue. Can you provide the exact steps you used?
I've tried:
- running everything with docker (did not use install.sh)
- running dispatch with python only

I see @mvilanova is already working on the organization switch issue #2599
