### ISSUE TITLE
Access to example documents restricted 

### ISSUE THREAD

**Issue by rlevit** [Netflix/dispatch#2275]
**Describe the bug**
On [this page](https://hawkins.gitbook.io/dispatch/administration-guide/incident/templates#incident) there are few links to examples that lead to Google Docs but the access to the documents is restricted. It used to work few weeks ago. Please grant access. Thank you.

**To Reproduce**
1. Go to this [link](https://hawkins.gitbook.io/dispatch/administration-guide/incident/templates#incident)
2. Click on example links

**Expected behavior**
Example documents accessible

**Screenshots**
<img width="640" alt="Screen Shot 2022-06-22 at 10 47 08 AM" src="https://user-images.githubusercontent.com/15822524/175059200-72fbcf74-60b6-4628-8c47-d1983007edeb.png">

**Comment by mvilanova** [comment]
This should be fixed now.
