### ISSUE TITLE
Missing image in the docs

### ISSUE THREAD

**Issue by rlevit** [Netflix/dispatch#2276]
**Describe the bug**
The image is missing on [this](url) page. There is an image placeholder with the message that reads "Could not load image".

**Screenshots**
<img width="831" alt="Screen Shot 2022-06-22 at 10 59 59 AM" src="https://user-images.githubusercontent.com/15822524/175062977-39c1b6aa-3b10-461a-93fc-c6b5e4747af1.png">

**Comment by mvilanova** [comment]
Not sure what @kevgliss had in mind here. I'll let him add it when he's back.
