### ISSUE TITLE
Can we get sample data to load in?

### ISSUE THREAD

**Issue by gazzerman2** [Netflix/dispatch#229]
https://github.com/Netflix/dispatch/tree/develop/data

This is not data, this is a "restore" schema for the tables and such, who ever made the dump said schema only rather than schema & data.

**Comment by kevgliss** [comment]
It does contain data: 

https://github.com/Netflix/dispatch/blob/develop/data/dispatch-sample-data.dump#L1831

How are you restoring the database?

**Comment by gazzerman2** [comment]
Ah I missed that line, will try again, I was following the steps in the other issue on loading data. Thanks.
