### ISSUE TITLE
Incidents created with empty name on fresh install

### ISSUE THREAD

**Issue by keithherron** [Netflix/dispatch#2290]
**Describe the bug**
New incidents are created with empty name field after fresh installation

**To Reproduce**
1. Install via ./install.sh method
2. Register account, grant owner privs, and create initial type and priority in the 'default' project
3. Attempt to create a test incident
4. Incident is created, but name is missing 

**Expected behavior**
Incident created with a name following the usual name scheme

**Screenshots**
<img width="1026" alt="Screen Shot 2022-06-23 at 4 26 57 PM" src="https://user-images.githubusercontent.com/702171/175395035-f20d4a7b-8af6-45bf-9452-557a221171b8.png">

**Desktop (please complete the following information):**
 - macOS
 - Chrome 103.0.5060.53

**Additional context**
I see the same issue happen after creating a non-default organization name when using an install that was populated with example data.

**Comment by mvilanova** [comment]
Hi @keithherron, did you add and set up one of the ticket plugins available (e.g. dispatch, Jira) in https://<HOSTNAME>/<ORG_NAME>/settings/projects/plugins?project=<PROJECT_NAME>? Dispatch relies on the plugin to be able to name the incident.

**Comment by keithherron** [comment]
Thanks! This indeed looks to have been my issue, once the ticket plugin is added to the project the name is populated.

Do you think this condition might be worthy of a warning message in the UI/logs, something to the effect of "project has no ticket plugin configured, incidents will not be named" ?
