### ISSUE TITLE
Dispatch Install, Deployment, and Config Support

### ISSUE THREAD

**Issue by Hellboy7** [Netflix/dispatch#2300]
**Describe the bug**
This regards to dispatch slack configuration issue, I have updated the necessary details in slack plugins according to dispatch [[slack documentation](https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack#conversation-management-plugin).] But I am getting multiple errors. 

Errors:

Error from Slack app:
[dispatch-conversion](https://app.slack.com/team/B03M18F5MRV)APP  [8:31 PM](https://sprinklr.slack.com/archives/C03MFS2LV9Q/p1656428466000500)
Looks like you tried to run /dispatch-list-incidents in a conversation where the Dispatch bot is not present. Add the bot to your conversation or run the command in one of the following conversations:
Only visible to you
[8:34](https://sprinklr.slack.com/archives/C03MFS2LV9Q/p1656428680000600)
I see you tried to run /dispatch-list-participants in an non-incident conversation. Incident-specifc commands can only be run in incident conversations.
Only visible to you
[8:39](https://sprinklr.slack.com/archives/C03MFS2LV9Q/p1656428969000800)
I see you tried to run /dispatch-list-my-tasks in an non-incident conversation. Incident-specifc commands can only be run in incident conversations.
Only visible to you
[8:39](https://sprinklr.slack.com/archives/C03MFS2LV9Q/p1656428988000900)
I see you tried to run /dispatch-update-incident in an non-incident conversation. Incident-specifc commands can only be run in incident conversations.
Only visible to you
[8:42](https://sprinklr.slack.com/archives/C03MFS2LV9Q/p1656429169001000)
Looks like you tried to run /dispatch-list-incidents in a conversation where the Dispatch bot is not present. Add the bot to your conversation or run the command in one of the following conversations:

Error from docker backend
ERROR:dispatch.plugins.dispatch_slack.service:SlackError. Response: {'ok': False, 'error': 'channel_not_found'} Endpoint: conversations.info kwargs: {'channel': 'C03MFS2LV9Q'}
ERROR:dispatch.plugins.dispatch_slack.service:SlackError. Response: {'ok': False, 'error': 'channel_not_found'} Endpoint: conversations.info kwargs: {'channel': 'C03MFS2LV9Q'}

**Comment by Hellboy7** [comment]
![Screenshot 2022-06-28 at 8 53 46 PM](https://user-images.githubusercontent.com/61435629/176218513-29886e08-b93b-48f5-bf2a-e11be90e4d2e.png)

**Comment by Hellboy7** [comment]
<img width="1211" alt="Screenshot 2022-06-28 at 8 53 59 PM" src="https://user-images.githubusercontent.com/61435629/176218600-5130661d-42f6-4937-877f-b6a3dd5ca981.png">

**Comment by Hellboy7** [comment]
Hi @mvilanova 
Thanks for the response in the gitter, 
Can you check above issue and screenshots please and help me to sort the problem? 
If you are ok with video call I can set up the meeting, it would be great helpful. Let me know your preference time if it is ok for you?

**Comment by mvilanova** [comment]
The reason why we don't allow you to run slash commands that are built to interact with the incident in non-incident-related channels is because Dispatch needs to know the Slack channel id linked to the incident.

**Comment by Hellboy7** [comment]
Can you help me on the configuration part to sort this issue? I can set-up call if you are ok?
I tried my best to config and troubleshoot the error but I failed.

**Comment by mvilanova** [comment]
Let's give it a try here first if you don't mind. Please share the steps you followed to setup Dispatch and the app/ bot in your Slack workspace.

**Comment by Hellboy7** [comment]
I guess screwed up entire dispatch docker. I am planning to start fresh install from scratch. Just guide me step by step procedure to install. Ill do it myself.

Initially, I installed dispatch from below mentioned github repo is that correct way?
https://github.com/Netflix/dispatch-docker

Then what is this github repo for ? I got confused when I saw below repo.
https://github.com/Netflix/dispatch

**Comment by Hellboy7** [comment]
My current dispatch version in my local machine is > "dispatch, version 0.1.0.dev0". is this latest version?

**Comment by mvilanova** [comment]
> how to run install dispatch using this repo > https://github.com/Netflix/dispatch
If this was a question, the answer is there's no script to install it. You need to pull the checkout the source in your CI/ CD pipeline.

> My current dispatch version in my local machine is > "dispatch, version 0.1.0.dev0". is this latest version?
Yes, ignore the version number. https://github.com/Netflix/dispatch.git#latest will always be the latest stable version.

**Comment by Hellboy7** [comment]
ok once we deploy code in AWS, how do we start the dispatch? In docker, we do docker-compose to start the dispatch.

**Comment by mvilanova** [comment]
You can start the web server by running the following command

`exec /apps/sirtdispatch/bin/dispatch server start dispatch.main:app --workers 6 --host 127.0.0.1 --port 7101 --proxy-headers`

and scheduler by running

`exec /apps/sirtdispatch/bin/dispatch scheduler start`

**Comment by Hellboy7** [comment]
Hi @mvilanova 

Thanks for your continuous support, and I appreciate that.

I did a fresh installation of dispatch in the AWS EC2 instance. Installation is done through the docker image repo (https://github.com/Netflix/dispatch-docker) with an example Postgres SQL data dump for testing. Post that, I have configured slack for dispatch as per instructions in the docs (https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack). This time it worked and whenever I create incident it automatically creates new slack channel for the incident. I have tested few slash commands which worked fine. Need to do further testing. 

Now I need support on to understand few things, I have created Application load balancer in AWS and mapped to dispatch server. I am able to access dispatch through application load balancer link. But, In some instances like in slack channel hyperlinks points to "localhost:8000". Another scenario is after creating incident below "Ticket" section in the same page where hyperlink points to "localhost:8000" and I want that to redirect that to my application load balancer link for example (http://dispatch.com). How to configure that, can you guide me on that? Check the screenshots for reference.

**Comment by Hellboy7** [comment]
![Screenshot 2022-07-01 at 10 32 26 AM](https://user-images.githubusercontent.com/61435629/176828396-e657cd1e-f60e-4643-8d6c-9308fb87cc5b.png)
<img width="742" alt="Screenshot 2022-07-01 at 9 39 49 AM" src="https://user-images.githubusercontent.com/61435629/176828402-b245b9ee-0c98-49b6-9ad5-03a835255223.png">

**Comment by mvilanova** [comment]
Looks like you did not define `DISPATCH_UI_URL` in your `.env` file and Dispatch is using the default. See https://hawkins.gitbook.io/dispatch/administration-guide/server#dispatch_ui_url

**Comment by Hellboy7** [comment]
Hi @mvilanova 

I read through the above mentioned blog post, and some of the info I was able to digest with my basic knowledge but, I felt it was complex.  

After reading the blog, one thing I noticed document says `it should be done during the build time`. But In my case, I have already installed the "dispatch" in AWS EC2 instance. 

Is it possible to modify now? If yes, how to do it? and in which docker image ("dispatch_web_1" or "dispatch_core_1") we should configure the "DISPATCH_UI_URL"? Refer Screenshots.

<img width="601" alt="Screenshot 2022-07-04 at 6 45 52 PM" src="https://user-images.githubusercontent.com/61435629/177163700-8d4669c2-20be-4d78-9332-a99e586319ca.png">

I searched ".env" file in the both docker images of "dispatch_web_1" & "dispatch_core_1" under the file locations which is mentioned below. I could not find any such file with extenion of ".env". where exactly this file is located? Refer Screenshots.

File Locations: `/usr/local/lib/python3.9/site-packages/dispatch/static/dispatch/`

<img width="1338" alt="Screenshot 2022-07-04 at 6 34 18 PM" src="https://user-images.githubusercontent.com/61435629/177163708-a09e3f19-7b97-4fc9-8f45-1508e368355d.png">

or Should I install from the beginning?

**Comment by mvilanova** [comment]
That's correct. The `.env` file needs to be in the same directory as the `install.sh` Bash script when you run the script to build the docker images. We provide a sample one [here](https://github.com/Netflix/dispatch-docker/blob/master/.env.example).

**Comment by Hellboy7** [comment]
Hi @mvilanova 

As suggested, I have created new ".env" file in the "dispatch-docker" directory with the content mentioned below:

`[ec2-user@ip-10-1-2-10 .github]$ cat .env 
# General
COMPOSE_PROJECT_NAME=dispatch
#SECRET_KEY=REPLACEWITHSOMETHIINGSECRET
#DISPATCH_JWT_SECRET=REPLACEWITHSOMETHIINGSECRET
#DISPATCH_ENCRYPTION_KEY=REPLACEWITHSOMETHIINGSECRET

# Database
# NOTE: Ensure that DATABASE_CREDENTIALS match the values passed to POSTGRES_USER and POSTGRES_PASSWORD
DATABASE_CREDENTIALS=dispatch:dispatch
DATABASE_HOSTNAME=postgres
DATABASE_NAME=dispatch
DATABASE_PORT=5432

# Used by postgres docker
POSTGRES_DB=dispatch
POSTGRES_PASSWORD=dispatch
POSTGRES_USER=dispatch

# For additional server configuration options see: https://hawkins.gitbook.io/dispatch/administration-guide/serve
DISPATCH_UI_URL=http://dispatch-webapp-10xx6597.us-xxx-xx.elb.amazonaws.com/'`

**Comment by Hellboy7** [comment]
In `docker-compose.yml` file I changed the `build:context` url from `https://github.com/Netflix/dispatch.git#latest` to `https://github.com/Netflix/dispatch.git` which worked fine. is something wrong with that or this is not the best practice? Refer to screenshot.

<img width="710" alt="Screenshot 2022-07-08 at 9 24 49 AM" src="https://user-images.githubusercontent.com/61435629/177913857-1abb9456-76f2-4aef-b28d-8b0b555a7628.png">

**Additionally, I need support on a few things:**

1. Few dispatch CLI commands are not working and it shows some warnings like "doesn't match supported versions!": Refer to screenshot.
<img width="1065" alt="Screenshot 2022-07-08 at 8 32 31 AM" src="https://user-images.githubusercontent.com/61435629/177913918-50488110-48e1-4a1c-9cde-196470ee2d8a.png">

<img width="1740" alt="Screenshot 2022-07-08 at 9 19 43 AM" src="https://user-images.githubusercontent.com/61435629/177913982-ea9ead9b-a8a5-4bdb-a409-c6b03c1c0c53.png">


2. Is possible to change the Org name "default" to any other name or can we delete the Org "default"? Refer to screenshot.
![Screenshot 2022-07-08 at 9 21 44 AM](https://user-images.githubusercontent.com/61435629/177913963-8e142f2b-ac27-41ec-8b4e-b7ee4a66c434.png)

3. How to reset a user password? "User management stuff" like user creation etc.

**Comment by rlevit** [comment]
+1 for being able to delete the default org entirely or rename it so creating a new org wouldn't need to be necessary.

**Comment by mvilanova** [comment]
> Few dispatch CLI commands are not working and it shows some warnings like "doesn't match supported versions!": Refer to screenshot.

See my comment here: https://github.com/Netflix/dispatch/issues/2300#issuecomment-1177902119

> Is possible to change the Org name "default" to any other name or can we delete the Org "default"? Refer to screenshot.

No, not at the moment.

> How to reset a user password? "User management stuff" like user creation etc.

If you're using basic auth, you can use CLI command `dispatch user update`

**Comment by Hellboy7** [comment]
Hi @mvilanova 

Thanks for the continuous support and information.

https://github.com/Netflix/dispatch/issues/2300#issuecomment-1177902119

I read the above comments. I understood bit of it `It is not error, and it is warning`. But is there anyway to solve those warnings. Because, In `docker-compose.yml` when I use `git#latest` in the `build:context` URL place. It fails with warning signs and does not proceed further. 

Refer to the **second screenshot** for warning sign details: https://github.com/Netflix/dispatch/issues/2300#issuecomment-1177108282

The reason why I ask above question repeatedly, because multiple times I update `.env` file to test few things. So post that I run `./install.sh` script in the [dispatch-docker](https://github.com/Netflix/dispatch-docker) folder which updates env variables for me. But last few times it failed with URL of "https://github.com/Netflix/dispatch.git#latest" and it did not update env variables and also `./install.sh` script stopped with `ERROR: error fetching: fatal: couldn't find remote ref latest : exit status 128`. So I started using to URL "https://github.com/Netflix/dispatch.git" which worked successful and updated the env variables. Any workaround to sort this problem to use `git#latest`.

**Comment by Hellboy7** [comment]
Hi @mvilanova 

Does dispatch support OAUTH through an app-registration on Azure AD? Because, our org is moving to Azure AD from GCP (G-Suite).

**Comment by mvilanova** [comment]
@Hellboy7 `latest` tag should work again. Let me know if that's not the case.

Dispatch supports basic login/password, [PKCE](https://oauth.net/2/pkce/), and custom auth providers. PKCE is the way to go for your use case. This article seems like a good start: https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/openidoauth-tutorial

**Comment by Hellboy7** [comment]
Hi @mvilanova 
As suggested, I have update the URL with `latest` tag in the `docker-compose.yml` file and executed the `./install.sh` script. 
![Screenshot 2022-07-12 at 9 22 38 PM](https://user-images.githubusercontent.com/61435629/178537415-3481b7e0-e1a0-477a-ab07-ae24cfc17cd1.png)
But, I got following `warnings/errors`. Refer screenshot.
Screenshot 1
![Screenshot 2022-07-12 at 9 21 45 PM](https://user-images.githubusercontent.com/61435629/178538012-e27cd3be-41bb-4a18-a80f-a8d73601cc74.png)
Screenshot 2
![Screenshot 2022-07-12 at 9 22 03 PM](https://user-images.githubusercontent.com/61435629/178538234-1df45e2a-4738-4151-9f6f-c16a4bd6f99c.png)

**Comment by mvilanova** [comment]
I reverted the changes in https://github.com/Netflix/dispatch/pull/2304, which caused this issue. You'll need to remove the `latest` label to leverage the changes. Can you run the script and let me know if it is resolved?

**Comment by Hellboy7** [comment]
Hi @mvilanova 
Thanks for the fix, That worked fine with minor warnings!!!

I am not able to switch the Org in the Dispatch UI!!!

![Screenshot 2022-07-13 at 10 06 11 AM](https://user-images.githubusercontent.com/61435629/178652772-e03f1a8f-4eda-40da-a906-2e0abfaada12.png)

I am able to access the projects by changing the Project names in URL. 

Project 1: `https://dispatch-netflix[.]com/`default`/dashboards/incidents`
Project 2: `https://dispatch-netflix[.]com/`sprinklr`/dashboards/incidents`

**Comment by mvilanova** [comment]
Known problem. Working on a fix.

**Comment by Hellboy7** [comment]
Thank you so much for the support so far !!!
I am currently working SSO integration with Azure AD. I will update my journey on this if it was successful and document it. It may be useful for others in the community.

**Comment by Hellboy7** [comment]
Hi @mvilanova 
I see new pull requests, How to update this? Same procedure like running the script "./install.sh" or any different ways to update the dispatch with latest changes done in the repo?

**Comment by Hellboy7** [comment]
Again, when I tried to run "./install.sh" script, I got error check the screenshot.
<img width="1682" alt="Screenshot 2022-07-18 at 9 30 19 AM" src="https://user-images.githubusercontent.com/61435629/179444017-91271d17-4ddd-41db-b1d3-57758f988327.png">
`error: could not write to 'build/lib/dispatch/static/dispatch/node_modules/prettier-eslint/node_modules/typescript/lib/typescriptServices.js': No space left on device
Removing intermediate container 64c6c37d51ce
ERROR: Service 'core' failed to build: The command '/bin/sh -c export YARN_CACHE_FOLDER="$(mktemp -d)"     && cd /usr/src/dispatch     && python setup.py bdist_wheel     && rm -r "$YARN_CACHE_FOLDER"     && mv /usr/src/dispatch/dist /dist' returned a non-zero code: 1
Cleaning up...`

**Comment by mvilanova** [comment]
@Hellboy7 you can run the install script when a new release goes out or remove `#latest` from [here](https://github.com/Netflix/dispatch-docker/blob/master/docker-compose.yml#L22) and run the install script any time you want to pull any new changes.

**Comment by mvilanova** [comment]
@Hellboy7 all good here? Can we close this issue?
