### ISSUE TITLE
Individual contact name overwritten on incident creation

### ISSUE THREAD

**Issue by keithherron** [Netflix/dispatch#2309]
**Describe the bug**
After creating a new incident individual contact name is shown as either "unknown" or "user@email.com"

**To Reproduce**
1. Switch to a non-default organization 
2. Set individual contact name in settings > project > contact > individuals to reflect their actual name, e.g. "Darth Vader"
3. Create an incident as this individual in the project updated in step 2
4. Their contact name is updated to either "unknown" (empty), or their email address

**Expected behavior**
The contact individual name is not altered once set.

**Additional context**
My test environment is using an organization of 'companyname'.   The project has plugins dispatch-ticket, dispatch-contact and slack-conversation enabled.

**Comment by mvilanova** [comment]
I'll see if I can repro and circle back as soon as I can.
