### ISSUE TITLE
Assignable default organization

### ISSUE THREAD

**Issue by keithherron** [Netflix/dispatch#2310]
**Is your feature request related to a problem? Please describe.**

Possibly, the problem could very well be operator error/misunderstanding as well!

Currently my environment has two organizations present, 'default' and 'companyname'.  'default' was created automatically, and 'companyname' was created by me via the UI and contains my site specific configuration.

The problem I'm currently encountering is needing to manually switch projects after login and managing user/registration/incident/etc creation between orgs.

I haven't yet found an inbuilt option to make 'companyname' behave as the default org in terms of automatic selection upon login, register, incident creation, etc.

Additionally, the register option presented at the root of the site leads to the default org.  I don't see an option to select org before login/register and using /companyname/auth/register yields a "no default project defined" error upon registration.  However I don't see a toggle to select a default project in project settings.

Overall I don't actually need multiple orgs enabled (at least should not any time soon), but the naming scheme dispatch-companyname-project-N is much preferable over dispatch-default-default-N.

**Describe the solution you'd like**

An option to make an org behave as the default
An option to delete or hide unused orgs
Documentation enhancements outlining/clarifying how orgs are intended to be used, setup requirements/steps etc.

**Describe alternatives you've considered**

Currently considering an HTTP rewrite from /default to /companyname, although unsure if this would work partially due to the "no default project defined" registration error mentioned above

**Comment by mvilanova** [comment]
I added support for default projects under member settings recently and am planning to do the same for organizations in the near future, so those are used/ applied throughout the app upon login.
