### ISSUE TITLE
Grafana oncall plugin feature request

### ISSUE THREAD

**Issue by lerra** [Netflix/dispatch#2323]
It would be awesome to have a plugin for [grafana oncall](https://github.com/grafana/oncall), an open source alternative (with SaaS as option) to the SaaS only oncall services that is supported today (pagerduty & opsgenie).

**Comment by mvilanova** [comment]
Hi @lerra, we're happy to guide you (or someone else) through the process of building a plugin for it and review and merge the code for it, but we're not going to have cycles to do it ourselves.
