### ISSUE TITLE
Registered members only appear in default organization

### ISSUE THREAD

**Issue by keithherron** [Netflix/dispatch#2334]
**Describe the bug**
When a user registers they appear only as a member of the default org, even if assigned a role (e.g. admin) in another org.  I only see one account in the members section (which has owner privs) at present

**To Reproduce**
1. Go to dispatch instance
2. Register new account
3. Account appears only in default org
4. Grant privileges to other org (e.g. admin of 'companyname' org) via CLI 
5. Account not appearing in org member list

**Expected behavior**
Expected available registered accounts to appear in the org member list, especially if an account has been granted additional privileges 

**Additional context**
Possibly related to 2310 where an error is encountered when attempting to register an account on a non-default org.  Still I would have thought users that can access the org would appear in the member list.

**Comment by mvilanova** [comment]
Thanks for the report @keithherron. We'll look into it as soon as I can.

**Comment by mvilanova** [comment]
https://github.com/Netflix/dispatch/pull/2336 fixes your issue and other issues I found when I was troubleshooting.
