### ISSUE TITLE
Only the first task runs in a list of 1+ BackgroundTasks tasks.

### ISSUE THREAD

**Issue by 3c-un-str** [Netflix/dispatch#2383]
**Describe the bug**
In the file ...plugins/dispatch_slack/events.py, in event_functions, in the key ["message"], five (in my case six) functions/background tasks are added during the execution of handle_slack_event, but only the first task in the list runs successfully. 

**To Reproduce**
Change the order of the tasks in the list, the execution always stops during the second; execution seems to be stopping here: ...->...>BackgrounTask/run_in_threadpool -> starlette.concurrency/run_sync ->anyio.to_thread.get_asynclib() -> anyio._backends._asyncio/run_sync_in_worker_thread ->  **await checkpoint()** 

**Environment and Setup**
Using the latest version.

**Comment by mvilanova** [comment]
Thanks for the report. I'll look into it and circle back.

**Comment by mvilanova** [comment]
I wasn't able to repro. All functions under the message key executed and in the listed order. If you have more info that can help me try to repro the issue you're observing, let me know.

executing <function increment_activity at 0x14dce5430>
executing <function after_hours at 0x14dce55e0>
executing <function ban_threads_warning at 0x14dce5940>
executing <function message_tagging at 0x14dce5a60>
executing <function message_monitor at 0x14dce5b80>

**Comment by 3c-un-str** [comment]
Interesting. I can get it to reliably fail after the first task; the execution just seems to stall during the second task. 

**Original order of tasks**
Adding -- <function increment_activity at 0x7fb6313108b0>
Adding -- <function handle_message_to_channel at 0x7fb631310790>
Adding -- <function after_hours at 0x7fb631310a60>
Adding -- <function ban_threads_warning at 0x7fb631310dc0>
Adding -- <function message_tagging at 0x7fb631310ee0>
Adding -- <function message_monitor at 0x7fb63bb7f040>
Executing-- <function increment_activity at 0x7fb6313108b0>
Executing -- <function handle_message_to_channel at 0x7fb631310790>

**Order changed**
Adding -- <function handle_message_to_channel at 0x7fa7efc75790>
Adding -- <function increment_activity at 0x7fa7efc758b0>
Adding -- <function after_hours at 0x7fa7efc75a60>
Adding -- <function ban_threads_warning at 0x7fa7efc75dc0>
Adding -- <function message_tagging at 0x7fa7efc75ee0>
Adding -- <function message_monitor at 0x7fa7f7149040>
Executing -- <function handle_message_to_channel at 0x7fa7efc75790>
Executing -- <function increment_activity at 0x7fa7efc758b0>

The second seems to be start, but is silently failing at anyio._backends._asyncio:functools.partial(<function increment_activity at 0x7fa7efc758b0>:run_sync_in_worker_thread:784. 

Not sure what other info I can give you.? Any other ideas? 

Thank You,

**Comment by 3c-un-str** [comment]
I setup a simple web app (using starlette==0.19.1) in my dev env, with three BackgroundTasks and ran it with uvicorn==0.18.2; all of them ran successfully. I am kind at a loss here :); I will continue to debug and update with any findings.

**Comment by 3c-un-str** [comment]
**Update:** According to https://github.com/encode/starlette/issues/1438, it looks like BackgroundTasks are cancelled if the client closes connection. It also looks like there is still discussion around the best way forward (several others seem to have reported similar issues). 

As a workaround, I added the below line to .../starlette/background.py (essentially shielding the tasks from cancelling; was suggested in the comments), and all the tasks have been running successfully since. Although sometimes, there is a 1-2 minute pause after the first|second task has run before (2|3)-6 resume operation (need to look into this more). 

-        if self.is_async:
-            await self.func(*self.args, **self.kwargs)
-        else:
-            await run_in_threadpool(self.func, *self.args, **self.kwargs)
+        with anyio.CancelScope(shield=True):
+            if self.is_async:
+                await self.func(*self.args, **self.kwargs)
+            else:
+                await run_in_threadpool(self.func, *self.args, **self.kwargs)


I am guessing that Slack API servers are closing the connection (should they? probably not?) after sending the command to the request/load URL defined in the app's settings, causing the tasks to be cancelled before completion; I ran tcpdump on my end to confirm the 4-way handshake (FIN(from_slack)->ACK(from_server)->FIN(from_server)->ACK(from_slack)). 

This behavior might also explain why only the first task was running prior to this change. 

If it's ok, I'd like to leave this issue open for a few days before closing it, as it may help others.  

Thanks again.

**Comment by mvilanova** [comment]
Nice work troubleshooting it. Agree, let's keep it open until the issue is fixed on the starlette side.
