### ISSUE TITLE
Please provide more details on Slack Integration

### ISSUE THREAD

**Issue by gazzerman2** [Netflix/dispatch#239]
How does the whole slack thing work, can I see a demo by any chance as its not clear at all by the documentation. Thanks!
I have a bot, I have all the info in the `.env`. Can I start incidents from Slack? 
![Screenshot 2020-04-21 at 17 07 06](https://user-images.githubusercontent.com/56310190/79887483-d5c4f300-83f2-11ea-97a7-90594ae37150.png)

**Comment by mvilanova** [comment]
Basically, we use Slack for real-time communications. The Dispatch Slack plugin uses the Slack app's bot token to send requests to a variety of API methods to create the channel, etc. The app is added to the channel, so we can process events such as when a member is added or a message is posted. The app also exposes a set of slash commands to allow the incident commander to manage the life cycle of the incident.

Did you follow all the instructions in the documentation [here](https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-slack)? The error that you shared makes me think that you have not defined the slash commands in the Slack app.

Also, note that command `/dispatch-mark-active` has been deprecated. You can change the status of the incident using the `/dispatch-update-incident` command.

Let us know how we can make the documentation better!

**Comment by gazzerman2** [comment]
Thanks can you walk me through a day in the life scenario with slack in the mix is it like this:

1. I open an incident in the webUI
2. This opening of the Incident sends API calls to Slack to create a channel
3. The channel gets a name and the person (who is authorized and logged into the web) gets added to the slack channel
4. During an incident we use Slack to discuss next steps... 
etc etc

**Comment by mvilanova** [comment]
Yes, pretty much. The incident commander and the rest of participants that get added to the incident channel do not necessarily need to be logged in into the Web interface. You define which oncall service needs to be resolved based on incident type and who needs to be added based on incident type, priority, terms, etc. in the Web interface. Once on the channel, the incident commander can use the slash commands that the bot exposes to make changes to the incident, post status updates, etc. You can also make changes to the incident in the Web interface.

**Comment by gazzerman2** [comment]
Thanks a lot, that really helps!
