### ISSUE TITLE
[feature request] Print all config items in server config command, instead of showing .env file contents

### ISSUE THREAD

**Issue by tsekine354** [Netflix/dispatch#243]
`dispatch server config` command, or `show_config()` in https://github.com/Netflix/dispatch/blob/develop/src/dispatch/cli.py#L804, shows no configs when dispatch is brought up via docker-compose, as all configs are read from system environment variables, not local `.env` file.

Additionally, `starlette.config.Config.get()` can take default value, but `show_config()` ignores that, or it prints only explicitly configured values. What I really expect is to print what dispatch interpreted given configurations (i.e. `cast=...` should be considered somehow). I don't mind how .env file is parsed.

I haven't dig internals of dispatch, but what I expect is something in pseudo-code:

```
from dispatch.config import config

core_configs = config.get_configs()
table = [item for item in core_configs.items()]
for p in plugins.all():
  plugin_configs = p.get_configs()
  table += [item for item in plugin_configs.items()]

click.secho(tabulate(table, ...
```

This means, ` config.py` and each plugins are supposed to implement `get_configs()` function, but it shouldn't be hard.

**Comment by kevgliss** [comment]
Interesting. We typically only use .env files for configuration show we haven't come across this issue. Under the hood we just use starlette config, which does read from the envvars but perhaps not in this context?

https://www.starlette.io/config/

**Comment by tsekine354** [comment]
When dispatch is brought up via docker-compose,  `.env` environment file is parsed by docker-compose
https://github.com/Netflix/dispatch-docker/blob/master/docker-compose.yml#L24
then those variables are given to each docker container as environment variables.

Those environment variables are stored in `config.environ` 
https://github.com/encode/starlette/blob/master/starlette/config.py#L55
while .env file parsed by dispatch (or its underlying starlette) are stored in `config.file_values`.

You use only latter one, so `show_config()` is implemented to support that case only.

But that's not the main point. Regardless how `.env` contents are given to dispatch, my feature request is to show parsed config, not to show what are given.

One of typical use case is to detect typo in variable name. If I made a typo in variable name but it has default value (or, the variable is referenced by `config(..., default=...)`), I expect to see the default value on `show_config()`, so that I could find that there are some problems in config. Current code displays just the typo as-is, then I'll observe unexpected behavior, then I'm supposed to dig deeper to see if it's bug of program or misconfiguration of program.

**Comment by kevgliss** [comment]
I've put together #264... I think it's kind of hacky but it's not terrible. Please let me know if that satisfies your use case.
