### ISSUE TITLE
Problems with authentication after last upgrade

### ISSUE THREAD

**Issue by sychev-a-k** [Netflix/dispatch#244]
Hello!
I have problems with auth after upgrade dispatch.
![image](https://user-images.githubusercontent.com/29555052/79978542-c3a58c00-84a8-11ea-89b0-f840f696bc53.png)
My .env config this
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=
DISPATCH_AUTHENTICATION_PROVIDER=
#DISPATCH_AUTHENTICATION_PROVIDER=""
#DISPATCH_AUTHENTICATION_PROVIDER_SLUG=
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=

# Frontend
#VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL=""
#VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID=""

**Comment by gazzerman2** [comment]
I am stuck on auhentication now, where did you put in  the following?

"authorization_endpoint": 
"token_endpoint":

**Comment by mvilanova** [comment]
@kevgliss can confirm, but I think his ongoing PR (https://github.com/Netflix/dispatch/pull/241/) should fix these problems.

**Comment by sychev-a-k** [comment]
I create account via /register, but i have same error.
Ho can I create this ?
"authorization_endpoint":
"token_endpoint":

i didn't find anything about this in docs?

**Comment by kevgliss** [comment]
@sychev-a-k #250 should fix your immediate problem. Please try it out.

**Comment by sychev-a-k** [comment]
Today i have problems with build dispatch web after upgrade
![image](https://user-images.githubusercontent.com/29555052/80074094-5863c480-8551-11ea-859c-9031641350c4.png)
