### ISSUE TITLE
Authentication plugin from request headers?

### ISSUE THREAD

**Issue by filippog** [Netflix/dispatch#2447]
**Is your feature request related to a problem? Please describe.**
We're testing/deploying Dispatch behind SSO (implemented by [mod_auth_cas](https://github.com/apereo/mod_auth_cas)). Requests are reverse-proxied to Dispatch on localhost by Apache.

**Describe the solution you'd like**
We'll be implementing a plugin to authenticate users based on request headers, is this something you'd be interested in shipping with Dispatch / accepting PRs for ?

thank you!

**Comment by mvilanova** [comment]
Hi @filippog, yes, I'll be happy to review and merge the plugin code.
