### ISSUE TITLE
Paging on-call does not work when using / commands from private channel

### ISSUE THREAD

**Issue by rivlinpereira** [Netflix/dispatch#2513]
**Describe the bug**
See the following error when I try to engage the on-call person from a private channel that dispatch creates 

`Sorry, we've run into an unexpected error. For help please reach out to your Dispatch admins and provide them with the following token: xxxxxxxxx`

**To Reproduce**
1. Create incident
2. Go to the private channel that dispatch creates
3. Try to use /dispatch-engage-oncall 
4. Choose the service 
5. You will see the error above

**Expected behavior**
The  /dispatch-engage-oncall should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Browser chrome
 - Version 105.0.5195.102

**Additional context**

**Comment by mvilanova** [comment]
@rivlinpereira is there an error in the server logs that you can share? Did you configure the [pagerduty](https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-pagerduty) or [opsgenie](https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-opsgenie) plugins?

**Comment by rivlinpereira** [comment]
> @rivlinpereira is there an error in the server logs that you can share? Did you configure the [pagerduty](https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-pagerduty) or [opsgenie](https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-opsgenie) plugins?

Using pagerduty plugin configured via UI. I dont see any errors in logs

**Comment by mvilanova** [comment]
Sounds like you were able to resolve it based on this [discussion](https://github.com/Netflix/dispatch/discussions/2514#discussioncomment-3637721)? Feel free to close the issue if so.

**Comment by rivlinpereira** [comment]
> Sounds like you were able to resolve it based on this [discussion](https://github.com/Netflix/dispatch/discussions/2514#discussioncomment-3637721)? Feel free to close the issue if so.

yes but now facing another issue. closing this one
