### ISSUE TITLE
Cant create incident when role policy is enabled

### ISSUE THREAD

**Issue by mvilanova** [Netflix/dispatch#2516]
### Discussed in https://github.com/Netflix/dispatch/discussions/2515

<div type='discussions-op-text'>

<sup>Originally posted by **rivlinpereira** September 13, 2022</sup>
I am looking into the commander to be paged by default when an incident is opened. So I created a policy under roles -->Incident Commander  and matching it to incident type and tag types to page the commander. If i enable the policy the incident creation does not work. What am i missing? </div>

**Comment by mvilanova** [comment]
Can you share server logs when the issue is happening @rivlinpereira?

**Comment by mvilanova** [comment]
Is the `page commander` checkbox checked in the incident type?

**Comment by rivlinpereira** [comment]
> Is the `page commander` checkbox checked in the incident type?

yes it is checked
