### ISSUE TITLE
Code duplication in service layer

### ISSUE THREAD

**Issue by kiriharu** [Netflix/dispatch#2532]
Hello!

I'm checking out different projects on github written with FastAPI for educational purposes. I am searching for interesting snippets, ideas and examples of various pattern implementations.
I find such functions in service layer almost in every package:

https://github.com/Netflix/dispatch/blob/4979063922eab0a3573686c026887b84371b4f9c/src/dispatch/conversation/service.py#L8-L10

https://github.com/Netflix/dispatch/blob/4979063922eab0a3573686c026887b84371b4f9c/src/dispatch/document/service.py#L11-L13

https://github.com/Netflix/dispatch/blob/4979063922eab0a3573686c026887b84371b4f9c/src/dispatch/feedback/service.py#L11-L13

There is absolutely no difference except arguments and models. This is boilerplate code. I wonder why it isn't something like:

```python
def get(*, db_session: Session, model: T, **kwargs) -> Optional[T]:
    return db_session.query(model).filter(**kwargs).one_or_none()
```

Looking forward to know the motivation for the current choice. Thank you in advance!

**Comment by mvilanova** [comment]
@kiriharu thanks for reaching out. You're correct, it's boilerplate code. Same for other service functions like `get_all()` and `delete()` and probably others like `get_by_name()` etc. Refactoring and consolidating these function calls into a common service module might make sense in the future to reduce amount of code and maintenance.
