### ISSUE TITLE
STATIC DIR error after last upgrade

### ISSUE THREAD

**Issue by sychev-a-k** [Netflix/dispatch#254]
After auth error and upgrade i found this error
![image](https://user-images.githubusercontent.com/29555052/80087140-628ebe80-8563-11ea-82ab-040518a50ece.png)

**Comment by mvilanova** [comment]
@sychev-a-k can you create the `dist` directory manually and try again? I was able to start the server after removing the `dist` directory from my local install.

**Comment by kevgliss** [comment]
If you do a `pip install -e .` locally it should create a dist directory with all the required JS. Please let us know if that is not happening.

**Comment by sychev-a-k** [comment]
I add in my Dockerfile this command
RUN cd /usr/src/dispatch && pip install -e . 
And it is not helping me(
i cannot run this command locally, because my docker container was exited with this error.

**Comment by kevgliss** [comment]
Are you using your own docker imagine or the official dispatch docker?

**Comment by sychev-a-k** [comment]
I am using official dispatch docker

**Comment by kevgliss** [comment]
Can you be more specific about the steps you took? 

I'd suggest:
- Deleting all containers/images
- run git pull on https://github.com/Netflix/dispatch-docker
- run `./install.sh`
- run `docker-compose`

I was not able to recreate your issue doing the above.
