### ISSUE TITLE
Can't create new plugin instance

### ISSUE THREAD

**Issue by caioaao** [Netflix/dispatch#2570]
**Describe the bug**
When trying to create a plugin instance through the dashboard (namely slack-converation and slack-contacts), instead of creating the instance I receive the following error message:

> str type expected

This is the HTTP response body (status code is 422):

```json
{
	"detail": [
		{
			"loc": [
				"body",
				"project",
				"name"
			],
			"msg": "str type expected",
			"type": "type_error.str"
		}
	]
}
```

**To Reproduce**
1. Go to `Projects -> "default" -> Plugins -> New`
2. Choose `slack-conversation` and fill in details
3. Click on "save" button

**Expected behavior**
Plugin Instance is created

**Screenshots**
Error Message:
![Screenshot_20221003_185846](https://user-images.githubusercontent.com/1395990/193693842-f8de59d0-c028-419c-a5a0-e61356f3a786.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Tested on Chromium and Firefox
 - Dispatch release: https://github.com/Netflix/dispatch/releases/tag/v20220915

**Additional info**
I'm trying to debug this, but I never used Vue so it might take a little of time.

**Comment by mvilanova** [comment]
Thanks for the report. We will try to see if we can repro it on our side and circle back as soon as we can.

**Comment by caioaao** [comment]
Just tested on master and it worked, so maybe it was fixed?
