### ISSUE TITLE
switching organization in UI is not working

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch#2595]
Reg: https://github.com/Netflix/dispatch/pull/2528

Switching from the organization option still not working, its still showing same data, I cant able to switch
<img width="936" alt="dispatch-is1" src="https://user-images.githubusercontent.com/21236859/195404284-56c1dc8d-b891-4bb0-b6ec-2faff81b6b19.PNG">

If I edit url /default to /mytest its throwing below error and in the project list its still showing all projects which Ihave created default organizations

![image](https://user-images.githubusercontent.com/21236859/195405767-9c78b5e5-5e29-4dc5-9e22-2f5ca3d84a0b.png)

**Comment by mvilanova** [comment]
Known problem. We will fix it as soon as we can.
