### ISSUE TITLE
Okta integration issue in dispatch

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch#2622]
I'm trying to integrate okta for identity management to dispatch application (instead of creating users manually)

here is my variables added inside .env

DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
DISPATCH_JWT_AUDIENCE=xxxxxxxxxxxxxx
DISPATCH_PKCE_DONT_VERIFY_AT_HASH=true
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=https://trial-xyz.okta.com/oauth2/v1/keys
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID=xxxxxxxxxxxxxxx
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL=trial-xyz.okta.com
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
VUE_APP_DISPATCH_CLIENT_ID=xxxxxxxxxxxxxxxxxxx
VUE_APP_DISPATCH_OPEN_ID_CONNECT_URL=trial-xyz.okta.com

here is my okta side conf, 
<img width="910" alt="a1" src="https://user-images.githubusercontent.com/21236859/197535480-5406f31b-14e3-4cfd-8228-16e4dcef079e.PNG">

I couldnt able to do, 

<img width="328" alt="a2" src="https://user-images.githubusercontent.com/21236859/197535489-74af8bac-263f-4cae-866a-e6c6ce857467.PNG">

Did anyone used okta, can you please guide me to integrate with disptach, what Im doing wrong here

**Comment by csetarun2** [comment]
![image](https://user-images.githubusercontent.com/21236859/197687683-430a56b3-4ace-4d22-9a7b-39bf95de1508.png)

**Comment by kevgliss** [comment]
We have had folks successfully setup Dispatch with Okta. While I am not super familiar with that IdP I do see some history using the id token instead of the access token. I.e. setting `VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_USE_ID_TOKEN=true` in the config while building the project. 

See: 
https://hawkins.gitbook.io/dispatch/administration-guide/server#vue_app_dispatch_authentication_provider_use_id_token-default-false

**Comment by csetarun2** [comment]
Thanks @kevgliss for your help, I will check and let you know

**Comment by csetarun2** [comment]
Thanks @kevgliss , I could able to integrate okta, there is one more issue Im facing, can u check this
https://github.com/Netflix/dispatch/issues/1597
getting blank page , added screenshots in the above issue-1597, can you please check
