### ISSUE TITLE
Renaming organizations

### ISSUE THREAD

**Issue by keithherron** [Netflix/dispatch#2657]
**Is your feature request related to a problem? Please describe.**

Essentially yes.  I'm currently unable to (or not clear on how to) change the default org name, and would prefer not to have incidents named e.g. dispatch-default-project-1.  dispatch-companyname-project-1 would be preferred

**Describe the solution you'd like**

I'd like my instance to have only one organization.  Ideally it would be 'companyname' as opposed to 'default'.

Is it possible to rename the default organization? 

If so, how?  And could a feature be added to simplify the process.

If not, what would be the recommend way to accomplish deploying dispatch with a single organization of 'companyname'?

**Describe alternatives you've considered**

I've considered creating org 'companyname' alongside org 'default' and deploying web server redirects to "pin" users to a certain org via the URL e.g. https://dispatch.example.org/companyname/ but I think handling within dispatch would be better.

**Comment by mvilanova** [comment]
@keithherron we don't currently support renaming orgs at the moment, as renaming the org involves renaming the database schema where all the tables live (`dispatch_organization_default` for the default org) and that can lead to db issues. The only way is to create a new organization.

**Comment by mvilanova** [comment]
We could look into allowing folks to specify the org name during the installation process in the future.

**Comment by keithherron** [comment]
Thanks for the response!  FWIW since writing this I've had some success in renaming from default using essentially

db init
alter schema dispatch_organization_default RENAME to dispatch_organization_companyname
update dispatch_core.organization set slug='companyname' where id=1;
update dispatch_core.organization set name='companyname' where id=1;

Seems to work, although the instance is not yet hosting live data.  Is there a downside or gotcha to moving forward like that?

I also notice the instance still attempts to load /default instead of /companyname, although I haven't yet pinpointed why

**Comment by mvilanova** [comment]
> Is there a downside or gotcha to moving forward like that?
We haven't experimented enough with it to be able to tell with certainty.
