### ISSUE TITLE
Deleting existing user

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch#2672]
Hi Team, 
How to delete existing user / I have created user, but forgot password, how to reset if its local user
dont see delete api call as well in documentation.

**Comment by kevgliss** [comment]
We don't currently have a way to delete a user (see #2652), but to reset their password, you can issue the `dispatch user reset` command via the CLI.

**Comment by csetarun2** [comment]
sure, Thanks @kevgliss for you help

can you check and suggest on this issue https://github.com/Netflix/dispatch/issues/2622 once,
