### ISSUE TITLE
Okta integration blank page

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch#2692]
I have configured okta and when I browser disptach url its redirecting to my okta sso after entering details its showing blank page, any thoughts on this ?

I could able to integrate using above steps, when I open url its redirecting to okta , once I have enter credentials it logged in, but its showing blank page always

I have added below env varibales in my .env file

DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
DISPATCH_JWT_AUDIENCE=0oaxxxxxxxx
DISPATCH_PKCE_DONT_VERIFY_AT_HASH=true
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=https://trial-2372xxx.okta.com/oauth2/v1/keys
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce
VUE_APP_DISPATCH_OPEN_ID_CONNECT_URL=trial-237xxx.okta.com
VUE_APP_DISPATCH_CLIENT_ID=0oaxxxxxxx
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID=0oa2rprxxxxxxxxxxx
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL=https://trial-237xxxx.okta.com/
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_USE_ID_TOKEN=true
DISPATCH_UI_URL=http://34.68.139.77:8000/
DISPATCH_JWT_EMAIL_OVERRIDE=0oa2rprxxxxxx

![image](https://user-images.githubusercontent.com/21236859/201672174-096f8640-c638-4277-b5b7-dce4a89f73e7.png)
![image](https://user-images.githubusercontent.com/21236859/201672371-9927a319-1f29-4f98-9250-16e546d3164f.png)
![image](https://user-images.githubusercontent.com/21236859/201672388-23b93614-c2db-4838-8c1d-fd40dfb588f3.png)
![image](https://user-images.githubusercontent.com/21236859/201672402-f60925f4-0629-46d5-86cc-a65df965ca5a.png)
![image](https://user-images.githubusercontent.com/21236859/201672417-12f38ec6-37fd-4436-9fd5-0248dc1e1b26.png)

 ?
& where should we give permission to users since its not local users.
ex: [user1@company.com](mailto:user1@company.com) should get admin access to default project, [user2@company.com](mailto:user2@company.com) should get read access to default organization & project ? How can we achieve this

**Comment by kevgliss** [comment]
Regarding your server error. I would double-check your JWKS endpoint here: 
`DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=https://trial-2372xxx.okta.com/oauth2/v1/keys`

Judging by the documentation (https://developer.okta.com/docs/reference/api/oidc/#response-example) it should return JSON with valid `kid` (which is what our code assumes) there could be a configuration error or maybe the URL is just wrong.

Once a user logs in, they will have a user created for them with default permissions. If you wish to modify these permissions you can do so via the UI by navigating to Settings > Members and editing their member. 

To establish the "first admin" problem we typically recommend logging in and then elevating yourself to be admin via the cli command:
```
dispatch ❯ dispatch user update --help
Usage: dispatch user update [OPTIONS] EMAIL

  Updates a user's roles.

Options:
  -o, --organization TEXT         Organization to set role for.  [required]
  -r, --role [Owner|Manager|Admin|Member]
                                  Role to be assigned to the user.  [required]
  --help                          Show this message and exit.
  ```

**Comment by csetarun2** [comment]
@kevgliss I can able to get the key value, kid value was here
https://trial-2372159-admin.okta.com/oauth2/v1/keys
![image](https://user-images.githubusercontent.com/21236859/202430549-0a8b9629-b22f-499b-8cb8-b5802b9094b3.png)

**Comment by kevgliss** [comment]
Are you able to inspect the `authorization` header value being sent? Is should be a base64encoded string that has a 'kid' in there.

https://github.com/Netflix/dispatch/blob/master/src/dispatch/plugins/dispatch_core/plugin.py#L98

**Comment by csetarun2** [comment]
![image](https://user-images.githubusercontent.com/21236859/203349680-cf78a2a5-8b37-4061-9b9a-004228333977.png)

**Comment by csetarun2** [comment]
Thanks @kevgliss , I could able to integrate okta in dispatch , added steps in https://github.com/Netflix/dispatch/issues/1597
