### ISSUE TITLE
Unable to create executive report

### ISSUE THREAD

**Issue by dhananjaysathe** [Netflix/dispatch#2694]
**Describe the bug**
When i try slack slash command to file executive report it fails

**To Reproduce**

Setting up google :

Setup google account as detailed here  https://github.com/Netflix/dispatch/blob/master/docs/admin-guide/administration/plugins/configuring-g-suite.md - only for *Google Drive Plugin - Storage Management* (i enabled all apis, setup domain delegation etc , all of it as instructed)
Mapped 
- Developer Key => API key from (https://github.com/Netflix/dispatch/blob/master/docs/admin-guide/administration/plugins/configuring-g-suite.md#enable-required-apis-in-google-cloud-platform GOOGLE_DEVELOPER_KEY)
- Service Account { client email, client_id, privatekey, privatekey id, project_id} => from the *json* creds i got from google
- Unsure of what to do about *service account delegated account* i put it the same as client email 
- workspace domain was straight forward;
- Root Incident Storage FolderID => not sure what to do here -> i created a new folder on a shred google drive > made sure the "....iam.gserviceaccount.com" had the highest possible access -> then from the URL "https://drive.google.com/drive/u/0/folders/<some long string >" -> i coped this "long string" as folderid for the config

Setting up template and incident types:  

- for "default" incident type i created a new  created a  new "default" executive template -> with weblink "https://docs.google.com/document/d/1dab6k14p5ageo5B_d1YlB_zS9hMGHDMXy9RUbIZous4/edit" that i got from the examples;
NOTE : default here is just a name i chose , and also marked the incident type name "defaut" ->  default as required in the ui 

Creating incident and testing:

- from slack report a new incident
- go to dispatch channel 
- try /dispatch-report-executive 
- failure to create report 

Relevant Logs as follows: 
- 
`share_contact_card': 'EVERYONE'}}:/usr/local/lib/python3.9/site-packages/slack_sdk/web/async_internal_utils.py:_request_with_session:143
INFO:     10.146.0.18:64209 - "POST /default/events/slack/action HTTP/1.1" 200 OK
ERROR:'NoneType' object has no attribute 'name':/usr/local/lib/python3.9/site-packages/dispatch/decorators.py:wrapper:92
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 85, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/report/flows.py", line 119, in create_executive_report
    f"{executive_report.document.name} - {executive_report.document.weblink}\n"
AttributeError: 'NoneType' object has no attribute 'name'
ERROR:'NoneType' object has no attribute 'document':/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/decorators.py:wrapper:169
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/decorators.py", line 147, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/plugins/dispatch_slack/actions.py", line 491, in handle_executive_report_create
    f"The executive report document has been created and can be found in the incident storage here: {executive_report.document.weblink}",
AttributeError: 'NoneType' object has no attribute 'document'
`

**Expected behavior**
A google doc with report should have been created

**Release**
[v20220915](https://github.com/Netflix/dispatch/releases/tag/v20220915)

**Comment by mvilanova** [comment]
@dhananjaysathe did you map the executive report document template to the incident type(s)? Does the document for the executive report get created in the Google share folder you created?

**Comment by dhananjaysathe** [comment]
yes i did that as described in the bug report 
"""
Setting up template and incident types:

    for "default" incident type i created a new created a new "default" executive template -> with weblink "https://docs.google.com/document/d/1dab6k14p5ageo5B_d1YlB_zS9hMGHDMXy9RUbIZous4/edit" that i got from the examples;
    NOTE : default here is just a name i chose , and also marked the incident type name "defaut" -> default as required in the ui
"""

**Comment by mvilanova** [comment]
Does the document for the executive report get created in the Google share folder you created? The error tells me something is going wrong when the document is getting created.

**Comment by dhananjaysathe** [comment]
Hey @mvilanova thanks for your response.  sorry i wasnt clear earlier, folder/files are NOT created :(

**Comment by mvilanova** [comment]
That's what I was afraid of. Make sure the settings in your `Google Drive Plugin - Storage Management` and `Google Docs Plugin - Document Management` are correct.

**Comment by dhananjaysathe** [comment]
Hello @mvilanova i added the configuration for document too , no dice
I have the following enabled now 

Slack Plugin - Conversation Management	
Slack Plugin - Contact Information Resolver	
Google Drive Plugin - Storage Management
Dispatch Plugin - Ticket Management	
Dispatch Plugin - Participant Resolver	
Google Docs Plugin - Document Management
Dispatch Plugin - Basic Authentication Provider

**Comment by dhananjaysathe** [comment]
also enabled document resolver, not sure that that does

**Comment by mvilanova** [comment]
Please review that the configuration settings for the Google related plugins are correct. That's likely the issue. If you see any other errors feel free to share them here.

**Comment by dhananjaysathe** [comment]
Here is roughlt visually repeting what i set as configuration , may be easier to follow
https://ibb.co/vk44S72

**Comment by dhananjaysathe** [comment]
i pasted the entire contents of private key including /n etc from the json i got from google

**Comment by mvilanova** [comment]
Config looks ok. The plugins are enabled correct? The checkbox in the screenshot is not checked.

**Comment by mvilanova** [comment]
If the plugins are enabled and properly configured a document should be created off of the template defined. Make sure that the account Google account you're using has permissions to access the template.

**Comment by mvilanova** [comment]
@dhananjaysathe were you able to resolve the issue? If so, feel free to close it.

**Comment by dhananjaysathe** [comment]
Nope no luck 😞
