### ISSUE TITLE
Issue with new release cant able to build core image symlinks error

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch#2706]
Im trying to build new release disptach application, when I execute the ./install.sh Im getting below error, I have tried 2 different server where I build dispatch app successfully with prev version..

(Vm1)
![image](https://user-images.githubusercontent.com/21236859/202231072-e5ff9f26-ed4a-4d4c-b15a-e1eb77b7f2ea.png)

VM2: 
Creating volumes for persistent storage...
Created dispatch-postgres.

Generating SECRET_KEY...
SECRET_KEY written to ./.env
Generating DISPATCH_JWT_SECRET...
DISPATCH_JWT_SECRET written to ./.env

Pulling, building, and tagging Docker images...

Pulling postgres ... done
postgres uses an image, skipping
web uses an image, skipping
scheduler uses an image, skipping
Building core
ERROR: Cannot locate specified Dockerfile: Dockerfile
Cleaning up...

can you please check once

**Comment by csetarun2** [comment]
I have downloaded the release source code, there Dockerfile was missing (no docker folder)
![image](https://user-images.githubusercontent.com/21236859/202236756-23fe11fa-955e-471a-baad-875754c99d0c.png)

can you please check once @mvilanova @kevgliss

**Comment by kevgliss** [comment]
This was fixed in #2697. Depending on your use case for docker you can either use the new Dockerfile that was included in that release (now under .devcontainer) or pull the latest version from `master` that includes the fix from #2697. We will likely deprecate the docker folder at some point in favor .devcontainer but reverted the change because we had not yet update the documentation.

**Comment by manireddyk** [comment]
Thanks @kevgliss , but how should I build the image now, can you share the steps, 
currently as per documentation Im following these steps
step1: git clone https://github.com/Netflix/dispatch-docker.git
step2: ./install.sh
Then getting above issue, Please correct me If Im wrong, How to properly clone/run the code ?

**Comment by csetarun2** [comment]
Thanks @kevgliss , but how should I build the image now, can you share the steps, 
currently as per documentation Im following these steps
step1: git clone https://github.com/Netflix/dispatch-docker.git
step2: ./install.sh
Then getting above issue, Please correct me If Im wrong, How to properly clone/run the code ?

**Comment by csetarun2** [comment]
Thanks @kevgliss for your help :)
