### ISSUE TITLE
Issue with new version image database

### ISSUE THREAD

**Issue by manireddyk** [Netflix/dispatch#2708]
I have manually cloned and build the dispatch image, and pushed the code repo, 
while Im trying to use the image, UI is loading when I click on cases/incidents looks all my prev incidents created by prev version container were not showing, When I read the logs, 
![image](https://user-images.githubusercontent.com/46611593/202258752-f0ccf91c-aa70-4986-beff-affce1a0ab4d.png)

Now I have reverted it back version, and created container from it, now its showing all the previous data,
can you  @mvilanova @kevgliss please  check any issue with new release db call code

**Comment by kevgliss** [comment]
Have you updated your database revision by issuing `dispatch database upgrade` with the new code checked out?

**Comment by manireddyk** [comment]
oh I havent run this step , Thanks you so much for your quick response @kevgliss , 
is there any places where you can add  all these points, will be helpful for others

**Comment by manireddyk** [comment]
Thanks @kevgliss 

I have upgraded and tried with new version, its not working as expected, How can I revert it back schema as well ? 
might be this step is required in the documenting, if they want to revert it back the schema 

I have logged into the old dispatch-docker container and ran the dispatch database downgrade, not working
![image](https://user-images.githubusercontent.com/46611593/202428260-2ba00b64-129b-4950-991a-d740a76f8887.png)

can you please help on this

**Comment by manireddyk** [comment]
I got the below error after I upgrade the schema
1. I can able to create incidents in default organization but its not sending the slack notifications
![image](https://user-images.githubusercontent.com/46611593/202429285-79da2a37-5c5a-42a8-a1db-9eda2613eaba.png)

2. If I try to switch diff org, while trying to create incident its not even creating
![image](https://user-images.githubusercontent.com/46611593/202429543-344694b6-7f01-4b39-aaed-f3a922d62ce4.png)
 
thats y would like to revert it back, can you please share the db schema revert steps/how to revert with older version
