### ISSUE TITLE
Unexpected behavior of the system when creating an incident

### ISSUE THREAD

**Issue by romanskugarevLMRU** [Netflix/dispatch#2717]
**Describe the bug**
Hello, there may be a bug, maybe something could not be done or deployed correctly.
When we use form http://dispatch.***/default/incidents/report we have 2 problems:

1. Every time we click on the Submit button, a new task is created. No info about task created, and we can create 2 and more task as user with similar data
![image](https://user-images.githubusercontent.com/117632465/203495200-adccf43e-ac1e-4fb6-af82-b6bb88be6ecb.png)
![image](https://user-images.githubusercontent.com/117632465/203495447-1773bdb0-e1ce-46e3-b54d-8f6429344ed1.png)
2. After creation by form, no task id and we can't add resourses and other data, if we create from form in system, by button New

**To Reproduce**
1. Go to 'http://dispatch.***/default/incidents/repor'
2. Click on 'Submit'
3. Also click on 'Submit'
4. Create 2 task without id

**Expected behavior**
Clear info in form, and reference on form http://***/default/incidents/status or success message

**Comment by kevgliss** [comment]
When you click submit are you not getting any feedback at all? Could you let me know if there are any console errors when you click submit?

**Comment by romanskugarevLMRU** [comment]
![image](https://user-images.githubusercontent.com/117632465/204456680-636f2854-8b79-4e1f-919f-16103a2ff72b.png)
but incident create
xhr.js:187          POST http://dispatch.obs.lmru.tech/api/v1/default/incidents 500 (Internal Server Error)

**Comment by mvilanova** [comment]
@romanskugarevLMRU any server side errors you can share? Did you create the tags beforehand in http://dispatch.obs.lmru.tech/api/v1/default/settings/projects/tags?project=<YOUR_PROJECT> or manually typed them in the intake form?
