### ISSUE TITLE
side bar coming down

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch#2718]
in the new release options are coming downside,

**Comment by csetarun2** [comment]
![image](https://user-images.githubusercontent.com/21236859/203541097-e7551b73-983b-4ede-ab7f-53e803b21027.png)

**Comment by kevgliss** [comment]
Are you using Firefox? I have noticed this behavior there, but not in chrome. Will take a look.

**Comment by csetarun2** [comment]
no @kevgliss , I have also used chrome
![image](https://user-images.githubusercontent.com/21236859/204577412-07e8912d-7f9a-4e1b-bc07-b578918a516e.png)

**Comment by manireddyk** [comment]
Thank you @mvilanova for fixing this in new release, please close this ticket :)

**Comment by kevgliss** [comment]
Closed by #2777
