### ISSUE TITLE
plugins are not loading

### ISSUE THREAD

**Issue by manireddyk** [Netflix/dispatch#2754]
Hi @kevgliss @mvilanova 
I have just created dispatch using new version, I have observed plugins are not loading, can you please check once :) 

<img width="743" alt="image" src="https://user-images.githubusercontent.com/46611593/206489063-b0da3e72-693c-494e-9658-86bf7b1ec5c8.png">
in the UI also when I try to add new plungins its showing empty .

**Comment by mvilanova** [comment]
Did you grant yourself admin or higher permissions to configure your project? Looks like plugins are loading, but are not yet enabled.

**Comment by manireddyk** [comment]
Thanks @mvilanova , its working fine
