### ISSUE TITLE
issue with while enabling slack plugins

### ISSUE THREAD

**Issue by manireddyk** [Netflix/dispatch#2773]
@kevgliss  @mvilanova 
I couldn't be able to save the plugin after entering the details, it showed str type expected, even though I provided details

<img width="530" alt="slack_strtype" src="https://user-images.githubusercontent.com/46611593/207925923-274659b7-458f-4345-8df4-263e42ebe2fe.png">

**Comment by mvilanova** [comment]
Looking at the screenshot, looks like you didn't populate the Socket Mode field. You can add a random string there if you're not planning to use Socket Mode to let the check pass and allow you to save.

**Comment by manireddyk** [comment]
Thanks @mvilanova for replying, 
I tried to pass both real socketmode token and also tried with random text, even thought its still showing same error, even I try to pass all other fields with random once, same issue

<img width="265" alt="image" src="https://user-images.githubusercontent.com/46611593/207927880-53f1a369-ae5a-4484-8622-b95dbbabcfb7.png">

**Comment by kevgliss** [comment]
The socket mode config item should be [optional](https://github.com/Netflix/dispatch/blob/master/src/dispatch/plugins/dispatch_slack/config.py#L12). If you open the console and look at the response from the server it should give you more detail about what field is actually missing.
