### ISSUE TITLE
request for info: openness to changes to accommodate for somewhat different workflow

### ISSUE THREAD

**Issue by rachten** [Netflix/dispatch#283]
Hey guys,

First off, thanks for open-sourcing Dispatch!

At my company we're increasing the level of automation in our incident management process. Dispatch is being considered as one of the candidates to support this. To better understand its current feature-set and its viability in our context, we got it up-and-running using most of the currently mandatory plugins (merely disabled Zoom) and played around with it. To make it fit our workflow, we would need to be able to customize certain things and add others (aside from having to create an alternative to the G Suite plugin as we're not using that).

I would like to better understand to what extent the following changes would be considered welcome ones:

* Allow for customization of Jira plugin. Current plugin contains some seemingly Netflix-specific things such as some custom fields, priority mapping, etc. These things should be customizable. Besides, I guess it would be good to leverage the create metadata that Jira exposes.
* Allow for customization of (Slack) messages. Guess it would be good to use a (potentially logic-less) template engine for the messages and extract them from the Python code. That should make customization easier as well.
* In our workflow we also create an incident-specific Slack channel for collaboration purposes. However, we also announce incident status changes in a dedicated shared Slack channel. Thus such functionality we'd like to add.
* Make conference plugin optional; guess this is already covered by https://github.com/Netflix/dispatch/issues/55.
* Allow for adding custom key-value pairs as metadata to an incident that is stored in the DB and exposed via the API. We would like to e.g. keep track of what customers are involved, status around communication towards those customers, preliminary root cause. Other users might have other needs, so being able to add custom key-value pairs would facilitate this. Potentially this is what the `tags` or `terms` are intended for, but I kind of fail to understand the idea behind both data types (as well as the `definition` one btw).
* Allow for customization of incident participant roles. We would like to e.g. include SME as a dedicated role while at the same time being able to fill in the subject while assigning the role (e.g "SME - some specific subject" as a particpant role, or possibly another partipant attribute). Aside from that, we don't distinguish a separate scribe and liaison at this moment.

Other potentially interesting changes:

* Propagation of incident-specific events (whatever source) to timeline as part of investigation documents. I was wondering if that's something you are already considering any way?
* Include timeline in incident status update notifications. Our incident commanders currently manually keep track of the incident timeline which is obviously something we'd like (partially) automate. Besides, we do inckude a high-level timeline in each of our status update. Dispatch captures all events related to an incident which is nice but a bit too much information for the high-level timeline we normally share. Perhaps it would be possible to somehow 'tag' the events to share in such status updates?
* Allow manual creation of incidents from Slack. Ah I see that's already covered by https://github.com/Netflix/dispatch/issues/180.
* Include comments in Jira ticket as part of the events? This would obviously increase complexity as it requires a Jira webhook to be installed.
* Leverage Home tab in Slack to show list of currently ongoing and recently closed incidents, including links to some of their important resources (e.g. conversation weblink, ticket weblink, etc.). That should be relatively straight-forward and remove the need for people to use the Dispatch UI.

Could you please comment on the above?

Thanks in advance!

**Comment by kevgliss** [comment]
Hi @rachten see the response below... Let me know if I missed anything!

> Allow for customization of Jira plugin. Current plugin contains some seemingly Netflix-specific things such as some custom fields, priority mapping, etc. These things should be customizable. Besides, I guess it would be good to leverage the create metadata that Jira exposes.
Allow for customization of (Slack) messages. Guess it would be good to use a (potentially logic-less) template engine for the messages and extract them from the Python code. That should make customization easier as well.

Agreed, the current Jira plugin contains too many netflixism. Making it generic would be welcome (and is in our backlog). Additionally, if you _do_ have any logic specific do your install of jira that can't be made generic, one option is to simply create your _own_ jira plugin in another repository (not in the core dispatch repository) and install it alongside the other plugins. We do this for several internal tools that are publically available. 

> In our workflow we also create an incident-specific Slack channel for collaboration purposes. However, we also announce incident status changes in a dedicated shared Slack channel. Thus such functionality we'd like to add.

This exists today, we update things like status change, priority change, type change and command change. We also do a daily rollup of all active or stable incidents to this dedicated notification channel. See [here](https://hawkins.gitbook.io/dispatch/configuration/app#incident_notification_conversations-default).

> Make conference plugin optional; guess this is already covered by #55.

Yes, the current plan is to make all plugins optional, we've started down that path but it will take us a while to decouple them all. 

> Allow for adding custom key-value pairs as metadata to an incident that is stored in the DB and exposed via the API. We would like to e.g. keep track of what customers are involved, status around communication towards those customers, preliminary root cause. Other users might have other needs, so being able to add custom key-value pairs would facilitate this. Potentially this is what the tags or terms are intended for, but I kind of fail to understand the idea behind both data types (as well as the definition one btw).

We use tags as pseudo foreign keys into other systems (e.g. application names synced from our application deployment system). But they could be extended to do whatever you'd like. Another nice feature of Tags is that we do some "auto-tagging" where we attempt to extract tags from things like associated documents and string values using some basic NLP. 

The main difference between tags and terms (at least for us) is that tags represent real assets, where terms are solving a more specific use case of trying to disambiguate internal acronyms and their definitions (we struggle with lots of terminology and jargon that we use for terms).

> Allow for customization of incident participant roles. We would like to e.g. include SME as a dedicated role while at the same time being able to fill in the subject while assigning the role (e.g "SME - some specific subject" as a participant role, or possibly another participant attribute). Aside from that, we don't distinguish a separate scribe and liaison at this moment.

This not yet something we expose at the moment, I'm unsure how difficult that may be, @mvilanova could you comment on this one?

> Propagation of incident-specific events (whatever source) to timeline as part of investigation documents. I was wondering if that's something you are already considering any way?
Include a timeline in incident status update notifications. Our incident commanders currently manually keep track of the incident timeline which is obviously something we'd like (partially) automate. Besides, we do inckude a high-level timeline in each of our status update. Dispatch captures all events related to an incident which is nice but a bit too much information for the high-level timeline we normally share. Perhaps it would be possible to somehow 'tag' the events to share in such status updates?

We're currently building out timeline features at the moment I believe @mvilanova just landed some PRs that might be of some interest, #228 #282 #262 #212 . We also struggle to build timelines manually as well, we added (#212) that allows us to simply react to a message in slack and have it added to the timeline, super useful!

> Allow manual creation of incidents from Slack. Ah I see that's already covered by #180.

Yes, we'd like to get this functionality implemented soon.

> Include comments in Jira ticket as part of the events? This would obviously increase complexity as it requires a Jira webhook to be installed.

In general, we tried to keep jira mostly as data sync, that being said we do allow plugins to advertise their own endpoints (in the case of a hook) so this could be added to the jira plugin. See: [here](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_slack/plugin.py#L80)

> Leverage Home tab in Slack to show list of currently ongoing and recently closed incidents, including links to some of their important resources (e.g. conversation weblink, ticket weblink, etc.). That should be relatively straight-forward and remove the need for people to use the Dispatch UI.

I believe this is a relatively new feature to Slack, that we haven't explored. I don't think we would prioritize this internally but would be open to contributions here. In general, the vast majority of participants never need to use the Dispatch UI (typically only responders and powerusers), everyone else should be able to get by with Slack.

**Comment by mvilanova** [comment]
Hey @rachten, thanks for considering Dispatch! Answers inline below:

> Allow for customization of (Slack) messages. Guess it would be good to use a (potentially logic-less) template engine for the messages and extract them from the Python code. That should make customization easier as well.
Agree, but not a priority for us at the moment. If you have spare cycles and want to send a PR, we will be happy to take a look at it. Out of curiosity, what would you change about the current messages?

> Allow for customization of incident participant roles. We would like to e.g. include SME as a dedicated role while at the same time being able to fill in the subject while assigning the role (e.g "SME - some specific subject" as a particpant role, or possibly another partipant attribute). Aside from that, we don't distinguish a separate scribe and liaison at this moment.
It's doable, but it would require a considerable amount of refactoring. Would "some specific subject" be used to help others understand how that SME can help during the incident? In order to provide context to other participants, we include the team the participant belongs to when we announce the participant in the incident channel or when users run `/dispatch-list-participants`.

> Propagation of incident-specific events (whatever source) to timeline as part of investigation documents. I was wondering if that's something you are already considering any way?
Yes, check out the PRs that Kevin mentioned. I'm also planning to include the timeline in the incident active status page and a link to it in the investigation document. If you have ideas on how to make it better, let me know!

> Include a timeline in incident status update notifications. Our incident commanders currently manually keep track of the incident timeline which is obviously something we'd like (partially) automate. Besides, we do inckude a high-level timeline in each of our status update. Dispatch captures all events related to an incident which is nice but a bit too much information for the high-level timeline we normally share. Perhaps it would be possible to somehow 'tag' the events to share in such status updates?
Yes, some of the events generated by Dispatch or its plugins included in the timeline may not be relevant to some of the stakeholders participating in the incident, but we wanted to include all of them in the first version to see how people would feel about it and then iterate on it. Being able to provide a high-level timeline is a good idea and something we have in mind.

> Allow manual creation of incidents from Slack. Ah I see that's already covered by #180.

Yes, easy and well-documented in #180 . We will give the contributor a few more weeks before doing it ourselves.

**Comment by rachten** [comment]
Thanks for the quick and elaborate responses, @kevgliss and @mvilanova! Good to hear that you’re mostly open to such changes. I’ll add a more in-depth reply when back in the virtual office :)

**Comment by rachten** [comment]
Again, thnx for your feedback. Very helpful! I went through things in a bit more detail. Please find some comments (including a few remaining questions):

**Regarding incident notification conversations**

> This exists today, we update things like status change, priority change, type change and command change. We also do a daily rollup of all active or stable incidents to this dedicated notification channel. See here.

Cool, missed that. Will play around with it to see if that suits our needs.

**Regarding adding metadata to an incident**

> We use tags as pseudo foreign keys into other systems (e.g. application names synced from our application deployment system). But they could be extended to do whatever you'd like. Another nice feature of Tags is that we do some "auto-tagging" where we attempt to extract tags from things like associated documents and string values using some basic NLP.

> The main difference between tags and terms (at least for us) is that tags represent real assets, where terms are solving a more specific use case of trying to disambiguate internal acronyms and their definitions (we struggle with lots of terminology and jargon that we use for terms).

I guess neither Tags nor Terms seem fit for purpose then (or I yet fail to understand them :))? We'd like to add information related to e.g. what customers are impacted, status of communication both internally and towards these customers, etc. Adding a `metadata` field (e.g. using JSON datatype, as was done recently to add the `details` field to the Event model) to the Incident model would suffice here?

**Regarding integration of events coming from Jira**

> In general, we tried to keep jira mostly as data sync, that being said we do allow plugins to advertise their own endpoints (in the case of a hook) so this could be added to the jira plugin. See: here

Nice, that might indeed come in handy.

**Regarding customization of (Slack) messages**

> Agree, but not a priority for us at the moment. If you have spare cycles and want to send a PR, we will be happy to take a look at it. Out of curiosity, what would you change about the current messages?

For example, the current FAQ document description refers to an "information security incident" whereas we would be using it for incident management in general. Mostly, we just have our own templates around incident communication that we would like to continue using.

**Regarding adding metadata to a participant**

>  It's doable, but it would require a considerable amount of refactoring. Would "some specific subject" be used to help others understand how that SME can help during the incident? In order to provide context to other participants, we include the team the participant belongs to when we announce the participant in the incident channel or when users run /dispatch-list-participants.

I guess using the team a participant belongs to could partially solve the problem, but that would imply we need to manage teams using Dispatch. I'm not sure if we'd like to manage teams in Dispatch as that would be rather redundant and ideally something we'd like to avoid. Besides, in our case some teams might be responsible for more than one service.

Could you elaborate on why you think it would require a considerable amount of refactoring? Perhaps we have different things in mind; from my perspective, allowing to add metadata to a participant using a set of key-value pairs could be sufficient.

**Regarding inclusion of timeline in status updates / extracting a high-level timeline**

> We also struggle to build timelines manually as well, we added (#212) that allows us to simply react to a message in slack and have it added to the timeline, super useful!

Yes, that's definitely very useful! Something that's on our current wishlist. In a simple demo slack app I've added this functionality as a message shortcut. Adding / removing a reaction is more lightweight, so good idea.

Related to this; what's the idea with messages in Slack that contain a file (screenshot / log file / etc)? I assume you'd like to upload them to the appropriate directory in the Google drive. How are you planning to add them to the timeline though?_ The current Event model does not seem to allow for adding this kind of information per se (albeit a URL to the file could obviously be included in the `details`).

> Yes, some of the events generated by Dispatch or its plugins included in the timeline may not be relevant to some of the stakeholders participating in the incident, but we wanted to include all of them in the first version to see how people would feel about it and then iterate on it. Being able to provide a high-level timeline is a good idea and something we have in mind.

An idea is to imply that all manually added events (those added by adding the stopwatch reaction to a message) can be considered events that should by-default be included in the high-level timeline to share with incident stakeholders. The IC (or other participant responsible for communications) could manually tag / untag other events in the timeline either through the Dispatch UI or by means of a new Slack interaction.

**Other**

* I saw the Slack plugin already allows for distinction between creating a private or public channel, however the core dispatch code does not. Our incident conversations are public by-default. Would adding a configuration option to switch between the two be a welcome change? (alternatively, the visibility could relate to the visibility of the incident as currently also supported by Dispatch).
* The above brings me to another question; given our incident conversations are public, people that can't really be considered participants also join (e.g. to observe). The current Slack plugin automatically assumes that all members that join a channel are considered participants. Would you be open to make that configurable? If the auto-adding-participant feature is disabled, we could e.g. present all members that join a channel an interactive ephemeral message that they could make use of only if they're actively participating.

**Comment by kevgliss** [comment]
> I guess neither Tags nor Terms seem fit for purpose then (or I yet fail to understand them :))? We'd like to add information related to e.g. what customers are impacted, status of communication both internally and towards these customers, etc. Adding a metadata field (e.g. using JSON datatype, as was done recently to add the details field to the Event model) to the Incident model would suffice here?

I don't have a strong opinion against adding such a column, how do you envision we would get that data into and out of Dispatch though? Some type of enrichment plugin?

> For example, the current FAQ document description refers to an "information security incident" whereas we would be using it for incident management in general. Mostly, we just have our own templates around incident communication that we would like to continue using.

It makes sense that you would want to change these strings, generally speaking, most of the strings are decoupled nicely from the actual code base and could be modifed to be set as configuration variables. See: [here](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/messaging.py#L130)

I think if there are only a few modifications here and there these can be exposed easily enough (with some sane defaults). However, if the ask is to expose _all_ strings/templates that is a larger undertaking. 

> I guess using the team a participant belongs to could partially solve the problem, but that would imply we need to manage teams using Dispatch. I'm not sure if we'd like to manage teams in Dispatch as that would be rather redundant and ideally something we'd like to avoid. Besides, in our case some teams might be responsible for more than one service.

> Could you elaborate on why you think it would require a considerable amount of refactoring? Perhaps we have different things in mind; from my perspective, allowing to add metadata to a participant using a set of key-value pairs could be sufficient.

By default, dispatch pulls team information from slack itself (many organizations populate this data into slack). If that's not the case you can write a `ContactPlugin` to pull employee information wherever you store that information from. This is what we do because our internal whitepages has more information than what we populate into slack. 

I think to extend that plugin with additional ownership information (jdoe, owner: App1, App2) would be a reasonable way to handling it.

> what's the idea with messages in Slack that contain a file (screenshot / log file / etc)? I assume you'd like to upload them to the appropriate directory in the Google drive. How are you planning to add them to the timeline though?_ The current Event model does not seem to allow for adding this kind of information per se (albeit a URL to the file could obviously be included in the details).

We don't do this today but should be pretty easy to add (we are already gathering all messages we just don't save off the attachment data. I don't think we've often had a need to include screenshots or images in our timelines (they are typically higher level). But could be useful for others. The hard part with hosting an actual image would be the server would have to access and serve the image which isn't really something that Dispatch was set up to do. 

> An idea is to imply that all manually added events (those added by adding the stopwatch reaction to a message) can be considered events that should by-default be included in the high-level timeline to share with incident stakeholders. The IC (or other participant responsible for communications) could manually tag / untag other events in the timeline either through the Dispatch UI or by means of a new Slack interaction.

This seems reasonable, we do plan to add timeline filtering by source/type/keyword so perhaps once that's implemented the default is to suppress the `system` events by default.

> I saw the Slack plugin already allows for distinction between creating a private or public channel, however the core dispatch code does not. Our incident conversations are public by-default. Would adding a configuration option to switch between the two be a welcome change? (alternatively, the visibility could relate to the visibility of the incident as currently also supported by Dispatch).

Today we just have `Open` (private channel, but with notifications) and `Restricted` (private channel only). Maybe something like `Open` (public channel w/notifications), `Secure` (private channel w/notifications), and `Restricted` (private channel, w/o notifications) makes sense. cc @mvilanova 

> The above brings me to another question; given our incident conversations are public, people that can't really be considered participants also join (e.g. to observe). The current Slack plugin automatically assumes that all members that join a channel are considered participants. Would you be open to make that configurable? If the auto-adding-participant feature is disabled, we could e.g. present all members that join a channel an interactive ephemeral message that they could make use of only if they're actively participating.

I think we would be open to making this configurable, for us it's interesting to see the actual number of "participants" or folks at least tangentially involved and work backward from there to determine the actual number of "active" participants. Today, we mainly use this to give us an estimate of the total cost of an incident. The theory there being that even if folks are being made aware of an issue, it still distracts them (even if in a small way) from other work and is an opportunity cost. As we mature that estimate we plan to take into account and refine what "active" means (slack messages, comments, attending meeting syncs, etc.) cc @mvilanova

**Comment by mvilanova** [comment]
> Could you elaborate on why you think it would require a considerable amount of refactoring? Perhaps we have different things in mind; from my perspective, allowing to add metadata to a participant using a set of key-value pairs could be sufficient.

I may have misinterpreted your ask. If all you want is to be able to add different types of roles and be able to customize them a little bit by adding metadata, then I don't think it would be too much work. We could expose that in the Web UI and make the roles that we already have to be required, so we don't have to make a lot of code changes. Dispatch relies on the `Incident Commander` and `Reporter` roles when the incident is created, and `Participant` when new participants are getting added to the incident. Then you can assign them your roles using the `/dispatch-assign-role` command.

> what's the idea with messages in Slack that contain a file (screenshot / log file / etc)? I assume you'd like to upload them to the appropriate directory in the Google drive. How are you planning to add them to the timeline though?_ The current Event model does not seem to allow for adding this kind of information per se (albeit a URL to the file could obviously be included in the details).

Yes, we would like to do it in the future. We have some code already in the Slack plugin to enable this (https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_slack/views.py#L170, https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_slack/views.py#L532), but we haven't prioritized it. In terms of adding it to the timeline, we could create an event when a new file is shared that would include the name of the person and a link to it in the storage drive in the details column like you mentioned. Something like: "Marc Vilanova shared a new file called X in the conversation".

> I saw the Slack plugin already allows for distinction between creating a private or public channel, however the core dispatch code does not. Our incident conversations are public by-default. Would adding a configuration option to switch between the two be a welcome change? (alternatively, the visibility could relate to the visibility of the incident as currently also supported by Dispatch).

Yeah, I think it would be a good addition and pair well with incident visibility. We could follow the different levels of data classification, for example, described [here](https://www.cmu.edu/iso/governance/guidelines/data-protection/approach.html) (Public, Private, and Restricted).

**Comment by rachten** [comment]
Thanks again for your elaborate responses! I'll leave this ticket open for a little while in case there's more comments from your side. From our side, things are clear enough and thus this ticket can be closed; there don't seem to be any major roadblocks to make Dispatch fit our incident management workflow.

> I don't have a strong opinion against adding such a column, how do you envision we would get that data into and out of Dispatch though? Some type of enrichment plugin?

I guess being able to provide this metadata upon creation of an incident could just work (i.e. extend the API to optionally allow for one or more key-value pairs and extend the web ui and the Slack plugin accordingly)? Anyway, we can discuss in more detail in due time :)

> I think if there are only a few modifications here and there these can be exposed easily enough (with some sane defaults). However, if the ask is to expose all strings/templates that is a larger undertaking.

No idea at this moment, but this could be implemented in a pragmatic way. Obviously, if we choose for Dispatch, we will invest and contribute.

> I think to extend that plugin with additional ownership information (jdoe, owner: App1, App2) would be a reasonable way to handling it.

I missed the idea behind this plugin thus far. Will experiment a little with it, sounds like a reasonable way indeed. Thanks!

> Dispatch relies on the Incident Commander and Reporter roles when the incident is created, and Participant when new participants are getting added to the incident. Then you can assign them your roles using the /dispatch-assign-role command.

That could work I guess!
