### ISSUE TITLE
sqla: scoped_session not removed from registry - memory leak?

### ISSUE THREAD

**Issue by liamvdv** [Netflix/dispatch#2867]
**Describe the bug**
Hey dispatch maintainers,
as far as I can tell you are using sqla scoped_session to obtain a new session for every web request as per described [here](https://github.com/tiangolo/fastapi/issues/726#issuecomment-917766454). You  [call .close() session](https://github.com/Netflix/dispatch/blob/6d8ed41fc71e9efde1488e626bc4faacdc4b5f5d/src/dispatch/main.py#L146) to release session attached objects. Yet, as per defined in the [sqla docs](https://docs.sqlalchemy.org/en/13/orm/contextual.html#using-thread-local-scope-with-web-applications) you must call session.remove() to actually remove the session from the registry. 
I think references in threading.local() will prevent the session from being garbage collected as non-scoped sessions would and thus this is a memory leak, see [thread-local sqla docs](https://docs.sqlalchemy.org/en/13/orm/contextual.html#thread-local-scope).

I'm not 100% sure this is the behaviour and don't have the capacity to check myself, but I rather ask you to investigate than keep quit and let a leak grow.
Have a nice day ^^

**To Reproduce**
...

**Expected behavior**
...

**Screenshots**
...

**Desktop (please complete the following information):**
 Server

**Smartphone (please complete the following information):**
...

**Additional context**
...

**Comment by mvilanova** [comment]
Hi @liamvdv , thanks for sharing your concern. We will look into it and circle back.

**Comment by kevgliss** [comment]
Hi @liamvdv, we are following the prescribed method in the fastapi documentation here:
https://fastapi.tiangolo.com/tutorial/sql-databases/#create-a-dependency

We haven't encountered any memory-related issues thus far (or at least they aren't very noticeable). I'm also unsure if it could be an issue with legacy documentation. The following doesn't even mention `remove()`:
https://docs.sqlalchemy.org/en/20/orm/session_basics.html#closing

**Comment by liamvdv** [comment]
Alright :) Thanks for looking into it anyway👍🏻
