### ISSUE TITLE
Search API call is failing with 'field required' message

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#2914]
In order to search an incident with specific string, I am calling the search API via following curl command:

`curl   -H "Content-Type: application/json"   -H "Authorization: Bearer $DISPATCH_API_TOKEN" "https://dispatch.xyz.com/api/v1/default/search?type=Incident&itemsPerPage=10&page=1&q='xyz string'"`

But it is failing with `"msg":"field required" `

I tried with required parameters only as well, but same error is showing up. e.g.
```
search?type=Incident&q='xyz string'
search?type=Incident&q='string'
```

Can you please help with the right search API call.

**Comment by vikassinha2019** [comment]
Hi @kevgliss,
Can you please have a look into this issue when you get a chance.
Thanks!

**Comment by kevgliss** [comment]
If you take a look at the swagger docs (they are generated dynamically at /api/v1/docs on your deployment), `type` should be `type[]`.
![Screenshot 2023-02-01 at 9 21 10 AM](https://user-images.githubusercontent.com/2262214/216116510-54e232ed-f04e-47ca-b1b8-286d5da2d2fa.png)


As an example
```
http://localhost:8080/api/v1/default/search?q=test&type[]=Document&type[]=Incident&type[]=Tag&type[]=Task&type[]=Source&type[]=Query
```
