### ISSUE TITLE
tag filtering is broken in the latest version (v20230201)

### ISSUE THREAD

**Issue by vindex10** [Netflix/dispatch#2978]
**Describe the bug**
Tags filtering doesnt find any tags, though API returns the tag of interest.

**To Reproduce**
1. Go to Incidents
2. Click on New
3. Scroll down to Tags
4. Enter some tag name to search for
5. See empty dropdown

**Expected behavior**
I want to see the tag :)

**Desktop (please complete the following information):**
 - OS: linux, ubuntu
 - Browser firefox
 - Version 109.0.1

**Additional context**
The error in the console:

```
TypeError: a.item.project is undefined
    fn http://dispatch-dev.mnv:8000/assets/TagFilterAutoComplete.89e24ed2.js:1
```

And indeed, the tag in the response doesn't have "project" field:
```
{"items":[{"id":14,"name":"some_tag","source":"dispatch","uri":null,"discoverable":true,"description":"Generic tag","tag_type":{"id":3,"name":"some_type","exclusive":false,"description":"some desc"}}],"total":1}
```

This route:
https://github.com/Netflix/dispatch/blob/3485c7c1505a7976bbd6ff9b2696a1b2ffd5221f/src/dispatch/tag/views.py#L23

Queries Tags object:
https://github.com/Netflix/dispatch/blob/3485c7c1505a7976bbd6ff9b2696a1b2ffd5221f/src/dispatch/tag/models.py#L15

Which has the ProjectMixin:
https://github.com/Netflix/dispatch/blob/3485c7c1505a7976bbd6ff9b2696a1b2ffd5221f/src/dispatch/models.py#L24

And `project` is not loaded, as well as timestamp fields.

 Timestamp and Project define fields through inheritance, maybe this is the reason? I checked, the version of Pydantic is latest, while sqlalchemy is 1.3, while latest minor stable is 1.4 and they issued 2.0. But this might not help..

**Comment by kevgliss** [comment]
Hi @vindex10 I believe this is already fixed on master, would you be able to pull it down and confirm? We had some bug fixes after the last release and probably need to tag another release with those fixes.

**Comment by kevgliss** [comment]
I've created a new release with those fixes (v20230213).

**Comment by vindex10** [comment]
Thank you, @kevgliss . I tried on the current master: 3485c7c1505a7976bbd6ff9b2696a1b2ffd5221f

It worked!
