### ISSUE TITLE
Docs for the dashboard UI URL location

### ISSUE THREAD

**Issue by darrenhaken** [Netflix/dispatch#312]
I've started trying out Dispatch locally and kicking the tyres. I struggled to find the dashboard, the root URL takes you to the incident report.

I have managed to find its at `/dashboard` by looking in the source code.
It would be good if this could be signposted in the docs.

**Comment by kevgliss** [comment]
I've adjusted the default landing page to be the dashboard instead of the incident report page. See: #313

**Comment by darrenhaken** [comment]
That's great thanks!
