### ISSUE TITLE
dispatch app not working properly after bulk individual contact upload 

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch#3158]
after adding bulk individual contacts in db, (I did using psql import csv file).
dispatch application stopping after sometime, and starting after sometime, in the error log I found this error, any idea ?
 default cost type for response cost does not exist 

<img width="579" alt="image" src="https://user-images.githubusercontent.com/21236859/227612012-5f3fd8a2-0491-4aa7-8106-d004e30754e4.png">

**Comment by kevgliss** [comment]
It looks like the variable for `business_year_hours` is not defined for your project. What was it removed somehow?

**Comment by mvilanova** [comment]
@csetarun2 are you still having the issue or can we close this?

**Comment by csetarun2** [comment]
It got fixed...can u close this issue..
If we enable costing for project...we have to add employee cost number in
db aswell..
I disabled cost budget for project...then it worked..

Thanks for ur help
