### ISSUE TITLE
"IncidentPriority not created. Reason: undefined" when creating some "Items"

### ISSUE THREAD

**Issue by alexandrosgkesos** [Netflix/dispatch#319]
Testing DIspatch's Authentication system installed with your Docker script and i get "Reason: undefined in few cases"

DISPATCH_AUTHENTICATION_PROVIDER_SLUG=""
![dispatchNoAuth](https://user-images.githubusercontent.com/62295151/82031527-4f6e9a80-969a-11ea-85c4-b639274ef777.jpg)

In the past, Priorities were being created, but not the "IncidentType"

DISPATCH_AUTHENTICATION_PROVIDER_SLUG= The whole line is deleted completely
![dispatchDeletedAuthLine](https://user-images.githubusercontent.com/62295151/82031589-6614f180-969a-11ea-9737-c60e3c793c99.jpg)

DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic
![dispatchBasicAuth](https://user-images.githubusercontent.com/62295151/82031633-73ca7700-969a-11ea-94e7-ef340338d87e.jpg)

Also if i try to create an Incident without any value set (Type/Priority/Users/etc) it loads for ever.
(Priority and Type are not mandatory, according to the non-red colors)

**Comment by alexandrosgkesos** [comment]
Let me know if that should be filed against the dispatch-docker repo

**Comment by kevgliss** [comment]
Do you have any logs for these errors?

**Comment by alexandrosgkesos** [comment]
@kevgliss Where are the logs being kept?
I don't see anything in /var/log/ or in documentation

**Comment by kevgliss** [comment]
It depends on your setup, typically they will just go to stdout if you're using that standard docker image I would try the `docker log`. See [here](https://docs.docker.com/config/containers/logging/)
