### ISSUE TITLE
make other org as a default organization 

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch#3275]
I have integrated okta for authentication, 
whenever I open url its redirecting to okta identity(sso) and then its  login to default organization and creates new user.
when I switch to other org , that user wont be exist. Since we are going to use other organization , where can I change like whenever user authneticate okta it should reditect to my other org and create user account there.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/21236859/232226459-c814643d-b1ba-48cc-bb6b-a4a2cf2fcf49.png">

<img width="954" alt="image" src="https://user-images.githubusercontent.com/21236859/232226495-27f14a59-b2af-4740-963d-5674c8604afd.png">

since I integrated with okta (sso) , I cant register manually,

@kevgliss @mvilanova any idea on this

**Comment by csetarun2** [comment]
Hi @kevgliss  any idea how to make default org to other organization, once it authenticate with okta its redirecting into the default org only, how to change this behaviour

**Comment by manireddyk** [comment]
hello team,

i also have similar use case where I want to give couple of users to have owner permission on another organization(other than default org). how can we do that?

**Comment by kevgliss** [comment]
@csetarun2 
> Hi @kevgliss any idea how to make default org to other organization, once it authenticate with okta its redirecting into the default org only, how to change this behaviour

Just to be clear you wish that on login you are able to configure which organization a user should be redirected to? We do have this flag on the organization's model but it looks like the frontend doesn't currently take this into account. I can make that change but I want to make sure that fits your requirement.

**Comment by kevgliss** [comment]
We currently only have the ability to update a user's role via the CLI. I can add an option to create a new user from the cli as well.

```
Usage: dispatch user update [OPTIONS] EMAIL

  Updates a user's roles.

Options:
  -o, --organization TEXT         Organization to set role for.  [required]
  -r, --role [Owner|Manager|Admin|Member]
                                  Role to be assigned to the user.  [required]
  --help                          Show this message and exit.
```

**Comment by csetarun2** [comment]
It will be helpful, Thanks @kevgliss :)

**Comment by kevgliss** [comment]
I created the CLI command here:
https://github.com/Netflix/dispatch/pull/3292

You also have the option of going to the register url `https://<dispatchUirl>/<organizationSlug>/auth/register` for that organization if you have registration enabled (probably not if you have SSO)

Let me see if I can make the SSO redirect respect the original URL such that if you are on /org1/incidents and are presented with a SSO it will send you back to /org1/incidents instead of /default/incidents.

**Comment by manireddyk** [comment]
Hi @kevgliss 

can we get this feature working in GUI please?

**Comment by manireddyk** [comment]
if this can be to next release would be awesome. I would love to see new users getting added to custom organization using Dispatch GUI.

**Comment by kevgliss** [comment]
@manireddyk Sorry, I was OOO last week and we have a an offsite this week, I will circle back on this next week.

**Comment by kevgliss** [comment]
@manireddyk I've created #3397 which will allow you to create users manually via the membership UI. I will take a look at the SSO redirect in a separate PR.
