### ISSUE TITLE
On new organization data from other org is visible and tables are not creating properly in newer one

### ISSUE THREAD

**Issue by anupam-meesho** [Netflix/dispatch#3287]
**Describe the bug**
I was creating new organization into the system. I created incident in my other organization. Then new organization. The data is going into only to the older organization schema and there were no tables created in the newer one.

**To Reproduce**
1. Go to 'Profile and create new organization'
2. Click on 'Switch organization and create incident into the newer one.'
3. Click on 'Profile and switch to older organization'

**Expected behavior**
When you switch to newer organization only data to that particular organization should be visible and not of the others.

**Screenshots**
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/103025860/233119914-1aad45cb-983d-43c0-81dd-c34d732c55dd.png">

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser chrome
 - Version 112.0.5615.121

**Additional context**
App is running on ubuntu server

**Comment by kevgliss** [comment]
Thanks for the report, I will take a look and get back to you.

**Comment by kevgliss** [comment]
Just to confirm; after the organization has been created (e.g. next page load) switching between organizations works okay? Is the issue only after immediately creating a new organization?

Also, would you prefer if after creation we sent you to the new organization?

**Comment by anupam-meesho** [comment]
Yeah, the organisation switching works fine but seems to have no effect on the data. Also restart fixes the problem as the data is still present in the Database.

**Comment by priyanshu-panwar** [comment]
@kevgliss Can I take up this issue?

**Comment by kevgliss** [comment]
@priyanshu-panwar Sure! I think it has something todo with how we reload the app after an organization is created:
https://github.com/Netflix/dispatch/blob/master/src/dispatch/static/dispatch/src/organization/store.js#L50

When we switch organizations we modify the router param before calling `go`:
https://github.com/Netflix/dispatch/blob/master/src/dispatch/static/dispatch/src/components/AppToolbar.vue#L180

I wasn't able to replicate entirely, but I do think there is some weirdness after creation where the frontend is stuck in a bad state after organization creation.
