### ISSUE TITLE
User name switches to unknown

### ISSUE THREAD

**Issue by anupam-meesho** [Netflix/dispatch#3298]
**Describe the bug**
When there is a new manual incident created there is some issue in the user fetch. It gets converted to Unknown even after updating the user multiple times. 

**To Reproduce**
1. Go to settings
2. Click on Project and add individual 
3. Click on Incident and report a new incident filling up all the details with the same added individual
4. Post incident creation the user name in reporter/incident commander becomes **unknown** 

**Expected behavior**
The username should remain the same as it was added into the individuals

**Screenshots**
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/103025860/234193481-5c689b90-8ab9-4f67-b06d-7e0ae7bc4ce8.png">
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/103025860/234193937-d9dcd65d-2ceb-4f1a-a09d-2ff47fc78603.png">
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/103025860/234194065-8c657593-5a87-4a77-810f-97fbf9cfed14.png">

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome
 - Version 112.0.5615.137

**Comment by wssheldon** [comment]
Thanks for reporting this. Can you confirm that you do *not* have a `contact` plugin enabled?

**Comment by wssheldon** [comment]
Are you still encountering this issue on the latest release?
