### ISSUE TITLE
Rename from Security Incident Tool to Incident Tool

### ISSUE THREAD

**Issue by tomarv2** [Netflix/dispatch#332]
@kevgliss  @mvilanova I want to see if you have any plans on renaming the tool from Security Incident Tool to just Incident Tool, I have other teams like support and outage who would like to use it.

**Comment by kevgliss** [comment]
Hi @tomarv2, you're not the only one thinking about using Dispatch for non-security related incidents. I believe @willbengtson has other SRE type teams interested as well. Is the name/description a big hang-up? Or just a point of clarification?

To be clear, we will generally support non-security use cases within Dispatch so I wouldn't be worried about that.

**Comment by tomarv2** [comment]
thanks for the comments, it's more on clarification side for other teams, just to ensure they understand it's not related to security only.

**Comment by mvilanova** [comment]
@tomarv2 we're planning to allow you to customize some of the strings in messages in the future (e.g. intake form title, description, etc.), which I think it will help non-security teams feel more included.

**Comment by willbengtson** [comment]
@tomarv2 we will be using dispatch at my company for all teams. Ops, SRE, Security IR, Vuln Management, etc. Example being that soon you will be able to specify different Jira projects based on the incident type: https://github.com/Netflix/dispatch/pull/336
