### ISSUE TITLE
What is the flow of the incident 

### ISSUE THREAD

**Issue by tarunmittal24** [Netflix/dispatch#3391]
Hi All,

Just wanted to know the flow of the incident, what happens when we create the incident and how to implement the escalation matrix for the incident.

From the flow means, as soon as an incident is created, create a slack channel, then email the commander like that, where we can define all of this.

I am not able to identify it from the docs, I am checking this:- **https://netflix.github.io/dispatch/docs/administration**

**Comment by kevgliss** [comment]
Hi, @tarunmittal24 the flow itself is largely not configurable (i.e. the given order of things happening). What you can configure is if a certain resource is created. For example, if you disable the slack plugin no incident conversation will be created. 

If you have not already I'd also encourage you to take a look at our original blog post:
https://netflixtechblog.com/introducing-dispatch-da4b8a2a8072

Some of the specifics are out of date but the overall methodology hasn't really changed.
