### ISSUE TITLE
How to Change the Incident Name

### ISSUE THREAD

**Issue by tarunmittal24** [Netflix/dispatch#3437]
I am using the default configuration, I just used the dispatch-docker repo to deploy dispatch and load the sample Postgres data, configuring the slack integration.

After I am creating the incident using the web UI, a Slack notification is triggered and the channel is created in Slack but the incident name and the slack channel name is auto-generated as you can see in the screenshot attached.

Looks like it follows this naming-convention  [ `dispatch-<org-name>-<project-name>-<number>` ]

e.g:- dispatch-default-zfh-project-7

**Can we change this naming convention anyhow ??**

![screenshot-localhost_8000-2023 05 29-14_55_56](https://github.com/Netflix/dispatch/assets/131644722/fdf07f8a-ebe4-4708-950c-43893668770e)

**Comment by tarunm97** [comment]
@kevgliss , can you please help here

**Comment by kevgliss** [comment]
@tarunm97 The incident name is currently controlled by the `ticket` plugin you have enabled. For instance, if you have jira enabled then the Jira ticket name will be the incident name. If no, ticket plugin is enabled the default is to use Dispatch's ticket plugin:

https://github.com/Netflix/dispatch/blob/master/src/dispatch/plugins/dispatch_core/plugin.py#L223

We don't currently allow this string to be configured in the Dispatch plugin (I'd be interested to know what naming scheme you were thinking of). But, depending on your requirements you could similarly create your own plugin to generate whatever string you'd like.

**Comment by tarunmittal24** [comment]
It is great to hear from @kevgliss , but we can make this a parameter, so users can enter what they want, and we should not hardcode the ticket-name, which I believe to be an important identifier. Thanks for the code-reference
