### ISSUE TITLE
individual contact name automatically renaming to dispatch

### ISSUE THREAD

**Issue by manireddyk** [Netflix/dispatch#3450]
Hi 
We have build dispatch using latest code, and we have loaded bulk individual contacts directly into the database.
we can able to see all user in the UI now.
but the issue is whenever user creates an ticket automatically his name changing into dispatch in the database , which means if all ppl in my org creates an incident their names be changing into dispatch, is there any hardcoded this value , can you plesae help us
 
only name is changing into the disaptch, mail id remains be the same..

![dispatch-duplicates-names](https://github.com/Netflix/dispatch/assets/46611593/e5dac78e-8820-47d1-888c-2662837ad227)

@mvilanova @kevgliss  can u please look into this

**Comment by manireddyk** [comment]
also I can able to modify existing individual-records but couldnt able to create/add new individual contacts
![names-add](https://github.com/Netflix/dispatch/assets/46611593/335e9905-866d-46ed-bb79-b319da48e104)

**Comment by kevgliss** [comment]
To restate your first issue: After a user has been registered, when they create an incident their dispatch user name is changed to `dispatch`? 

If so, that would be very strange indeed. Could you tell me which plugins you have enabled?

**Comment by manireddyk** [comment]
yes @kevgliss , If an user creates an incident his name is going to be change to dispatch
I have enabled below plugins, could you please check once, is there anywhere we hardcoded default value

![plugins](https://github.com/Netflix/dispatch/assets/46611593/f2902135-2f3c-4bd8-ae56-68ede949218a)

**Comment by manireddyk** [comment]
we have added other custom plugin , we have enabled both plugins due to that this error came, after disabling core plugin Im getting normal names, thanks
