### ISSUE TITLE
Any Guide to Setup the Google SSO

### ISSUE THREAD

**Issue by tarunm97** [Netflix/dispatch#3451]
hi @kevgliss , is there any doc which i can follow to setup the google sso in the dispatch, not able to set it up using the docs.

**Comment by kevgliss** [comment]
Hi @tarunm97, we don't have any guide specific to Google SSO. Dispatch uses PKCE as its auth flow which should be compatible with Google SSO (we use Google's own openid-connect library):
https://netflix.github.io/dispatch/docs/administration/settings/server#authentication 

But some of the specifics on setting this up are provider specific, like using the google specific discovery document:
https://developers.google.com/identity/openid-connect/openid-connect#discovery
https://developers.google.com/identity/openid-connect/openid-connect#exchangecode

If you are able to get a series of steps together we'd love community contributions in this space.
