### ISSUE TITLE
Bypass Jira

### ISSUE THREAD

**Issue by tomarv2** [Netflix/dispatch#347]
@kevgliss how do I bypass Jira, for example, its having issue authenticating, I want it to continue but right now it fails.

**Comment by kevgliss** [comment]
@tomarv2 you can disable jira by enabling the dispatch-ticket-plugin and disabling the jira plugin in the plugin UI.

**Comment by tomarv2** [comment]
Thanks @kevgliss .. I think this is not possible with the master branch as yet. Will keep an eye on it.

**Comment by kevgliss** [comment]
It is possible with master, we just release a new version yesterday with the required changes.
