### ISSUE TITLE
Plans To Support Enterprise SSO (e.g. OpenID Connect/SAML)?

### ISSUE THREAD

**Issue by Osipion** [Netflix/dispatch#348]
Great project, thanks for sharing. I want to understand if there are any plans to support authentication flows via an external IdP (e.g. AD, Okta, OneLogin etc.)? If not, is the project open to PRs that add an OIDC or SAML authentication flow and has any thoughts on which would be preferred? Think a feature like this could really help adoption in corp environments.

**Comment by kevgliss** [comment]
Today, we support the PKCE auth flow (which I believe is supported by Okta, maybe others?). 
We're open to PRs for other providers/flows. This would be accomplished by writing a new AuthenticationProviderPlugin for those providers. As an example:

https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_core/plugin.py#L61
