### ISSUE TITLE
Invalid Slack notification for closed incidents

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#3516]
We have incidents in Dispatch that are in closed state. But, we are still getting Dispatch notifications by the Slack bot to close the incident. For example:

Here is the Dispatch ticket that was closed last year. 
<img width="603" alt="Screenshot 2023-06-22 at 7 11 32 AM" src="https://github.com/Netflix/dispatch/assets/52274121/6059d395-437c-43d9-9ae2-76996b6c02bb">

Here is the slack notification that I got a few days back.
<img width="729" alt="Screenshot 2023-06-22 at 7 10 50 AM" src="https://github.com/Netflix/dispatch/assets/52274121/7a8408c3-91db-4d2e-8c3b-afe0e22ed9c2">

In the scheduler pod, we are getting this error regularly:
`TypeError: '>' not supported between instances of 'datetime.datetime' and 'NoneType'
ERROR:dispatch.incident_cost.scheduled:'>' not supported between instances of 'datetime.datetime' and 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/dispatch/incident_cost/scheduled.py", line 54, in calculate_incidents_response_cost
    if incident_response_cost.updated_at > incident.stable_at:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
But this seems to be related to cost calculation, and should not be related to the slack notification issue. 

We are using v20230505 build of Dispatch in our environment.

**Comment by mvilanova** [comment]
We have seen this TypeError before when the `stable_at` time does not get set in the database. It's likely that `stable_at` not being set is leading to the close reminder notifications as well as we rely on this timestamp for deciding whether we need to notify or not: https://github.com/Netflix/dispatch/blob/master/src/dispatch/incident/scheduled.py#L213

Can you check if `stable_at` is being set in the `incident` table in your database?

**Comment by vikassinha2019** [comment]
Thanks @mvilanova for looking into it. 

Yes, I can see values set for `stable_at` field in `incident` table for all incidents.

<img width="966" alt="Screenshot 2023-06-26 at 8 36 16 AM" src="https://github.com/Netflix/dispatch/assets/52274121/aa64b794-be43-4bab-b6a1-10c565b4b8ae">

**Comment by mvilanova** [comment]
Are you sure there are no `stable_at` columns with null values? The `TypeError` provided above is essentially saying that `incident.stable_at` is of `NoneType`.

**Comment by vikassinha2019** [comment]
okay, I was checking a few incidents where they had no `stable_at` columns with null values. 
However, I found one such incident that was in Closed state but had 'NULL' for `stable_at` column. I have added the right value for that field now. 

So, is that single incident can be causing false notification for other incidents, even though they had all fields populated fine?
