### ISSUE TITLE
can we get notification for the tasks creation ?

### ISSUE THREAD

**Issue by manireddyk** [Netflix/dispatch#3586]
Hi @kevgliss  @mvilanova 
I have created incidents for that Im getting slack notifiactions, later I have created tasks and attached to the incident which I have created earlier, I dont see any event notification for the tasks creation and attachment .

can you please let me know is this feature already available,  If not can you please add in your to-do list, it will be helpful for us, whenever new task get attached to the incident, in the parent incident slack group a task message has to be pop-up to notify people.

**Comment by kevgliss** [comment]
It looks like we weren't notifying for tasks created via the UI. Please see #3590 for the fix.

**Comment by kevgliss** [comment]
I'll also point out some caveats around these notifications:

- Only triggered on state change (Open, Resolved)
- Send as an ephemeral message to the assignee (not the whole channel)
