### ISSUE TITLE
How to upgrade dispatch ?

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch#3602]
Im using 3months old dispatch version, whenever I try to test new version, its breaking , I have to drop all db, and start from fresh, 
Is there any smooth way to do that ?

current doc is not sufficient/clear  , I couldnt understand how to generate conf file

<img width="782" alt="image" src="https://github.com/Netflix/dispatch/assets/21236859/ee3720d8-42d7-4160-8fc9-a6228cc3cecf">

should I clone new code, build image, then do database upgrade command ? or is something different , 
can you share the steps while moving to next version
@mvilanova @kevgliss  can u guide me

**Comment by kevgliss** [comment]
You should have to run `dispatch database upgrade`. I would do this on a snapshot / backup of your data first. Let us know if you have errors during the upgrade. Or if something isn't working right and we can take a look.
