### ISSUE TITLE
Support dynamic enums for Case Status and Resolution

### ISSUE THREAD

**Issue by aidn-tommy** [Netflix/dispatch#3609]
**Is your feature request related to a problem? Please describe.**
[Case enums](https://github.com/Netflix/dispatch/blob/master/src/dispatch/case/enums.py) are currently hardcoded (as far as I can tell). When tracking different types of cases, the status and resolution may vary by the procedure path taken. For instance a Case created from an impossible travel scenario will differ in conclusion from the investigation into a supply chain incident (e.g. an account owner won't acknowledge it).

**Describe the solution you'd like**
It would be great if we can get these as configurable settings under the Case configuration of a project. 

**Describe alternatives you've considered**
The alternative is to lock processes into the existing options or to compile a custom version of Dispatch containing all possible permutations of case type, status and resolution, which is an unfavorable overhead.

**Additional context**
N/A

**Comment by kevgliss** [comment]
I think this is a logical next step, we weren't sure what usage might look like but these should be relatively easy to add.

**Comment by kevgliss** [comment]
I think @whitdog47 will be taking this feature on.
