### ISSUE TITLE
API auth when SSO is enabled using PKCE

### ISSUE THREAD

**Issue by SREbharatkumar** [Netflix/dispatch#3613]
Hello Netflix team,

We are using dispatch with PKCE auth enabled using OKTA SSO. We are in the process of building some automation will need to make use of dispatch's API for incident management. The current API documentation provides details only on username and [password based auth](https://netflix.github.io/dispatch/docs/api#tag/auth/operation/get_me__organization__auth_me_get).

Is there support for any token based auth available for using the APIs, when PKCE is used for logging onto the UI, where we can create an API/App token to communicate with the API?

**Comment by kevgliss** [comment]
@whitdog47 was investigating possible use cases for API tokens.

**Comment by whitdog47** [comment]
@SREbharatkumar - currently you can do a post to `/api/v1/<organization>/auth/login` with the email and password in the body and get a token as a response. Would that work?

**Comment by aidn-tommy** [comment]
@kevgliss re. use cases I was looking into a similar issue recently when trying to send in an email as a webhook to create a Signal and then a case. 

For this the workaround suggested by @whitdog47 won't work, but this is perhaps where the (future?) signals consumer plugins and e.g. something like PubSub may come into play?

**Comment by kevgliss** [comment]
@aidn-tommy I'd have to hear more about the email <-> signal -> case use-case, but today I think we'd implement such functionality as a `signal-consumer` plugin and have the plugin monitor a mailbox or dl for new messages to process.

**Comment by kevgliss** [comment]
Also, surrounding proper API token support. We do agree it's something we should have, but we don't currently have an internal use case so it's not super high on the priority list. Internally, we have mTLS (and internal authentication plugin) that makes such API tokens not required for our own integrations. But we do realize this isn't a reasonable solution for most folks.
