### ISSUE TITLE
Zoom plugin does not work anymore

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#3812]
Zoom plugin in Dispatch works with Zoom JWT API Key. However, as of September 8, 2023, the JWT app type has been deprecated by Zoom. Due to this the Zoom plugin does not work anymore in Dispatch. We only get a link to https://zoom.us in the incident channel. 

<img width="154" alt="Screenshot 2023-09-27 at 10 49 32 PM" src="https://github.com/Netflix/dispatch/assets/52274121/35b0143d-d586-483e-929e-c8655aebd9f3">

As Zoom call is an eminent feature of incident management tool, please help in providing the solution of this issue on priority.
Thanks!

**Comment by wssheldon** [comment]
Hello,

Thanks for raising the issue. We don't use Zoom internally so it'll be hard for us to test and maintain this plugin. the change should be fairly straightforward. You'll want to modify the client code that handles authentication, which is here: 

https://github.com/Netflix/dispatch/blob/master/src/dispatch/plugins/dispatch_zoom/client.py
