### ISSUE TITLE
docker build fails  

### ISSUE THREAD

**Issue by inv1sible** [Netflix/dispatch#39]
Am trying to `docker build` or executing `/dispatch-docker/install.sh` ~~on a Mac~~ under Ubuntu 20.04. Unfortunately the process fails with the following output. 

```
Step 14/44 : RUN set -x     && wget -O /usr/local/bin/tini "https://github.com/krallin/tini/releases/download/v$TINI_VERSION/tini"     && wget -O /usr/local/bin/tini.asc "https://github.com/krallin/tini/releases/download/v$TINI_VERSION/tini.asc"     && gpg --batch --verify /usr/local/bin/tini.asc /usr/local/bin/tini     && rm /usr/local/bin/tini.asc     && chmod +x /usr/local/bin/tini
 ---> Using cache
 ---> ffdcf0d5d43e
Step 15/44 : COPY .nvmrc /usr/src/dispatch/
COPY failed: stat /var/lib/docker/tmp/docker-builder708155561/.nvmrc: no such file or directory
```

What am I doing wrong? Any tips or ideas? Thx in advance

**Comment by pepck-svc** [comment]
FWIW I'm getting the same error on an Ubuntu 18.04 box (on latest master):

> Removing intermediate container 87a91609c136
>  ---> 51d6300d7e47
> Step 15/44 : COPY .nvmrc /usr/src/dispatch/
> ERROR: Service 'web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder243719387/.nvmrc: no such file or directory
> Cleaning up...

Docker/Docker Compose versions:
> Client: Docker Engine - Community
>  Version:           19.03.6
>  API version:       1.40
>  Go version:        go1.12.16
>  Git commit:        369ce74a3c
>  Built:             Thu Feb 13 01:27:49 2020
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.6
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.12.16
>   Git commit:       369ce74a3c
>   Built:            Thu Feb 13 01:26:21 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.2.12
>   GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
>  runc:
>   Version:          1.0.0-rc10
>   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683

> docker-compose version 1.25.4, build unknown

**Comment by fabiang** [comment]
Make sure you dont run ˋdocker buildˋ from the base directory instead of inside ˋdocker/ˋ. Specify the Docker file like this: ˋdocker build -f docker/Dockerfile .ˋ

**Comment by jsenon** [comment]
If you use `dispatch-docker/install.sh` you can modify the docker-compose with
```
 build:
    context: https://github.com/Netflix/dispatch.git#master
    dockerfile: docker/Dockerfile
```

**Comment by pauroger** [comment]
Got the same error as OP. (Catalina v.10.15.3)

Also tried this:

> If you use `dispatch-docker/install.sh` you can modify the docker-compose with
> 
> ```
>  build:
>     context: https://github.com/Netflix/dispatch.git#master
>     dockerfile: docker/Dockerfile
> ```

And now I am getting this error:

`ERROR: Service 'web' failed to build: The command '/bin/sh -c set -x     && buildDeps=""     && apt-get update     && apt-get install -y --no-install-recommends $buildDeps     && pip install -i https://smartiproxy.mgmt.netflix.net/pypi /tmp/dist/*.whl     && apt-get purge -y --auto-remove $buildDeps     && apt-get install -y --no-install-recommends     pkg-config         && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1`

**Comment by jsenon** [comment]
Pypi server could not be reach I’ve open this issue https://github.com/Netflix/dispatch/issues/40

**Comment by jwillmer** [comment]
How can they open source something with a broken installation. This is ridiculous. Anyone who might be interested in this product will first try it in a container before investing any time in a bare metal installation. Only to find out that it is not working..

**Comment by kevgliss** [comment]
@jwillme While I understand your frustration, please keep in mind that open-sourcing projects is not part of our normal day jobs and is typically something we try to do to give back to the community. 

That being said the error you're running into was fixed in develop before release but had not yet been merged to master. It now has been.

**Comment by jwillmer** [comment]
It is still not working for me. Did someone get it to work?

```
Step 37/44 : COPY ./docker/docker-entrypoint.sh ./docker/.env $DISPATCH_CONF/
ERROR: Service 'web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder153433637/docker/.env: no such file or directory
```

**Comment by TheDahv** [comment]
@jwillmer there are a few other things to fix, but I believe that particular problem comes from the docker-compose `build` configuration.

Look at `docker-compose.yml` and find the `web.build.context` config. Change this:

```
   build:
-    context: https://github.com/Netflix/dispatch.git#master:docker
+   context: https://github.com/Netflix/dispatch.git#master:.
```

That unblocked me on that error, but there are others to tackle that I'm working on now.

**Comment by TheDahv** [comment]
@jwillmer I'm working on cleaning up both the Docker build and the invocations in the dispatch-docker project. I don't think the build actually needs the .env file since it's supposed to be supplied at runtime in the Docker Compose project. So here's something that unblocks the build but there are a few other related issues I'm still working on

https://github.com/TheDahv/dispatch/commit/db0fbda11f5cb51000ef66b24a9bd27fe1ad32d2

**Comment by inv1sible** [comment]
```
- COPY ./docker/docker-entrypoint.sh ./docker/.env $DISPATCH_CONF/
+ COPY ./docker/docker-entrypoint.sh $DISPATCH_CONF/
```
fixes build issue @TheDahv +1

**Comment by inv1sible** [comment]
thanks everyone for your commitment. with the change in db0fbda the build succeed but when running the image it stops with

`server: 1: exec: /etc/dispatch/docker-entrypoint.sh: Permission denied`

ideas?

**Comment by TheDahv** [comment]
@inv1sible check out

https://github.com/Netflix/dispatch/issues/50
https://github.com/Netflix/dispatch/pull/51
https://github.com/Netflix/dispatch/pull/53

**Comment by TheDahv** [comment]
For a short-term fix, run `chmod +x docker/docker-entrypoint.sh` and rebuild the image.

**Comment by kevgliss** [comment]
There have been quite a few fixes (thanks @TheDahv + others). While I have released the majority of 
 they to `master` things are in flux please check out the `develop` branch for the latest if you run into issues. 

For now, I am going to close this issue out please open additional issues as necessary.

**Comment by jsenon** [comment]
Thanks @kevgliss
