### ISSUE TITLE
v-alert icon colors don't match text

### ISSUE THREAD

**Issue by kevgliss** [Netflix/dispatch#3991]
![Screenshot 2023-11-15 at 9 59 36 AM](https://github.com/Netflix/dispatch/assets/2262214/923ac5da-bcbc-4b07-a331-183bd440fe1d)

@KaelWD would you be able to help with this?

**Comment by KaelWD** [comment]
https://github.com/Netflix/dispatch/blob/df8d1023fa4fac061a2f4309583c18707ed93505/src/dispatch/static/dispatch/src/vuetify/index.js#L43-L45
