### ISSUE TITLE
pypi server not reachable

### ISSUE THREAD

**Issue by jsenon** [Netflix/dispatch#40]
With master branch your internal pypi server could not be reach.

https://github.com/Netflix/dispatch/blob/985335da4e5bc3fcfe74d19c7eb1d256a109c398/docker/Dockerfile#L112

**Comment by bobflorian** [comment]
same, can't get past this step.

**Comment by kevgliss** [comment]
Sorry, this was fixed in developed but not yet merged into master.

**Comment by kevgliss** [comment]
Resolved by #45
