### ISSUE TITLE
How to delete all incidents at once ?

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch#4023]
Is there any option where I can delete all my incidents, and is there any custom field availably my incidents will start number from 100 ?

**Comment by whitdog47** [comment]
Hi @csetarun2 - the easiest way to do this is to use pgAdmin. To delete all the incidents, you can truncate the incident table. To change the starting incident number, so under Sequences and under `incident_id.seq` select Definition, where you can change the start number.
<img width="496" alt="Screenshot 2023-11-25 at 7 37 38 PM" src="https://github.com/Netflix/dispatch/assets/84562015/d97f2568-001c-4f29-b431-aa53dc891bda">
