### ISSUE TITLE
Getting Internal server error 500 for many api calls

### ISSUE THREAD

**Issue by Martin1196155** [Netflix/dispatch#406]
I run the ./install.sh and i refer develop branch of the dispatch. When i am loading web UI i am getting below error
![image](https://user-images.githubusercontent.com/46367679/83797359-2735f280-a6c0-11ea-8318-98b3a9adda67.png)

In ngrok console i found few api call got internal server error 500.

![image](https://user-images.githubusercontent.com/46367679/83797426-403ea380-a6c0-11ea-95b2-d9c2ec9b975f.png)

after that i click every option in the left hand side and i am getting the same error.

![image](https://user-images.githubusercontent.com/46367679/83797535-71b76f00-a6c0-11ea-979b-5b40a161a669.png)

Can anyone please help me to resolve this issue.

**Comment by mvilanova** [comment]
@Martin1196155 the error in the first screen is expected when there's no data in the database. @kevgliss we may want to provide a less scary, more informative message here.

**Comment by kevgliss** [comment]
The errors could be lack of data or something else entirely, we would need the error logs from the server to know. @Martin1196155 could you provide those logs?

**Comment by Martin1196155** [comment]
@mvilanova @kevgliss Please find the attachment contains the docker logs for the dispatch web container.
[Logs.txt](https://github.com/Netflix/dispatch/files/4737910/Logs.txt)

**Comment by kevgliss** [comment]
I don't see the server startup in those logs, but based on `2020-06-05T15:26:58.800406049Z KeyError: 'dispatch-auth-provider-basic'` it's likely that your database is not up to date. Please try and run `dispatch database upgrade`

**Comment by gargrag** [comment]
Hi I'm having the same error on a fresh install, I did run the `dispatch database upgrade` 

![image](https://user-images.githubusercontent.com/967311/84549126-1424b300-acbc-11ea-80f5-ecc8c41de64e.png)

I'm still debugging to see if I can find something else.

**Comment by gargrag** [comment]
@Martin1196155  OK! got it, you DO NEED to set `DISPATCH_JWT_SECRET=something` if you want to get rid of the error.

**Comment by Martin1196155** [comment]
I think the new update in the dispatch-docker works. I registering by using https://XXXXXX:8000/register. Now i am not getting this issue.

**Comment by Martin1196155** [comment]
But still i am getting error while creating incident. 
![image](https://user-images.githubusercontent.com/46367679/84672471-37fb2980-af46-11ea-9759-15c699209585.png)
![image](https://user-images.githubusercontent.com/46367679/84672558-506b4400-af46-11ea-9d7b-580e90f17e49.png)

**Comment by kevgliss** [comment]
@Martin1196155 we still require that all plugins are set up correctly before we can create an incident, we're working on making them optional (#55) but you're likely running into an issue where one of the required plugins is not setup correctly.

You'll likely to take a look at the server logs to see which plugin is not setup correctly.
