### ISSUE TITLE
Docker build: env file not found

### ISSUE THREAD

**Issue by jsenon** [Netflix/dispatch#41]
`.env` file doesn't exist in the directory `docker`. See dockerfile: https://github.com/Netflix/dispatch/blob/56a9435d08b32429c6b44f83cb0f5aff5a8b6931/docker/Dockerfile#L124

**Comment by kevgliss** [comment]
I've added an example in #48 but you will need to create your `.env` with your secrets/values. See: https://hawkins.gitbook.io/dispatch/configuration/app for details.
