### ISSUE TITLE
Getting Error with database setup 

### ISSUE THREAD

**Issue by yeshwanth1312** [Netflix/dispatch#416]
**Describe the bug**
Error loading plugins 

**To Reproduce**
when reloading UI , We always see below 
Something has gone very wrong, please retry or let your admin know that you recieved this error.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Running in Docker 
 - Browser chrome

**Additional context**
seeing below in logs 
No JWT secret specified, this is required if you are using basic authentication.
No metric providers specified metrics will not be sent.
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
WARNING:dispatch.common.utils.cli:Failed to load plugin: opsgenie_oncall Reason: "Config 'OPSGENIE_API_KEY' is missing, and has no default."
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
WARNING:dispatch.common.utils.cli:Failed to load plugin: zoom_conference Reason: "Config 'ZOOM_API_USER_ID' is missing, and has no default."
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

**Comment by kevgliss** [comment]
Are you running this directly or via `dispatch-docker` file? This usually means that your database is not up to date. Please run `dispatch database upgrade`

**Comment by yeshwanth1312** [comment]
`dispatch database upgrade
No JWT secret specified, this is required if you are using basic authentication.
No metric providers specified metrics will not be sent.
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
WARNING:dispatch.common.utils.cli:Failed to load plugin: opsgenie_oncall Reason: "Config 'OPSGENIE_API_KEY' is missing, and has no default."
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
ERROR:dispatch.common.utils.cli:Something went wrong with creating plugin rows, is the database setup correctly?
WARNING:dispatch.common.utils.cli:Failed to load plugin: zoom_conference Reason: "Config 'ZOOM_API_USER_ID' is missing, and has no default."
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade b12f7a59ced9 -> e7c696ffd69a, Replaces application table with tag table.
INFO  [alembic.runtime.migration] Running upgrade e7c696ffd69a -> 8b67c774279d, Adds association table for incident tags
INFO  [alembic.runtime.migration] Running upgrade 8b67c774279d -> 5d4dee3e24fc, Adds column for conference challenge
INFO  [alembic.runtime.migration] Running upgrade 5d4dee3e24fc -> 5957303b1b8a, Adds additional columns to incident priorities.
INFO  [alembic.runtime.migration] Running upgrade 5957303b1b8a -> d841f9945338, Adds status report reminder.
INFO  [alembic.runtime.migration] Running upgrade d841f9945338 -> 343bc4e6aa79, Creates table for event model
INFO  [alembic.runtime.migration] Running upgrade 343bc4e6aa79 -> 057604415f6c, Adds a service description.
INFO  [alembic.runtime.migration] Running upgrade 057604415f6c -> 14d7a4703d7c, Renames columns in participant role model
INFO  [alembic.runtime.migration] Running upgrade 14d7a4703d7c -> 1221a4d60f03, Adds discoverable column
INFO  [alembic.runtime.migration] Running upgrade 1221a4d60f03 -> 895ae7783033, Adds plugin table
INFO  [alembic.runtime.migration] Running upgrade 895ae7783033 -> 62465f508f69, Adding dispatch user table
INFO  [alembic.runtime.migration] Running upgrade 62465f508f69 -> 2d3e511db6b4, Adds required or multiple fields to plugin data
INFO  [alembic.runtime.migration] Running upgrade 2d3e511db6b4 -> 6f04af3f261b, Adds details column to event model
INFO  [alembic.runtime.migration] Running upgrade 6f04af3f261b -> 9a3478cbe76c, Adds primary key id to user table.
INFO  [alembic.runtime.migration] Running upgrade 9a3478cbe76c -> d1e66a4ef671, Migrates after hours flag to participant model.
INFO  [alembic.runtime.migration] Running upgrade d1e66a4ef671 -> a32bfbb4bcaa, Adds a unique constraint to email.
INFO  [alembic.runtime.migration] Running upgrade a32bfbb4bcaa -> 9b4a5ff08170, Add JSON column to Incident Type table to allow for plugin metadata
INFO  [alembic.runtime.migration] Running upgrade 9b4a5ff08170 -> cfd62f719c84, Migrates the incident metadata json
INFO  [alembic.runtime.migration] Running upgrade cfd62f719c84 -> a57934336710, Adds task ticket association table
INFO  [alembic.runtime.migration] Running upgrade a57934336710 -> dd3df6a3af3c, Generalizes data model for incident reports (tactical, executive)
INFO  [alembic.runtime.migration] Running upgrade dd3df6a3af3c -> 9eaa2a392dae, Adds executive_report_reminder column to incident priority model
INFO  [alembic.runtime.migration] Running upgrade 9eaa2a392dae -> 5693756fd192, Migrates assignee and creator emails to participants.
Success.`


Seeing same issue after upgrade , Also copied sample data [https://github.com/Netflix/dispatch/blob/develop/data/dispatch-sample-data.dump](url) . UI doesn't show any data

**Comment by kevgliss** [comment]
Do you only see that error on the dashboard? Also, how are you loading that sample data into the database?

**Comment by yeshwanth1312** [comment]
I am using psql 
`psql dispatch < dis.dump`

**Comment by kevgliss** [comment]
Do you see any other errors in the logs or when you import the data? I believe your command should work, however, to be on the safe side can you try with the dispatch restore command?

Rename your dump file to `dispatch-backup.dump` and then run `dispatch database drop` and `dispatch database restore`

**Comment by yeshwanth1312** [comment]
Hi @kevgliss , Still not able to get this working , Did `dispatch database restore` , Restore says success , I am attaching logs here , Please have a look 
[Log.txt](https://github.com/Netflix/dispatch/files/4753279/Log.txt)

**Comment by kevgliss** [comment]
Please run `dispatch database upgrade` after you do the restore, I think the example data is a bit old and we still need to update it to the latest release, if that works I'll work on updating the example data.

**Comment by yeshwanth1312** [comment]
@kevgliss No luck .. Still not seeing data in UI

**Comment by bobmorane83** [comment]
> Hi @kevgliss , Still not able to get this working , Did `dispatch database restore` , Restore says success , I am attaching logs here , Please have a look
> [Log.txt](https://github.com/Netflix/dispatch/files/4753279/Log.txt)

Exact same problem here.

**Comment by kevgliss** [comment]
@bobmorane83 is your problem that you aren't seeing example data or that you  get the error: `No JWT secret specified, this is required if you are using basic authentication.`?

**Comment by bobmorane83** [comment]
> @bobmorane83 is your problem that you aren't seeing example data or that you get the error: `No JWT secret specified, this is required if you are using basic authentication.`?

Setting DISPATCH_JWT_SECRET=something did the trick. Thanks.
I'am now stuck in Javascript error to display incidents : TypeError: Cannot read property 'weblink' of null
Seems that the sample database is missing some fields : "href":item.commander.weblink

**Comment by kevgliss** [comment]
So, I think the example data was pretty old. @bobmorane83 would you mind seeing if this dump resolves your issue? It's based on the `master` codebase branch: https://github.com/Netflix/dispatch/pull/455

The established user is:
`joe@example.com:test`

**Comment by bobmorane83** [comment]
Much better ;)
After : `dispatch database drop` and `dispatch database restore`, I could login, not with `joe@example.com:test` but with your real email address. May be you want to change that.
Thanks for the support.
