### ISSUE TITLE
Slack event hook returns invalid response

### ISSUE THREAD

**Issue by SMillerDev** [Netflix/dispatch#4298]
**Describe the bug**
Slack is claiming:
```
Our Request:
POST
"body": { 
	 "type": "url_verification",
	 "token": "",
	 "challenge": ""
}
Your Response:
"code": 
"error": "challenge_failed"
"body": {
  
}
```

**To Reproduce**
1. Try and setup a new slack plugin
2. Get an error

**Expected behavior**
I can save the Slack settings for events because the API responds succesfully.

**Screenshots**
<img width="644" alt="Screenshot 2024-01-26 at 16 09 57" src="https://github.com/Netflix/dispatch/assets/1484494/5c2dc03c-8965-4d59-8f38-b538cbe1190b">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I'm running this through an AWS loadbalancer instead of NGINX.

**Comment by SMillerDev** [comment]
Just gonna tag @mvilanova then, who touched the file I guess this is happening in last.

**Comment by SMillerDev** [comment]
@whitdog47 this still happens with the latest release by the way.

**Comment by rialg** [comment]
```shell
wget --method=POST      --header="Content-Type: application/json"      --body-data='{"type": "url_verification"}'      http://localhost:8000/api/v1/default/events/slack/event
--2024-11-07 10:20:33--  http://localhost:8000/api/v1/boozt/events/slack/action
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:8000... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-11-07 10:20:33 ERROR 403: Forbidden.
```

I have the same issue. Initially, I thought that it was related to the fact that [http handled](https://github.com/Netflix/dispatch/blob/f878a3eecb9f923b6ba040c9da22c32dcf939150/src/dispatch/plugins/dispatch_slack/endpoints.py#L52) requires the `slack-conversation` plugin to be enabled, or else it returns a `403` error. However, the problem persisted after enabling the plugin :/
