### ISSUE TITLE
docker-entrypoint.sh issue

### ISSUE THREAD

**Issue by tgrzinic** [Netflix/dispatch#43]
Any idea why this is happening after I do `docker run`:

```/etc/dispatch/docker-entrypoint.sh: line 12: syntax error near unexpected token `start'```

I set the chmod u+x, but I do not see the problem in the script.

**Comment by TheDahv** [comment]
@tgrzinic try updating your local `master` and see if you still get this error. I'm hoping my PR addressed it.

**Comment by tgrzinic** [comment]
Yeah, double quotes have saved my day.
I find some other problems. There is a problem with .env location in config.py, it should be copied to the container and have a DISPATCH_HELP_EMAIL defined.

Also when I try to access the app this happens, and crashes the container:
```
No metric providers specified metrics will not be sent.
Usage: dispatch server start [OPTIONS] APP
Try "dispatch server start --help" for help.

Error: Missing argument "APP".

```

I am closing this because the entrypoint issue is fixed. Thanks!
