### ISSUE TITLE
Duplicate entries in Documents

### ISSUE THREAD

**Issue by tomarv2** [Netflix/dispatch#438]
Hi Team,

I am seeing duplicate entries in docs for two items:

- Incident Conversation Reference Command Doc
- Incident FAQs

I was expecting they would begin Jira ticket name as other Docs.

<img width="563" alt="Screen Shot 2020-06-12 at 7 15 02 AM" src="https://user-images.githubusercontent.com/11890959/84512999-a9548700-ac7d-11ea-9f2f-b2e52c03e7eb.png">

**Comment by mvilanova** [comment]
@tomarv2 we are not prefixing them with the incident's name, because they're not specific to any incident. We create an object for them every time an incident is created, that's why you see duplicated entries for them. We're aware of it and will fix it. Thanks

**Comment by kevgliss** [comment]
Going forward this should be fixed by #461. Currently, I do no plan to create a migration to cleanup existing duplicates.
