### ISSUE TITLE
Helm Chart for Dispatch

### ISSUE THREAD

**Issue by tommy-skaug** [Netflix/dispatch#4573]
**Is your feature request related to a problem? Please describe.**
Deployment of Dispatch on Kubernetes.

**Describe the solution you'd like**
An official chart or operator in case this makes sense from the dev team's perspective to provide.

**Describe alternatives you've considered**
Hosting them on my own or in a community repo. It would be better to provide it from a trusted source though.

**Additional context**
I have built and are running Dispatch from a Helm Chart for deploying Dispatch to Kubernetes at [tommy-skaug/charts/dispatch](https://github.com/tommy-skaug/charts/tree/main/charts/dispatch). This is functional at a basic level being deployed with Flux, works connecting to Cloudnative-PG and with the Tailscale operator using auth headers. It also runs a db init. However, not production ready as-is.

**Comment by jawadqur** [comment]
Hi @tommy-skaug  - Do you still have the helm chart somewhere?

**Comment by tommy-skaug** [comment]
Hey @jawadqur. Absolutely. I'm restructuring my charts to go into app repos, but you can find the current version here: https://code.252.no/pub/charts/src/branch/main/charts/dispatch. You'll want to replace the image with your own etc.
