### ISSUE TITLE
Slack Returning Error on Command

### ISSUE THREAD

**Issue by alexa-kelley-vim** [Netflix/dispatch#495]
**Describe the bug**
When attempting to us a / command in slack associated with Dispatch I receive an error. 

for example 
`/dispatch-assign-role failed with the error "http_client_error"`

on the backend I get the following log error:
`web_1        | INFO:     <scrubbed IP>:55234 - "POST /api/v1/events/slack/dispatch-update-incident HTTP/1.1" 404 Not Found
web_1        | INFO:     <scrubbed IP>:64720 - "POST /api/v1/events/slack/dispatch-update-incident HTTP/1.1" 404 Not Found
web_1        | INFO:     <scrubbed IP>:54206 - "POST /api/v1/events/slack/dispatch-update-incident HTTP/1.1" 404 Not Found
web_1        | INFO:     <scrubbed IP>:64454 - "POST /api/v1/events/slack/dispatch-assign-role HTTP/1.1" 404 Not Found`

I have been able to confirm that the Dispatch server is able to post to the channel when doing updates on incidents. 

I have a suspicion that this may be because the document "INCIDENT_CONVERSATION_COMMANDS_REFERENCE_DOCUMENT_ID" that I point to is blank as there isn't a reference available in the documentation on expected syntax/config for it. 

Any suggestions on where I might be missing something?

EDIT: Sorry I forgot to mention. I am running on the development branch with everything to the most recent version through docker.

**Comment by mvilanova** [comment]
Hi @alexa-kelley-vim, we use the same endpoint for all commands `/api/v1/events/slack/command`. Can you update the request url in all your commands and try again?

**Comment by alexa-kelley-vim** [comment]
Thank you that seems to have done the trick for the /commands. Although now I'm noticing the following in the logs.

web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 35, in wrapper
web_1        |     result = func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 874, in incident_update_flow
web_1        |     set_conversation_topic(incident)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 400, in set_conversation_topic
web_1        |     convo_plugin.set_topic(incident.conversation.channel_id, conversation_topic)
web_1        | AttributeError: 'NoneType' object has no attribute 'channel_id'

**Comment by alexa-kelley-vim** [comment]
actually it looks like that is part of a separate issue. I'm going to test further and create a separate issue on it. The core issue with the / slack commands has been resolved. Thank you.
