### ISSUE TITLE
latest docker version of dispatch fails sending notification emails

### ISSUE THREAD

**Issue by vindex10** [Netflix/dispatch#5023]
When sending a email Dispatch uses `mjml`. Which seems to indirectly depend on `minimatch` .

`minimatch` is incompatible with node 12.x used in the docker image:
https://github.com/isaacs/rimraf/issues/265

Importantly:

* In the docker file, I noticed that the intermediate image uses Node 16.x to build the deps:
https://github.com/Netflix/dispatch/blob/fc9e0287e4c34fee34257cd6c8685a8c043a5887/docker/Dockerfile#L19

* But then uses 12.x for running the actual app:
https://github.com/Netflix/dispatch/blob/fc9e0287e4c34fee34257cd6c8685a8c043a5887/docker/Dockerfile#L89

 
 I changed the node version to 16.x on the line 89 + changed this:
`npm install mjml` ->  `npm install -g mjml`

Then I was able to start dispatch, create an incident and send the notification email - as much as I tested it for now.

**Comment by deepthi-kk** [comment]
Can someone assign this issue to me? I can take a look
