### ISSUE TITLE
hawkins.gitbook.io not accessible

### ISSUE THREAD

**Issue by robinbowes** [Netflix/dispatch#5026]
**Describe the bug**
There are several references to https://hawkins.gitbook.io throughout the project, but I am not able to access the docs on that site.

I get this message: `Authentication missing to access this content`

Is there a problem with the docs site, or is it internal-only?

**To Reproduce**
1. Go to https://hawkins.gitbook.io/dispatch/administration-guide/server
2. See error: ``Authentication missing to access this content``

**Expected behavior**
I expect to be able to read the doucmentation!

**Screenshots**
N/A

**Desktop (please complete the following information):**
MacOS, Chrome Version 127.0.6533.73 (Official Build) (arm64)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by robinbowes** [comment]
No love for this project?

**Comment by mvilanova** [comment]
@robinbowes our docs were moved to https://netflix.github.io/dispatch/.
