### ISSUE TITLE
Beta: Google Drive Folders "Sharing folders that are inside a shared drive is not supported."

### ISSUE THREAD

**Issue by alexa-kelley-vim** [Netflix/dispatch#515]
I am getting the following error when attempting to using the shared folder functionality within the develop branch in Dispatch. Could you please share instructions on the expected drive configuration so that I can recreate that on my end? 

`web_1        | /usr/local/lib/python3.8/site-packages/sqlalchemy/orm/collections.py:628: SAWarning: This collection has been invalidated.
web_1        |   util.warn("This collection has been invalidated.")
web_1        | WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "teamDrivesFolderSharingNotSupported"
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/drive.py", line 84, in make_call
web_1        |     return getattr(client, func)(**kwargs).execute()
web_1        |   File "/usr/local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
web_1        |     return wrapped(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 907, in execute
web_1        |     raise HttpError(resp, content, uri=self.uri)
web_1        | googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/<redacted>/permissions?sendNotificationEmail=false&fields=id&supportsTeamDrives=true&key=<Redactedkey>&alt=json returned "Sharing folders that are inside a shared drive is not supported.">
web_1        | 
web_1        | During handling of the above exception, another exception occurred:
web_1        | 
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 35, in wrapper
web_1        |     result = func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 467, in incident_create_flow
web_1        |     storage = create_incident_storage(
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 252, in create_incident_storage
web_1        |     storage = p.create_file(INCIDENT_STORAGE_FOLDER_ID, incident.name, participant_group_emails)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 59, in wrapper
web_1        |     result = func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 75, in wrapper
web_1        |     return func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/plugin.py", line 79, in create_file
web_1        |     response = create_file(client, parent_id, name, participants, role, file_type)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/drive.py", line 199, in create_file
web_1        |     add_permission(client, member, file_data["id"], role, "user")
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/drive.py", line 294, in add_permission
web_1        |     return make_call(
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 329, in wrapped_f
web_1        |     return self.call(f, *args, **kw)
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 409, in call
web_1        |     do = self.iter(retry_state=retry_state)
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 356, in iter
web_1        |     return fut.result()
web_1        |   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
web_1        |     return self.__get_result()
web_1        |   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
web_1        |     raise self._exception
web_1        |   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 412, in call
web_1        |     result = fn(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/drive.py", line 94, in make_call
web_1        |     raise Exception(f"Request failed. Errors: {errors}")
web_1        | Exception: Request failed. Errors: {'error': {'errors': [{'domain': 'global', 'reason': 'teamDrivesFolderSharingNotSupported', 'message': 'Sharing folders that are inside a shared drive is not supported.'}], 'code': 403, 'message': 'Sharing folders that are inside a shared drive is not supported.'}}`

**Comment by kevgliss** [comment]
Have you enrolled in the beta?

https://support.google.com/a/answer/9890318?hl=en#:~:text=Help%20CenterCommunity-,Folder%20sharing%20in%20shared%20drives%20(beta),folders%20within%20a%20shared%20drive.

To signup:
https://docs.google.com/forms/d/e/1FAIpQLSfrILe0_bPkkI7pxfr-4rHk0qcajrUOHTcmrWPOVLo0SKNF7A/viewform

**Comment by alexa-kelley-vim** [comment]
Ah no I haven't. I wasn't aware it was a pre-requisite to that functionality. I'll need to raise internally on if it's a direction we want to go with our GSuite administration or not.

**Comment by kevgliss** [comment]
Yes, we can always backport the existing google shared drive functionality. But we think now that google is enabling shared folders it's a much better solution for a few reasons:

- Creating shared drives took longer and was more error-prone than creating folders
- Shared drives tend to clutter a users sidebar in google drive
- Archiving files meant moving files from one shared drive to another (which if you had a lot of files could take quite a bit of time)

With shared folders, we can keep the data in a centralized place but still manage it's permission accordingly.

**Comment by kevgliss** [comment]
Updated the documentation with reference to the beta, will hopefully be able to remove once the feature goes GA in the next month or so.
