### ISSUE TITLE
Can not found server on Jira plugin

### ISSUE THREAD

**Issue by tiankai0114** [Netflix/dispatch#5153]
Hi，Everyone，

Why I can not found server or cloud configuration on Jira plugin, I use the latest code.
 
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/278afa68-62b9-4895-a3c4-c4c13f58b4b9">

<img width="457" alt="image" src="https://github.com/user-attachments/assets/836f109d-db34-490c-8349-0c48b3ebf688">

**Comment by mvilanova** [comment]
@tiankai0114 The Jira plugin configuration fields need to be set based on your Jira deployment, on-prem server or cloud.

**Comment by tiankai0114** [comment]
Hi @mvilanova ，got your point, my jira is server deployment, according to document https://netflix.github.io/dispatch/docs/administration/settings/plugins/configuring-jira, there is a parameter on the update page of jira plugin named JIRA_HOSTING_TYPE,
<img width="662" alt="image" src="https://github.com/user-attachments/assets/7249e4a5-86e2-4eb7-b9d9-27cd79641542">
 however I can not found this parameter on my update page, Is there anything else I need to do to display this parameter?

**Comment by mvilanova** [comment]
> Hi @mvilanova ，got your point, my jira is server deployment, according to document https://netflix.github.io/dispatch/docs/administration/settings/plugins/configuring-jira, there is a parameter on the update page of jira plugin named JIRA_HOSTING_TYPE,
> 
> <img width="662" alt="image" src="https://github.com/user-attachments/assets/7249e4a5-86e2-4eb7-b9d9-27cd79641542">
> 
>  however I can not found this parameter on my update page, Is there anything else I need to do to display this parameter?
> 
> 

The default value used is Cloud, but if you have an on prem deployment then you should use Server.

**Comment by tiankai0114** [comment]
> > Hi @mvilanova ，got your point, my jira is server deployment, according to document https://netflix.github.io/dispatch/docs/administration/settings/plugins/configuring-jira, there is a parameter on the update page of jira plugin named JIRA_HOSTING_TYPE,
> > <img alt="image" width="662" src="https://private-user-images.githubusercontent.com/52437130/369765808-7249e4a5-86e2-4eb7-b9d9-27cd79641542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDI2MjUsIm5iZiI6MTcyNzEwMjMyNSwicGF0aCI6Ii81MjQzNzEzMC8zNjk3NjU4MDgtNzI0OWU0YTUtODZlMi00ZWI3LWI5ZDktMjdjZDc5NjQxNTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE0Mzg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ODY0M2I1MmQ0MThhNDM1ZTQ2ODM0Yjk5ZTU4MjE0ZjliYTlhYTVkMGNlMTcxZmZkM2NlMDcxYTBlZjYzNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CM_seaHivdblTuPP7XTBSexYI5UtWzSEVx7e-Vw_jXo">
> > however I can not found this parameter on my update page, Is there anything else I need to do to display this parameter?
> 
> The default value used is Cloud, but if you have an on prem deployment then you should use Server.

I have an on prem deployment, however I can not found how set Jira type is Server, this is the whole parameters of jira plugin what i saw, can not found how to set use jira as Server
![image](https://github.com/user-attachments/assets/0c534430-a98e-4f5b-bfe7-7ec24281212d)

**Comment by tiankai0114** [comment]
Hi @mvilanova , do you know how to set use jira as Server, it seems do not have such parameter on jira plugin on UI, thanks.

**Comment by mvilanova** [comment]
> Hi @mvilanova , do you know how to set use jira as Server, it seems do not have such parameter on jira plugin on UI, thanks.

I see... This appears to be a bug in the UI. There should be a field for hosting type in the plugin configuration settings. Cc @whitdog47
