### ISSUE TITLE
Alternate database backend support (ex: MySQL)?

### ISSUE THREAD

**Issue by bored-engineer** [Netflix/dispatch#528]
The docs seem to indicate a PostgreSQL DB is required, however (at first glance) most of the codebase seems to be using SQLAlchemy which can be backend agnostic. 

Are there any specific datatypes or features that are actually Postgres specific? Are you aware of anyone using dispatch with an alternate DB?

**Comment by bored-engineer** [comment]
To answer my own question partially (would still love an official answer), the usage of TSVectorType is PostgreSQL specific

**Comment by kevgliss** [comment]
Yes, we do use some PostgreSQL specific functionality. I don't know of anyone using a non-postgres database for Dispatch.
