### ISSUE TITLE
Office 365 support

### ISSUE THREAD

**Issue by r1ckyb0nd** [Netflix/dispatch#529]
Is it possible to replace Gsuite with Office 365? 
Is Gsuite only used for document storage?

**Comment by kevgliss** [comment]
It is possible to switch out GSuite with Office356, we use GSuite for a variety of things:

- Document Storage (Google Docs)
- Artifact Storage (Google Drive)
- Permissions (Google Groups)
- Video Conference (Google Meet)

Each of the above has its own plugin, such that new services can be integrated. Additionally, as of #507 you _should_ be able to pick and choose which plugin types you want to use. 

We are open to plugin contributions but have no plans to create any Office 365 plugins ourselves.
