### ISSUE TITLE
Error creating documentation PDF with gitbook cli

### ISSUE THREAD

**Issue by francbartoli** [Netflix/dispatch#533]
**Describe the bug**
A pdf version of the docs cannot be created due to an error:

```bash
error: error while generating page "docs/upgrading.md":

Template render error: (/Users/geobart/code/dispatch/docs/upgrading.md) [Line 8, Column 2]
  unknown block tag: hint
```

**To Reproduce**
1. Install gitbook cli: `npm install -g gitbook-cli`
2. Clone the repo
3. Run the pdf generation: `gitbook pdf .`

**Expected behavior**
A pdf version of the docs is generated.

**Screenshots**

**Desktop (please complete the following information):**
 - npm version: 6.14.6

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mvilanova** [comment]
The gitbook CLI is no longer supported (see deprecation warning in https://github.com/GitbookIO/gitbook). You can access the docs [here](https://hawkins.gitbook.io/dispatch/).
