### ISSUE TITLE
Question: Every incident creates a new Google shared drive

### ISSUE THREAD

**Issue by tomarv2** [Netflix/dispatch#534]
Hi,

I have a version of dispatch which I think is 2-3 months old. It has been running great. New some assistance on two things:

Everytime there is an incident it creates a new Google shared drive and I have to manually add new users to it. I want to see if this is right. Is it possible to create one shared drive and every new Incident gets dropped into it? 

Also, we have Slack integration but Slack commands don't work because they are not able to connect to dispatch because of AWS security groups that dont allow traffic from Slack as Slack does not provide an IP address. Any ideas on how to address it.

**Comment by kevgliss** [comment]
Hi @tomarv2,

> every time there is an incident it creates a new Google shared drive and I have to manually add new users to it.

The latest versions of Dispatch support this but you have to be in a Google Drive beta (not sure if it's GA yet). See [here](https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-g-suite#enable-required-apis). Also note that with this change we have added a new envvar that will need to be set [INCIDENT_STORAGE_FOLDER_ID](https://hawkins.gitbook.io/dispatch/configuration/app#incident_storage_folder_id), this would be the top-level folder that will hold all incident artifacts (in one google drive). 

> Also, we have Slack integration but Slack commands don't work because they are not able to connect to dispatch because of AWS security groups that don't allow traffic from Slack as Slack does not provide an IP address. Any ideas on how to address it.

This is a bit tricky, slack commands require a publically accessible endpoint. We have the luxury of a robust internal proxy that we can use to proxy requests from slack to our app (without exposing dispatch APIs). You may be able to use something like (https://github.com/amancevice/slackend) for this (full disclosure I have not used this library).
