### ISSUE TITLE
Netflix Dispatch Slack Integration Query

### ISSUE THREAD

**Issue by mccannm1** [Netflix/dispatch#538]
Hi @mvilanova 

Just a short question on the Slack Integration for Dispatch. 
This is the procedure that we are required to follow:
- https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-slack

I have dispatch installed and started on Ubuntu on a machine:  e.g  server1.aaa.bbb.com
and a HAProxy put in front of it. It is configured to support a secure connection using SSL.
- so dispatch renders at:  https://server1.aaa.bbb.com/dashboard/incidents   thats fine

My question is regarding the API endpoints or the Request URLs as they are called in the Slack 
application I create to subscribe to event notifications :

**Q. Based on the above are these examples of the correct Request URLs or URL endpoints that should be defined in the 
Slack app where Dispatch receives information from Slack?**

- Events API to receive events for the event types the app is subscribed to
https://server1.aaa.bbb.com/api/v1/events/slack/event   

- API endpoints for slash (/) commands and interactive components like dialogs and modals
https://server1.aaa.bbb.com/api/v1/events/slack/command
https://server1.aaa.bbb.com/api/v1/events/slack/action

**Comment by mvilanova** [comment]
Yes, all the example URLs you provided are correct. Let me know if something is not clear when you're reading the docs.

**Comment by mccannm1** [comment]
Last question  curl -I https://server1.aaa.bbb.com/api/v1/events/slack/event
what will the application return from this ?

**Comment by mvilanova** [comment]
This endpoint will return an HTTP 200 with an `ok` in the message body, if the timestamp and signature in the request headers is valid. You can found the code [here](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_slack/views.py#L77).

**Comment by mccannm1** [comment]
Thank you @mvilanova 
Closing.
