### ISSUE TITLE
Netflix Dispatch RTM API compatability for Slack integration

### ISSUE THREAD

**Issue by mccannm1** [Netflix/dispatch#543]
Hello
This is a short question. I am working on the Slack Integration defining the Events Subscriptions as per procedure:
https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-slack 

There is a Request URL that is required to be specified and according to the document the endpoiunt does need to be a public URL where Slack can send HTTP post requests, i.e. publicly accessible.

I however had installed dispatch on an internal corporate network virtual machine.

I was informed by Slack support that If I am not able to use a publicly accessible URL, then the alternative is to use 
the RTM API instead of the Events API. 
Folks who are looking for Events API-like functionality but are restricted by corporate firewalls often use the RTM API instead, described here https://api.slack.com/rtm

**_Question_**: Is the RTM API compatible with Dispatch for this integration purpose?

Thank you

**Comment by kevgliss** [comment]
RTM API is not currently implemented in Dispatch. Additionally, the RTM API also has some limitations regarding slack dialogs and interactivity which Dispatch uses heavily.

If you don't want to expose the Dispatch API directly you could look into proxying the traffic. For instance, we have an organization-wide proxy that handles all of our slack traffic. Unfortunately, this is organization specific.

**Comment by mccannm1** [comment]
Thank you @kevgliss 
A final question please.  I have installed Dispatch on a VM inside my corporate network (company A)
Currently working on integrating Slack/PagerDuty

1. Slack cannot reach the VM (endpoints) as it is internal, and I have been informed that it is not possible to 
    proxy traffic to that VM because the VM that I would be proxying traffic to has full access to the internal network, 
    which means that the proxy will create a security exposure for the company.
2. The main integrations Dispatch uses as far as I can see that are sufficient for our needs are Slack and PagerDuty
     PagerDuty is external application 
3. Dispatch you have informed me doesn't support SAML (but PKCE) so therefore no use for company A's IDP

So is there actually anything that Dispatch would have to have access to inside  company A's internal network? It seems not?   Do users of Dispatch install it on external VMs? machines?   I can't proxy the traffic for security compliance reasons..  
Please comment on the above and we can then close

**Comment by mccannm1** [comment]
Company A's users can login to things outside of Company A of course

**Comment by mccannm1** [comment]
@kevgliss I understand this may be a question more related to the environment setup that specific individual bugs/fixes.
Apologies for that, just hit this sticking point..
After your response I will close the case

**Comment by kevgliss** [comment]
It's really a limitation of how Slack works. Slack requires an endpoint available to it in order to send events. 

Some things to consider:
- Allowing the endpoint to be publically routable but only accessible from Slack IPs
- Limiting the access the VM has to the internal network unless you are using custom plugins; most of the functionality uses external resources (e.g. pagerduty) and would not need access to the internal network.

In general, I would recommend both of the above be in place regardless of the application I was deploying.

**Comment by mccannm1** [comment]
Thank you @kevgliss

**Comment by mccannm1** [comment]
@kevgliss 
Do the endpoints have to be on specific ports?  (443 SSL)

https://<appserver.domain.com>/api/v1/events/slack/event (receive events in Slack, e.g. member joined/left channel)
https://<appserver.domain.com>/api/v1/events/slack/command (enable Dispatch's slash commands)
https://<appserver.domain.com>/api/v1/events/slack/action (generate interactive components such as dialogs and modals

**Comment by kevgliss** [comment]
If you are using an https endpoint then 443 is the default. Slack might require https but I'm not sure.

**Comment by mccannm1** [comment]
Thanks @kevgliss
