### ISSUE TITLE
ERROR: Error loading ASGI app. Could not import module "main"

### ISSUE THREAD

**Issue by AliceLoeser** [Netflix/dispatch#56]
Hello,

I managed to go through the whole `docker-dispatch/install.sh` installation script, but I have the following issue when starting the containers:

```
Error: Missing argument "APP".
```

I tried to clone `dispatch` locally to make some changes and put an `APP` value, but I'm not sure what the value should be. I tried with `main` but got `ERROR:    Error loading ASGI app. Could not import module "main".`. 

I feel restricted by my lack of python knowledge, hope you can help!

**Comment by TheDahv** [comment]
Try this https://github.com/Netflix/dispatch/pull/54
