### ISSUE TITLE
Request for sample google templates - documentation update

### ISSUE THREAD

**Issue by alexa-kelley-vim** [Netflix/dispatch#579]
**Is your feature request related to a problem? Please describe.**
There are multiple references within the code that point to google docs templates, but there seems to be little indication on the expected structure/syntax that the code will work best with. 

**Describe the solution you'd like**
Can you provide a sanitized version or example document of the expected template structure? Or alternatively document the syntax that is expected? 

**Describe alternatives you've considered**
I've considered trying to RE the source and determine the expected syntax through that, but I am limited on time and resources and wanted to check first here before taking on such an undertaking.

**Additional context**
Files referencing templates include dispatch-sample-data.dump, config.py, service.py, and so on.

**Comment by kevgliss** [comment]
Yes, we had been planning to do a blog post regarding these templates but ran out of time this quarter.

Here is a list of reference documents that can be copied and used. We typically have a document for each incident type that is the generic template but with questions pertaining to the specific incident type.

I will also add a task to document the variables available to documents. 

Incident Document:
https://docs.google.com/document/d/1fv--CrGpWJJ4nyPR0N0hq4JchHJPuqsXN4azE9CGQiE

Incident Review Document:
https://docs.google.com/document/d/1-VwcEpVVdymoojdUg9e5XP8QGam0-B5Djxh-guuPpEc

Executive Report:
https://docs.google.com/document/d/1dab6k14p5ageo5B_d1YlB_zS9hMGHDMXy9RUbIZous4

**Comment by alexa-kelley-vim** [comment]
Wonderful! Thank you very much for the swift response! I look forward to incorporating these. 

@kevgliss By chance do you have a similar reference for the investigation sheet template?

**Comment by kevgliss** [comment]
We do, although at least in our experience this doesn't get used quite as much (so it doesn't really have any interesting templating abilities).

Incident Tracking Sheet:
https://docs.google.com/spreadsheets/d/1Odk4KlL7uMF_yd7OvTOCaPWmtTA_WzFBIA4lMeU5cGY

**Comment by alexa-kelley-vim** [comment]
Thank you again :)

**Comment by kevgliss** [comment]
No problem, we also have internal documents for Incident FAQs and Incident Command Reference cheatsheet. These are not templated and have some internal nflx-isms in them. If there is interest, I can clean them and release them as well.

**Comment by alexa-kelley-vim** [comment]
Sure, that wouldn't hurt to have as well. I appreciate you being willing to share. :)

**Comment by kevgliss** [comment]
Cool, will put that on the todo.
