### ISSUE TITLE
Feature: Discord Bot Integration Plugin

### ISSUE THREAD

**Issue by grplyler** [Netflix/dispatch#586]
Hi There! For my Hacktoberfest 2020 contribution, I would like to suggest a Discord Bot Integration Plugin and
offer myself to develop it.

**Rationale**

With Discord's recent marketing strategy shift from being geared towards gamers to opening up their platform to communities of all types, Discord has seen a fairly large boost in usage. I use it for team communication and collaboration, even in a professional setting. I personally use discord bots for various security and system monitoring use cases. Adding Discord Bot integration to Netflix's `dispatch` would open the tool up to a wider community of users, and enhance it's integration capabilities.

**Scope**

The new feature would create a Discord Bot plugin to integrate with Discord's simple bot API.
The plugin would _NOT_ be the creation of an official Netflix Dispatch Bot. Instead, the plugin would accept
discord bot access tokens to be able to authenticate as a bot that a user created.

**Why me?**

I have experience with implementing Discord bots in other languages (NodeJS) for system administration, services monitoring, and security monitoring purposes and that experience should apply to this case quite well.

**Why Netflix Open Source?**

As a participant in Hacktoberfest 2020, I was searching around for projects to contribute to. Many issues are simple to code "code for the heck of it", I prefer to "code for a purpose" even though I still like coding for the heck of it. So basically, I wanted to contribute to something of meaning. I also have done some research on Netflix's microservices architecture and really admire it and the challenges they face to build an awesome system and a great product.

**Conclusion**

If this sounds like a worthy contribution, I would love to be assigned the issue by a project manager for Hacktoberfest 2020! 
Thank you!

**Comment by mvilanova** [comment]
Hi @grplyler, thanks for reaching out. Sounds like an interesting idea. Can you elaborate a little bit more and provide a few examples on how the the plugin would enhance the Incident Commander and participant's experience during an incident and if you foresee any conflicts with the current features that Dispatch and its Slack plugin provides?

**Comment by grplyler** [comment]
Hi @mvilanova ! Certainly. Give me a day or so to read the code and to provide those examples. At this point I can't see how it would conflict if the plugin architecture is truely plugable. And to answer your other question, this would merely add a Discord Bot plugin as a _option_ for notification of incidents. So as I see it, yes it could be an alternative to Slack, or used into addition to Slack in a priority message queue fashion. E.g., Dispatch looks at the list of configured notifiers and dispatches the announcement through each integration, one at a time. 

To confirm that exsisting code would support that, give me a day or so and I will get back to you with more detailed answers after I've had a chance to read the code. Thanks!

**Comment by mvilanova** [comment]
Sounds good. There might be a few Dispatch features that are tightly coupled with the Slack plugin code, but nothing we can't fix with some refactoring.

**Comment by forestmonster** [comment]
Hi @grplyler , I think this is a great idea. I see that you're considering it as a _notification_ plugin. Would you please give some thought to your Discord bot as a _chatops_ plugin as well, or would you consider that too much work for the limited Hacktoberfest "four pull requests" scope? Within Slack channels to which it is added, Dispatch offers a number of capabilities through Slack's [slash commands](https://api.slack.com/legacy/custom-integrations/slash-commands). A Discord [app](https://discord.com/developers/docs/intro#bots-and-apps) could do the same, couldn't it? Of course as you can tell we'd be happy to receive your contribution.

**Comment by mvilanova** [comment]
You can find more information about the functionality that the Slack plugin provides [here](https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-slack).

**Comment by grplyler** [comment]
Thank you @forestmonster and @mvilanova. To answer your question, I have done some preliminary research by reading some of the plugin code, getting a handle on the plugin architecture, and reading the documentation on contributing, specifically the difference interfaces I can implement.

After reading some of the code for the slack plugin, I see there is quite a heavy integration with slack. In short, yes. Discord would be able to do all of that and support command and control, real-time notification, etc. But after doing some research, that might not be a top priority at this time, even though it would be a cool enhancement to support discord fully in the future as a _chatops_ plugin. 

For the time being, I think this feature would be more along the lines of a _Notification_ plugin, or even and method to notify _OnCall_ personnel.

After I setup a dev environment for dispatch, play around with it, and understand its plugin internals, I'll be able to speak more to the scope and particular use cases and examples where this feature could be handle. I will most likely not pursue other smaller projects for Hacktoberfest and contribute here instead. I will also look at the other outstanding issues to see if I can contribute there as well.

Thank you for your support! I think it's a cool project, and its nice to be contributing on a project by a company with and household name.  I am current a senior in college, but I'll contribute what time and effort I can!

PS. I also love VueJS and use that for several other things, so I was happy to see that's what's used for the UI!

**Comment by mvilanova** [comment]
@grplyler are you still interested in submitting a PR or should we close it?

**Comment by grplyler** [comment]
I think we should just close it for now. I've had some life things come up.
Thank you for reaching out!

-Ryan

**Comment by mvilanova** [comment]
Yes of course!

**Comment by mvilanova** [comment]
Sounds good. Let me know if you have any questions.
