### ISSUE TITLE
Unusual python errors

### ISSUE THREAD

**Issue by alexa-kelley-vim** [Netflix/dispatch#588]
**Describe the bug**
After loading a clean copy of dispatch for testing and development I have noticed new errors in the log associated to 'httpcore'. I have attempted multiple variations to resolve this and it appears to be an issue with the code requirements itself and not my configuration. 

Here is a highlighted section for example. 

`web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
web_1        |     plugin = ep.load()
web_1        |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2444, in load
web_1        |     self.require(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2467, in require
web_1        |     items = working_set.resolve(reqs, env, installer, extras=self.extras)
web_1        |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
web_1        |     raise VersionConflict(dist, req).with_context(dependent_req)
web_1        | pkg_resources.ContextualVersionConflict: (h11 0.10.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('h11<0.10,>=0.8'), {'httpcore'})
web_1        | 
web_1        | ERROR:dispatch.common.utils.cli:Failed to load plugin dispatch_contact:Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
web_1        |     plugin = ep.load()
web_1        |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2444, in load
web_1        |     self.require(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2467, in require
web_1        |     items = working_set.resolve(reqs, env, installer, extras=self.extras)
web_1        |   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
web_1        |     raise VersionConflict(dist, req).with_context(dependent_req)
web_1        | pkg_resources.ContextualVersionConflict: (h11 0.10.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('h11<0.10,>=0.8'), {'httpcore'})`

**To Reproduce**
1. Errors happen as fresh install. Follow stock instructions for install. 

**Expected behavior**
Python plugins to not be causing errors. 

**Screenshots**
I have included a copy of the log for example.
[log.txt](https://github.com/Netflix/dispatch/files/5314025/log.txt)

**Comment by kevgliss** [comment]
Did you recreate a new virtualenv as well? I've seen this before when re-installing various versions into the same virtualenv, I would try and run `pip check` for an indication which dependency is causing the conflict.

**Comment by alexa-kelley-vim** [comment]
I would imagine it is a new virtualenv as it's a fresh docker container+image+volume installed through the ./install.sh script. However I'll connect to the web image and see if I can verify that.

**Comment by alexa-kelley-vim** [comment]
so I connected via  `sudo docker exec -it <web-container-hash> /bin/bash`

then I ran `pip check` at root. Result was
`httpcore 0.11.1 has requirement h11<0.10,>=0.8, but you have h11 0.10.0.`

**Comment by kevgliss** [comment]
Okay, this likely means that some other dependency wants `h11 >= 0.10.0` let me see if I can find it.

**Comment by kevgliss** [comment]
It looks like uvicorn is the issue: https://github.com/encode/uvicorn/releases/tag/0.12.1

**Comment by kevgliss** [comment]
If you can force the image to pin to: `pip install uvicorn==0.11.8 ` to confirm I will create a hotfix with that pinned.

**Comment by alexa-kelley-vim** [comment]
Sounds good, I'll give it a try now

**Comment by alexa-kelley-vim** [comment]
at a glance it's resolved the errors I was referencing. Here is a dump of the log. As a note this is a stock/empty install so the Zoom & OPSGENIE errors are to be expected. I have not yet tested the frontend, but will confirm that as well shortly. 


------

> 
> 
> pip install uvicorn==0.11.8
> Collecting uvicorn==0.11.8
>   Downloading uvicorn-0.11.8-py3-none-any.whl (43 kB)
>      |████████████████████████████████| 43 kB 996 kB/s 
> Collecting websockets==8.*
>   Downloading websockets-8.1-cp38-cp38-manylinux2010_x86_64.whl (78 kB)
>      |████████████████████████████████| 78 kB 6.3 MB/s 
> Requirement already satisfied: click==7.* in /usr/local/lib/python3.8/site-packages (from uvicorn==0.11.8) (7.1.2)
> Collecting uvloop>=0.14.0; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy"
>   Downloading uvloop-0.14.0-cp38-cp38-manylinux2010_x86_64.whl (4.7 MB)
>      |████████████████████████████████| 4.7 MB 21.0 MB/s 
> Collecting h11<0.10,>=0.8
>   Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
>      |████████████████████████████████| 53 kB 22.8 MB/s 
> Collecting httptools==0.1.*; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy"
>   Downloading httptools-0.1.1-cp38-cp38-manylinux1_x86_64.whl (227 kB)
>      |████████████████████████████████| 227 kB 35.0 MB/s 
> Installing collected packages: websockets, uvloop, h11, httptools, uvicorn
>   Attempting uninstall: h11
>     Found existing installation: h11 0.10.0
>     Uninstalling h11-0.10.0:
>       Successfully uninstalled h11-0.10.0
>   Attempting uninstall: uvicorn
>     Found existing installation: uvicorn 0.12.1
>     Uninstalling uvicorn-0.12.1:
>       Successfully uninstalled uvicorn-0.12.1
> Successfully installed h11-0.9.0 httptools-0.1.1 uvicorn-0.11.8 uvloop-0.14.0 websockets-8.1
> root@shell:/# dispatch
> No metric providers specified metrics will not be sent.
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: dispatch_basic_auth
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: dispatch_contact
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: dispatch_document_resolver
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: dispatch_participant_resolver
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: dispatch_pkce_auth
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: dispatch_ticket
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: google_calendar_conference
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: google_docs_document
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: google_drive_storage
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: google_drive_task
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: google_gmail_email
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: google_groups_participants
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: jira_ticket
> ERROR:dispatch.common.utils.cli:Failed to load plugin opsgenie_oncall:Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
>     plugin = ep.load()
>   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2445, in load
>     return self.resolve()
>   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2451, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/plugin.py", line 11, in <module>
>     from .service import get_oncall, page_oncall
>   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/service.py", line 4, in <module>
>     from .config import OPSGENIE_API_KEY, OPSGENIE_TEAM_ID
>   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_opsgenie/config.py", line 4, in <module>
>     OPSGENIE_API_KEY = config("OPSGENIE_API_KEY", cast=Secret)
>   File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
>     return self.get(key, cast, default)
>   File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
>     raise KeyError(f"Config '{key}' is missing, and has no default.")
> KeyError: "Config 'OPSGENIE_API_KEY' is missing, and has no default."
> 
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: pagerduty_oncall
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: slack_contact
> ERROR:dispatch.common.utils.cli:Successfully loaded plugin: slack_conversation
> ERROR:dispatch.common.utils.cli:Failed to load plugin zoom_conference:Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 29, in install_plugins
>     plugin = ep.load()
>   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2445, in load
>     return self.resolve()
>   File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2451, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_zoom/plugin.py", line 16, in <module>
>     from .config import ZOOM_API_USER_ID, ZOOM_API_KEY, ZOOM_API_SECRET
>   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_zoom/config.py", line 4, in <module>
>     ZOOM_API_USER_ID = config("ZOOM_API_USER_ID")
>   File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
>     return self.get(key, cast, default)
>   File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
>     raise KeyError(f"Config '{key}' is missing, and has no default.")
> KeyError: "Config 'ZOOM_API_USER_ID' is missing, and has no default."
> 
> Usage: dispatch [OPTIONS] COMMAND [ARGS]...
> 
>   Command-line interface to Dispatch.
> 
> Options:
>   --version  Show the version and exit.
>   --help     Show this message and exit.
> 
> Commands:
>   database   Container for all dispatch database commands.
>   plugins    All commands for plugin manipulation.
>   scheduler  Container for all dispatch scheduler commands.
>   server     Container for all dispatch server commands.
> root@shell:/#

**Comment by alexa-kelley-vim** [comment]
I can't say for 100% that there's no bugs, but I'm not seeing anything outright broken. I think it's good to go. 

(Sorry on the delay had to spin up a clean test instance against updating the requirements to be sure)

**Comment by kevgliss** [comment]
The latest release has this change and I have bumped the tag in dispatch-docker https://github.com/Netflix/dispatch-docker/pull/72

Let me know if you run into any other issues.

**Comment by alexa-kelley-vim** [comment]
Thank you very much. I'll keep an eye out for any other issues.

**Comment by nedvna** [comment]
Can confirm I had the described bug as well and updating helped.
