### ISSUE TITLE
Can't properly use default set of plugins

### ISSUE THREAD

**Issue by nedvna** [Netflix/dispatch#594]
**Describe the bug**
After I set up the basic minimalistic install of Dispatch, I can't actually use it.
All the plug ins are enabled by default.
When you try to create the incident (after creating a document, service, service type, priority and an individual), the application fails to do so. You can't see your incidents in the incident list (/incidents).

**To Reproduce**
1. Set up basic .env - change only DISPATCH_UI_URL, DISPATCH_HELP_EMAIL. SECRET_KEY and DISPATCH_JWT_SECRET will be replaced automatically. Other fields are left 'as is', AFAIK.
2. Run ./install.sh
2. docker-compose up -d
3. Register (and auto-login) with basic auth
4. Create the incident (and all its prerequisites before)
5. Observe the trace in logs and not-working GUI

**Expected behavior**
Incident is created successfully, and can be viewed in the incidents list.
Or maybe an error message stating 'you can not use multiple plugins of type X!' of some kind.

**Additional context**
What we have here is that Dispatch doesn't quite work 'out of the box'. It took quite some time to find a workaround.
Obviously, the described setup is a 'bare bones' one, only useful for demonstrational purposes / some basic testing. But, well, that was what I was trying to achieve before I try to set up plugins etc. Unfortunately, that doesn't work. According to database data, the incident is created but you can't view it.
What worked was - disabling all plugins before creating anything in the UI, except for dispatch-* ones.
Also, even though it worked, the UI is kind of unresponsive. I mean, it looks like the incident is being created forever. I have to switch to another tab from the side pane, and the back to 'Incidents'. Then I can see and access my incident.
Can't create tasks though, but that should be another bug report.
(edited) If after the failed creation, I disable the plugins, restart docker-compose and then try to create another incident, I still can't view the list. I guess some info gets halfway-written there, and fetching the incidents from DB is broken.

Trace examples:
[trace_examples.log](https://github.com/Netflix/dispatch/files/5327772/trace_examples.log)

**Comment by nedvna** [comment]
> I will take a look, did you happen to install the example data? Or was this just based on an empty database?

It was an empty database, I only added my data.
I'll try to populate with data from [here](https://raw.githubusercontent.com/Netflix/dispatch/master/data/dispatch-sample-data.dump) a bit later but I doubt it's going to help, might have also done that in the past.

**Comment by nedvna** [comment]
So I dropped the database and loaded data from dump.
jira-ticket and slack-contact are conveniently disabled there, but now I also get error 401 from pagerduty-oncall (which is not configured) on incident creation.
If I drop database, load the dump, disable plugins except for dispatch-*, and then create incident, it goes more or less OK, same as with the workaround I described earlier.

**Comment by kevgliss** [comment]
Thanks for reporting these issues, I've put together #597 which I hope will address _most_ of the issues you're experiencing. Admittedly, we do _use_ plugins so testing without any plugins enabled is not as great as it could be. Hopefully we can work through issues as we find them.

**Comment by nedvna** [comment]
@kevgliss , many thanks!
It's got much better.
I reinstalled from scratch, enabled dispatch-* plugins.
Now I can create the incident without UI hangs or error traces.
I can also create a task, with a trace, but it does work!

**Comment by kevgliss** [comment]
Ah that's good to hear, #606 should fix that other stack trace. Let us know if you find anything else and we'll get them fixed.

**Comment by nedvna** [comment]
@kevgliss , thank you, tested it, now it's a bit different.
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 37, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 1034, in incident_add_or_reactivate_participant_flow
    add_participant_to_conversation(user_email, incident_id, db_session)
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 369, in add_participant_to_conversation
    plugin.instance.add(incident.conversation.channel_id, [participant_email])`

Failure of the same nature, when I applied fix like you in #606 to line 369 in incident/flows.py, it was fixed, and no other traces appeared.
