### ISSUE TITLE
Trace when editing an incident

### ISSUE THREAD

**Issue by nedvna** [Netflix/dispatch#607]
**Describe the bug**
Getting an error message to console when editing an existing incident in UI

**To Reproduce**
1. Set up Dispatch with minimal set of plugins (basic auth + dispatch-* ones), master branch (latest)
2. Create a document, service etc, then finally an incident
3. Edit that incident, for example its description, click the save icon
4. Get the error (the changes are saved and applied, though, so it's ok)

**Expected behavior**
Changes are applied, no errors occur

**Additional context**
[edit_incident.log](https://github.com/Netflix/dispatch/files/5357266/edit_incident.log)
I have only one user registered - I log in as it.
Also I have two Individuals - one is that user (created automatically, it seems; has the same name as its email), and the one I create manually. The two have different email addresses, if that matters. I try specifying the 'manual' user for the incident, fill in the fields, except for the last threee (terms, tags, duplicates), nothing special.

Oh! And found a related thing, maybe, while writing this. I put the one created manually as the reporter and commander, and have my log-in user put as reporter and commander instead. Can't change to the other user, getting the same trace.

**Comment by kevgliss** [comment]
Looks like we didn't pass a var to the dispatch core contact plugin. #608 should resolve this once it gets reviewed and merged. Thanks for reporting!

**Comment by nedvna** [comment]
Thanks! Yes, now it works properly
