### ISSUE TITLE
Add Initial "Create" Migration

### ISSUE THREAD

**Issue by TheDahv** [Netflix/dispatch#66]
I'm concerned I'm missing something, but I cannot successfully run the `database upgrade` command.

It is able to successfully run migration `e75e103693f2`: https://github.com/Netflix/dispatch/blob/develop/src/dispatch/alembic/versions/e75e103693f2_.py

However, this appears to not do anything.

Then the migration tries to run `d0501fc6be89`: https://github.com/Netflix/dispatch/blob/develop/src/dispatch/alembic/versions/d0501fc6be89_.py

In my environment, that fails with:

```
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "application" does not exist

[SQL: ALTER TABLE application ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE]
(Background on this error at: http://sqlalche.me/e/f405)
```

That's pretty consistent with the initial migration not actually creating any tables. I can verify that with Postgres that my database is indeed empty:

```
$ echo '\d' | dc exec -T postgres psql -U dispatch dispatch                                                                                          

              List of relations
 Schema |      Name       | Type  |  Owner   
--------+-----------------+-------+----------
 public | alembic_version | table | dispatch
(1 row)
```

Is there something I need to do to create the initial schema?

**Comment by kevgliss** [comment]
If it's a new database, I would run `database init` instead of `database upgrade`. I think we can make the database upgrade command smart enough to detect the lack of a database (and run init instead).

**Comment by TheDahv** [comment]
That was it! Here's what I had to do to get things up and running:

```
$ docker-compose stop web dispatch-scheduler # Disconnect any clients
$ echo 'drop database dispatch' | docker-compose exec -T postgres psql -U dispatch postgres # booting the postgres container creates an empty database
$ docker-compose run --rm web dispatch database init # set up initial schema
$ docker-compose run --rm web dispatch database update # migrate everything
```

**Comment by kevgliss** [comment]
Nice, to be clear you don't need to run `upgrade` after `init` for new databases. As it doesn't really make sense to run a migration as all the tables are created correctly in the first place.
