### ISSUE TITLE
Slack Integration API Migration

### ISSUE THREAD

**Issue by alexa-kelley-vim** [Netflix/dispatch#673]
**Describe the bug**
An upcoming change from slack will likely break current integration as its configured. I am opening this issue for the sake of tracking this concern. Listing as bug because it will break the slack integration after it goes live. 

**Reference articles:**
https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api#prepare 
https://api.slack.com/changelog/2020-09-15-events-api-truncate-authed-users#how.

At a glance I am noticing at least these API calls will be impacted:
channels:read
groups:history
groups:read
groups:write
im:history
im:read
im:write
mpim:history
mpim:read
mpim:write

I recommend an adjustment of the plugin in preparation for this change from slack.

**Comment by mvilanova** [comment]
Hi @alexa-kelley-vim,

Slack notified us about the upcoming changes and we determined that none of them will impact us. We don't use any of the methods listed [here](https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api#methods) in the plugin service [module](https://github.com/Netflix/dispatch/blob/master/src/dispatch/plugins/dispatch_slack/service.py), and we don't rely on `authed_users` or `authed_teams`.

Thanks for opening the issue and raising the concern!

**Comment by alexa-kelley-vim** [comment]
Hi @mvilanova,

Sorry for the delay in getting back to you. Thank you so much for the confirmation and glad to hear it should be fine. That answers my concerns on it rather thoroughly.

Would you like me to go ahead and close the issue or leave it open in case anyone else has questions?

**Comment by mvilanova** [comment]
@alexa-kelley-vim no worries. I'm going to close it. People can find it by searching through the closed issues. Thanks
