### ISSUE TITLE
Is there an alternative to using domain-wide delegation? How is this secured?

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [Netflix/dispatch#677]
**Is your feature request related to a problem? Please describe.**
Domain-Wide delegation in GSuite seems like too much power. Do we need this in order to act on behalf of a single delegated account. Is there a way we can scope it down?

**Describe the solution you'd like**
Is it possible to replace this with OAuth 2.0 consent from a single account?

**Describe alternatives you've considered**
Not sure if any other alternatives exist

**Additional context**
Would [this](https://developers.google.com/identity/protocols/oauth2/service-account#authorizingrequests
) work as as opposed to [this](https://developers.google.com/admin-sdk/directory/v1/guides/delegation#delegate_domain-wide_authority_to_your_service_account)?

**Comment by kevgliss** [comment]
We think that is overly scoped as well, historically this level of access was needed to create google groups. 

Just recently (a few weeks ago) google has gone to GA with this: https://cloud.google.com/identity/docs/how-to/create-google-groups 

We have an internal ticket open to tackle this change (I don't think it will be a lot of work) and then we can finally get rid of that terrible permission. 

cc @mvilanova

**Comment by sfc-gh-pkommini** [comment]
Sounds good. Saw it on the [blog](https://workspaceupdates.googleblog.com/2020/08/use-service-accounts-google-groups-without-domain-wide-delegation.html) no too long ago and was hoping this was in the works.

It's awesome to hear that you have a plans for this! You can close the issue as this is good enough for me for now or keep it open for others to know that this is coming. Your choice really.

**Comment by kevgliss** [comment]
Cool, will start work on this soon and link this issue to the PR when I have one.
