### ISSUE TITLE
Minimum set of required plugins to be configured

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [Netflix/dispatch#684]
**Is your feature request related to a problem? Please describe.**
We don't find the need to have pager duty part of our incident flow, is there a way to disable it?

**Describe the solution you'd like**
Some way to recognize the absence of config variables as a way to disable a specific plugin.

**Describe alternatives you've considered**
I'll try and set it up regardless of our requirement. However, I wanted to check if we have a way to disable specific plugins and what is the set of plugins you consider integral to the incident management flow.

**Additional context**
As of now I get an error message when I try to leave the two configs for pagerDuty empty

**Comment by kevgliss** [comment]
All plugins are optional, you can disable or enable them via the Plugins page in the Dispatch UI.

**Comment by sfc-gh-pkommini** [comment]
So can I remove the pagerduty configs from the .env file all together?

**Comment by kevgliss** [comment]
Yes, if don't use the plugins it should be fine to not have any of the variables (it will just issue a warning). We don't currently have a way to say if var-foo doesn't exist disable that plugin, we could add that relatively trivially but it doesn't exist atm.

**Comment by sfc-gh-pkommini** [comment]
Sounds good! I'm just going to remove the plugin variables from the .env file and proceed with the setup.
