### ISSUE TITLE
Include a Mattermost chat communication plugin

### ISSUE THREAD

**Issue by elyscape** [Netflix/dispatch#71]
[Mattermost] is an on-prem workplace chat solution that is very similar to Slack. It would be nice if Dispatch had support for it as well.

This request relies on #55 and would likely require refactoring the codebase to have a common internal interface, implemented by both the Slack and Mattermost plugins, for chat systems.

[Mattermost]: https://mattermost.com/

**Comment by ShakataGaNai** [comment]
Perhaps "Support for Mattermost chat". The current title ("instead") implies ripping out Slack support which wouldn't make sense since it's popular and already supported.

**Comment by mvilanova** [comment]
@elyscape that looks like a cool open source replacement for Slack. We don't use Mattermost at Netflix, so motivation for writing a plugin for it is low on our side. That being said, if you want to give it a try, we're happy to guide you through the process and review your PR.

**Comment by elyscape** [comment]
> @elyscape that looks like a cool open source replacement for Slack. We don't use Mattermost at Netflix, so motivation for writing a plugin for it is low on our side. That being said, if you want to give it a try, we're happy to guide you through the process and review your PR.

I’m absolutely open to contributing on this, though there are some infrastructural dependencies that need to happen first (primarily #55).

**Comment by kevgliss** [comment]
@elyscape I don't think that #55 would block the creation of a mattermost plugin, that issue is more around how plugins are enable/disabled than how plugins are written. That being said, there are a few slackisms we have in our code base (that we are actively removing).

 I haven't looked to hard at matter most, does it provide app-like dialogs for users?

**Comment by procyclinsur** [comment]
> @elyscape I don't think that #55 would block the creation of a mattermost plugin, that issue is more around how plugins are enable/disabled than how plugins are written. That being said, there are a few slackisms we have in our code base (that we are actively removing).
> 
> I haven't looked to hard at matter most, does it provide app-like dialogs for users?

I also use Mattermost at work, integrated into many other platforms.

I am not sure what you mean by app-like dialog for users, but its interface is very nearly a clone of Slack, but open source.

**Comment by elyscape** [comment]
@kevgliss The reason I think #55 is probably a requirement for this is that, in deployments where Mattermost is used, Slack would not be used, and so that plugin would need to be inactive.

**Comment by kevgliss** [comment]
@elyscape today, you don't need to disable a plugin you would just specify your own. For example, you would change `INCIDENT_PLUGIN_CONVERSATION_SLUG=` to be `mattermost-conversation` instead of `slack-conversation` in your `.env`. 

#55 Is a request is for exposing that functionality via the UI.

**Comment by elyscape** [comment]
Aha! In that case, I’ll take a look when I have some time. I don’t know when that will be, so if anyone else wants to look into this then please feel free.
