### ISSUE TITLE
Incident CSV report feature not downloading file

### ISSUE THREAD

**Issue by mrthankyou** [Netflix/dispatch#712]
**Describe the bug**
When I click on the "Export" button to download a CSV of my Incidents, nothing happens.

**To Reproduce**
1. Go to the Incidents page. You should already have several incidents created.
2. Click on the blue "Export" button.
3. The export modal pops up.
4. Follow the steps till you reach the final step titled Preview.
5. Click on the blue "Export" button on the bottom left of the modal. A spinning icon appears in the button and the modal disappears.
6. Nothing happens nor do I see a CSV file downloaded.

**Expected behavior**
I expected to see my browser download a CSV file of my incidents.

**Screenshots**
![image](https://user-images.githubusercontent.com/52643283/101673185-d6afa100-3a24-11eb-8fa0-786102e29736.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7 
 - Browser: Tested on the latest Firefox and Safari browsers.

**Smartphone (please complete the following information):**
N/A

**Additional context**
I reviewed the console logs in both Firefox and Safari browsers and did not see any error printed during the entire testing process.

**Comment by kevgliss** [comment]
Do you see a network request to the API when you hit export?

**Comment by mrthankyou** [comment]
@kevgliss Currently away from the computer that has Dispatch installed on. Will reply with the answer sometime tonight. Thanks.

**Comment by mrthankyou** [comment]
Yes, I do.

```
"GET /api/v1/incidents/?itemsPerPage=-1&include[]=name&include[]=title&include[]=status&include[]=incident_type.name&include[]=incident_priority.name HTTP/1.1" 200 OK
```

**Comment by kevgliss** [comment]
So, I just tried this with firefox/chrome (don't have safari) and it worked ok. I did notice that your incident don't have a name. Could you not attempt to export that field and see if that helps matters? I wonder if some of the code is expecting a value and is having issues when there isn't one.

**Comment by mrthankyou** [comment]
I'll try this out and get back to you later tonight on what my debugging of different fields resulted in.

**Comment by mrthankyou** [comment]
I'm currently occupied with other tasks and may take longer than expected (early next week) before I can reply. Thank you for your patience.

**Comment by mrthankyou** [comment]
Update:

Removing the name from the export field worked! I successfully downloaded a CSV file. Looks like for some reason if a field is blank the CSV export feature breaks.

**Comment by kevgliss** [comment]
Okay, let me try to re-create that issue and see if I can fix it.

**Comment by kevgliss** [comment]
This should be fixed in the next release (probably not until next year). Thanks for reporting!
