### ISSUE TITLE
Incident Select Dropdown Not Displaying Incidents

### ISSUE THREAD

**Issue by mrthankyou** [Netflix/dispatch#726]
**Describe the bug**
When I create a Task in the New Task form, none of the existing incidents appear. 

**To Reproduce**
1. Create an Incident in the New Incident form or on the Report Incident page.
2. Create a Task by going to `http://localhost:8000/incidents/tasks` and creating a Task in the New Task form.
3. On the Incident Select dropdown begin typing in a word or character that was used inside one of the attributes of the Incident.
4. The Incident Select dropdown alerts that `No incidents matching " SQL injection". `.

**Expected behavior**
I should be seeing the incident in the Incident dropdown.

**Screenshots**
![Screen Shot 2020-12-17 at 3 01 30 PM](https://user-images.githubusercontent.com/52643283/102537295-c62ca580-4078-11eb-830a-60b711575b2d.png)

**Desktop (please complete the following information):**
Mac OS 10.14.6
Firefox 83.0

**Additional context**
I reviewed the network requests being sent as I type inside the Incident Select dropdown. Requests to `http://localhost:8000/api/v1/incidents/?q=<INPUT_HERE>` are successfully sent and received. I also see Incidents inside the response payloads.

What I think is happening (can be wrong) is that the Incident dropdown is displaying incident names but I don't think that attribute is set when I currently create an incident. Therefore none of the incidents are showing up. Also, in some cases I will see an incident appear in the dropdown but the selected item is blank.

**Comment by kevgliss** [comment]
Thanks for reporting this. It's a subtle bug that I didn't notice. You were close with your assessment, essentially the API searches on an incident's name, title, and description. However, when the objects are returned to the Vue component it's doing additional filtering. So we needed to add our own custom filter to search those same fields. 

This should be fixed in the next release.

**Comment by mrthankyou** [comment]
Thanks for the update!

**Comment by kevgliss** [comment]
On further thought, we want to display filtering on the client altogether. I also found a few more places that this would affect us that should be fixed in #729.
