### ISSUE TITLE
First Admin User 

### ISSUE THREAD

**Issue by gustavooliveira1979** [Netflix/dispatch#736]
After a new installation, it is possible to create a first user as a regular one, not as admin one, and so many configuration features stay locked. 

When browsing inside the tool, it is not possible to change the first user to a admin one (http://localhost:8000/configuration/users)

**Comment by kevgliss** [comment]
You're right, we recently switched from the default of new users being an `admin` to  `user`. For the "first admin problem," I've added a simple CLI command (#737) that will allow you to promote a given user to admin. 

Let me know if this works for you!

**Comment by mrthankyou** [comment]
I needed this as well since I accidentally deleted my local database and am starting from scratch. Thanks @kevgliss!

**Comment by nazmulapu** [comment]
@kevgliss Not working for me. Here is the error message: Error: No such command 'user'.
