### ISSUE TITLE
Dispatch development instance

### ISSUE THREAD

**Issue by tgrzinic** [Netflix/dispatch#76]
Hi,

I tried bringing up the the Dispatch development environment. 
The Vuejs part with `npm install serve`, and the FastAPI part with the `run.py` script after installing the dependecies in the virutalenv.

The problem is that I can not get the frontend working due to the  CORS errors, is there a simple way to disable Google OAuth authentication and to run the dispatch without it? I just want to evaluate the frontend part of Dispatch.

**Comment by kevgliss** [comment]
There is not currently a simple way to disable auth. But we do need this functionality for ourselves. I'll be taking a look at how to do so in the next week or so.

**Comment by kevgliss** [comment]
Hi @tgrzinic I've open #88 to help tackle this. 

Once merged you would enable `DISPATCH_HEADER_AUTH_ENABLED` both in the server .env and `VUE_APP_DISPATCH_PKCE_AUTH` in the frontend .env (located in `src/dispatch/static/dispatch`). This essentially tells dispatch to rely on whatever HTTP header specified by `DISPATCH_AUTH_HEADER_KEY` as the user identity. 

Most actions should work well enough (simple crud actions) but a few (creating an incident, will not work without a real identity).

**Comment by tgrzinic** [comment]
Thanks, I will try it tomorrow.

**Comment by gargrag** [comment]
Hi, is there any documentation about how to configure google auth for dispatch?

**Comment by mvilanova** [comment]
@gargrag you can find it here: https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-g-suite

**Comment by gargrag** [comment]
@mvilanova Thanks! I promess I will update the docs after this, but.... After I set all the google G suite configuration, how do I configure dispatch so that every user will login through google? Thanks!!!

**Comment by mvilanova** [comment]
@kevgliss can you answer @gargrag question above?

**Comment by kevgliss** [comment]
@gargrag the TLDR, is that Dispatch should work with any provider that supports the PKCE authentication flow. Unfortunately, this means there are multiple ways to accomplish your goal;

Depending on what is already available in your organization some possible options:
- https://developer.okta.com/blog/2019/08/22/okta-authjs-pkce
- https://www.oauth.com/oauth2-servers/signing-in-with-google/
- https://auth0.com/docs/flows/concepts/auth-code-pkce
