### ISSUE TITLE
General Questions: Slack Plugin

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [Netflix/dispatch#764]
Hi Team,

I was wondering if we get more details on what the following fields are used for in the slack plugin? I understand the fields 

```bash
SLACK_PROFILE_DEPARTMENT_FIELD_ID=""
SLACK_PROFILE_TEAM_FIELD_ID=""
SLACK_PROFILE_WEBLINK_FIELD_ID=""
```

Also, may I know what goes into the value this config variable?
```
SLACK_USER_ID_OVERRIDE=""
```
i.e. Would this be an email ID or just username?

Finally, what's the significance of this variable?
```
SLACK_TIMELINE_EVENT_REACTION=stopwatch
```
What are the other options for the values here?

**Comment by kevgliss** [comment]
I believe all of those options are documented here: https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-slack#dispatch-configuration 

> SLACK_TIMELINE_EVENT_REACTION=stopwatch

This variable denotes which emoji you want dispatch to key off of in order to add slack messages the incident timeline. The value can be any slack emoji.

Let us know if you need any more details than what the documentation provides.

**Comment by sfc-gh-pkommini** [comment]
@kevgliss: I gathered all the other slack config data from the gitbook link provided above. I'm still not clear on the purpose of some of the fields:

For example, In the below config variable what are the allowed values for department field ID values? What is this variable? Is it specific to slack or something else.
```
SLACK_PROFILE_DEPARTMENT_FIELD_ID [Optional. Default: ""]
Specifies the profile field ID where Department is mapped.
```
Same thing for the below variable. This description in the docs still lacks context of what are the allowed values and where the variable will be used.
SLACK_PROFILE_TEAM_FIELD_ID [Optional. Default: ""]
Specifies the profile field ID where Team is mapped.

Same thing for the below variable.
SLACK_PROFILE_WEBLINK_FIELD_ID [Optional. Default: ""]
Specifies the profile field ID where the weblink is mapped.

I believe a little more context on the use of these above config variables might help immensely.

I found the following code use the config variables, but I was still unable to establish what the purpose of this `SlackContactPlugin` is:
```
@apply(counter, exclude=["__init__"])
@apply(timer, exclude=["__init__"])
class SlackContactPlugin(ContactPlugin):
    title = "Slack Plugin - Contact Information Resolver"
    slug = "slack-contact"
    description = "Uses Slack to resolve contact information details."
    version = slack_plugin.__version__

    author = "Netflix"
    author_url = "https://github.com/netflix/dispatch.git"

    def __init__(self):
        self.client = slack.WebClient(token=str(SLACK_API_BOT_TOKEN))

    def get(self, email: str, **kwargs):
        """Fetch user info by email."""
        team = department = weblink = "Unknown"

        profile = get_user_profile_by_email(self.client, email)
        profile_fields = profile.get("fields")
        if profile_fields:
            team = profile_fields.get(SLACK_PROFILE_TEAM_FIELD_ID, {}).get("value", "Unknown")
            department = profile_fields.get(SLACK_PROFILE_DEPARTMENT_FIELD_ID, {}).get(
                "value", "Unknown"
            )
            weblink = profile_fields.get(SLACK_PROFILE_WEBLINK_FIELD_ID, {}).get("value", "Unknown")

        return {
            "fullname": profile["real_name"],
            "email": profile["email"],
            "title": profile["title"],
            "team": team,
            "department": department,
            "location": profile["tz"],
            "weblink": weblink,
            "thumbnail": profile["image_512"],
        }
```

**Comment by kevgliss** [comment]
Slack allows additional profile data to be set. These fields tell Dispatch where to find that data (as each organization may name them differently). Typically, these are set by some other internal source (e.g. workday) and sync'd to slack by some other means. The _values_ are just strings. If the organization decides not to set that profile information in Slack tit should be a no-op and Dispatch will simply set "unknown" for those values.

If that helps, I can add that context to the docs.

**Comment by sfc-gh-pkommini** [comment]
Gotcha. I think adding to the docs might help.
