### ISSUE TITLE
Slack API via websockets

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [Netflix/dispatch#773]
**Is your feature request related to a problem? Please describe.**
It's a pain to setup a separate API gateway just to allow slack incoming traffic and would be nice if we didn't have to set that up.

**Describe the solution you'd like**
Using the [socket mode](https://medium.com/slack-developer-blog/socket-to-me-3d122f96d955) to connect will save us that effort of allow incoming connections from slack securly.

**Describe alternatives you've considered**
API Gateway, Proxy server the usual

Am curious to know what the effort might involve. I'm happy to help. Saw it on the new and was wondering if it might apply to slack plugin?

**Comment by kevgliss** [comment]
Yes, we were planning on switching to socket mode. It's exciting that it was just released. I'm not sure how long it might take to switch but we will probably scope out the work this quarter and see how much work it is.

**Comment by sfc-gh-pkommini** [comment]
Sounds good! Please close if you have it planned. Thank you for your quick responses.

**Comment by kevgliss** [comment]
I've done some research on this. According to the documentation, it _shouldn't_ be that much work, providing the data structures in socket mode are the same as they were for the events API. 


Socket mode will probably be an optional way of running our bot (until we decide to deprecate the slack event endpoints sometime down the road, if ever).

With that said, I see the following tasks to add support:

- Create Socket Client Handler [docs](https://slack.dev/python-slack-sdk/socket-mode/index.html)
- Refactor the action, command, and event endpoints to support both socket and HTTP modes
- Create new cli command to run the websocket background process
- Add configuration and documentation for switching between the two modes

**Comment by kevgliss** [comment]
@sfc-gh-pkommini I believe we have basic support enabled by #795 (will be testing more in the coming week) please let us know if anything is confusing/broken.

**Comment by sfc-gh-pkommini** [comment]
@kevgliss I believe the `SLACK_APP_TOKEN` in this is missing in the config variables, Do you mean for it to be `SLACK_SOCKET_MODE_APP_TOKEN`?

Could you add that to the docs or correct that to reflect the correct variables name in this line: https://github.com/Netflix/dispatch/blob/21ae0a284b69427c2daf3f23014df4089bb19505/src/dispatch/plugins/dispatch_slack/socket_mode.py#L7

**Comment by kevgliss** [comment]
Fixed by #799. Thanks.
