### ISSUE TITLE
Slack message not sent when updating incident status

### ISSUE THREAD

**Issue by rilutham** [Netflix/dispatch#794]
**Describe the bug**
Slack message not sent to `#dispatch-x` channel when updating incident status from **Active** to **Stable**. It only happens when we have not yet executed `/dispatch-report-tactical` command. 

**To Reproduce**
1. Create an incident (admin UI or Slack command)
2. Update incident status from Active to Stable (admin UI or Slack command)
3. There is no slack message telling the incident status already changed.

**Expected behavior**
The slack message should be sent when updating the incident status.

**Screenshots**
<img width="514" alt="Screen Shot 2021-01-25 at 17 48 48" src="https://user-images.githubusercontent.com/1596026/105696982-8f2e9700-5f36-11eb-9546-f3ebe1045e2a.png">

**Comment by kevgliss** [comment]
@rilutham are there any errors in the logs that might help us?

**Comment by rilutham** [comment]
After having some troubleshooting, it was caused by a missing document with type `google-docs-incident-review-document`.

**Comment by kevgliss** [comment]
Thanks for following up, I'll add a task to harden incident update so as not to fail if it's missing an incident review document.
