### ISSUE TITLE
Email notification body is empty

### ISSUE THREAD

**Issue by rilutham** [Netflix/dispatch#796]
**Describe the bug**
All notifications sent to email have an empty body.

**To Reproduce**
1. Create an incident
2. An email with an empty body sent to the recipient.

**Expected behavior**
The email has the information needed for incident participants.

**Screenshots**
![Screen Shot 2021-01-27 at 10 14 16](https://user-images.githubusercontent.com/1596026/105940008-e34b8f80-608c-11eb-97a8-cde19e31d0f5.png)

**Exception from Sentry**
![Screen Shot 2021-01-27 at 10 46 54](https://user-images.githubusercontent.com/1596026/105940070-0aa25c80-608d-11eb-9a85-92f7e263acfe.png)

It seems there is no `node` installed on my system. After manually install `node` from the server, there is another error:

![Screen Shot 2021-01-27 at 10 48 43](https://user-images.githubusercontent.com/1596026/105940171-41787280-608d-11eb-847b-d2dfda5692d8.png)

**Comment by kevgliss** [comment]
Did you set the MJML location? 

https://hawkins.gitbook.io/dispatch/configuration/app#mjml_path-default-static-dispatch-node_modules-bin

**Comment by rilutham** [comment]
I did not set the environment variable, just let it using the default location. I see the `mjml` command exists in the default location @kevgliss

**Comment by kevgliss** [comment]
Judging from your sentry output, it looks like `node` isn't in your path: `/usr/bin/env`.

Perhaps something like: 

`export PATH=$PATH:/usr/local/lib/python3.8/site-packages/dispatch/static/node_modules/bin/` might work?

**Comment by rilutham** [comment]
The weird things is I have not `node` installed on `/usr/local/lib/python3.8/site-packages/dispatch/static/node_modules/bin/` or anywhere in the system. 

Here is some binary that exists in that directory with prefix `node-`:
- node-fetch
- node-forge
- node-ipc 
- node-libs-browser
- node-releases

Maybe there is some mistake in the way I built the docker image? I use the same way as @sfc-gh-pkommini to build the docker image as stated in https://github.com/Netflix/dispatch-docker/issues/91#issuecomment-768805782 

Anyway, after setting the `MJML_PATH` to `/static/dispatch/node_modules/.bin`, I got this error message:
```
[Errno 2] No such file or directory: '/static/dispatch/node_modules/.bin'
```
So, I drop the env and use the default value.

**Comment by rilutham** [comment]
I tried to install node and npm manually on the system, the error still happens @kevgliss

**Comment by rilutham** [comment]
@sfc-gh-pkommini did you encounter the same issue on your ECS setup?

**Comment by rilutham** [comment]
It is solved by doing the following:
- Remove `node_modules/` directory and `package-lock.json`on `/usr/local/lib/python3.8/site-packages/dispatch/static/dispatch`
- Manually install `node` and `npm` on the server
- Run `npm install` 

However, IMHO it is not the best way to make it works. Any idea of how to properly build the frontend assets in the deployment pipeline? Am I miss some env variable that should exist in the build step?

**Comment by kevgliss** [comment]
It's hard to say... are you using our docker file? The only real requirement is that you have node (with mjml) in that same path as the dispatch webserver, we do include node in our image because we use it to build the frontend assets. But that build process could be completed outside of your image. 

Perhaps, we just need to export node in the correct path [here](https://github.com/Netflix/dispatch/blob/master/docker/Dockerfile#L71)?

**Comment by sfc-gh-pkommini** [comment]
@rilutham We didn't use the email plugin and hence didn't receive this error. Sorry I couldn't help on this.

**Comment by rilutham** [comment]
@kevgliss Yes, I used the docker image [here](https://github.com/Netflix/dispatch/blob/master/docker/Dockerfile). Like I said before, there is no `node` installed in the system (runtime image). As a workaround, I was adding the following command in the runtime image:

```
RUN wget "https://nodejs.org/dist/v12.16.2/node-v12.16.2-linux-x64.tar.gz" \
    && tar -xzf "node-v12.16.2-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
    && rm -f "node-v12.16.2-linux-x64.tar.gz" \
    && cd /usr/local/lib/python3.8/site-packages/dispatch/static/dispatch \
    && rm -rf package-lock.json node_modules/ \
    && npm install
```

@sfc-gh-pkommini no worries, thank you for your response.

**Comment by kevgliss** [comment]
Doesn't https://github.com/Netflix/dispatch/blob/master/docker/Dockerfile#L70 add node to `/usr/local`?

**Comment by rilutham** [comment]
Somehow if you do `$ ls /usr/local/bin` in the runtime image, there is no node binary there.

**Comment by kevgliss** [comment]
Hopefully, #835 fixes the missing binary. Let me know if you still have issues.

**Comment by rilutham** [comment]
By copying the node binary from build image, it will raise the following error:
```
Step 36/47 : COPY --from=sdist /usr/local/bin/gosu /usr/local/bin/tini /usr/local/bin/node /usr/local/bin/
failed to copy files: failed to copy file: Container ID 166537 cannot be mapped to a host ID
```

The error will not show up if we add `RUN chgrp -R root /usr/local && chown -R root:root /usr/local` in the build image, however, the main issue still happens @kevgliss
