### ISSUE TITLE
Incident Detail Page 404

### ISSUE THREAD

**Issue by rilutham** [Netflix/dispatch#797]
**Describe the bug**
The incident detail page on https://dispatch.domain.com/incidents/dispatch-1 is not found. There is so much link to this page, but it is not found. Is it already on the backlog or a bug in my setup?

**To Reproduce**
1. Go to the incident detail page on domain.com/incidents/dispatch-number
2. The system returns a 404 page.

**Expected behavior**
Dispatch return incident detail.

**Screenshots**
![Screen Shot 2021-01-27 at 12 18 33](https://user-images.githubusercontent.com/1596026/105946692-560f3780-609a-11eb-8288-cc496d0428a8.png)

**Comment by kevgliss** [comment]
This is a bug, let me work on a fix.

**Comment by rilutham** [comment]
@kevgliss after pulling the latest code in ae5aacc212f79ad48df483cd08864df707477186 , I get the following error when accessing the incident detail page:

```
BadFilterFormat
Filter spec `[{"and":[{"model":"Incident","field":"name","op":"==","value":"dispatch-59"}]}]` should be a dictionary.
```

**Comment by rilutham** [comment]
After updated the code to 494db6e4b86db85fd0a60ba37e14929d0a1b1ac2, it is working properly, thanks @kevgliss
