### ISSUE TITLE
Broken image links in Slack documentation

### ISSUE THREAD

**Issue by mrthankyou** [Netflix/dispatch#800]
**Describe the bug**
When on the Slack docs page, the images are returning 404s.  

**To Reproduce**
1. Visit https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-slack.
2. See the broken image links on the page.

**Expected behavior**
The Images should properly load

**Screenshots**
<img width="1224" alt="Screen Shot 2021-01-27 at 2 17 59 PM" src="https://user-images.githubusercontent.com/52643283/106041974-7810b600-60aa-11eb-87a8-060176b48202.png">

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
None.

**Comment by kevgliss** [comment]
Thanks for reporting!
