### ISSUE TITLE
Proper way to delete incidents

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [Netflix/dispatch#814]
**Describe the bug**
![image](https://user-images.githubusercontent.com/72515998/106215051-f3df3100-6184-11eb-8a20-ea0b9420c295.png)

Wanted to check as to what is the proper way to delete an incident, and wanted to know who or what role as access to delete incidents?
Right now when I try to delete the incident, I get redirected to the login screen and see the message above.

**Expected Behavior**
 Maybe I should only get the message without going to the login screen?

**Comment by mvilanova** [comment]
You need to be admin to delete incidents. #810 should have fixed the redirect to the auth page.

**Comment by sfc-gh-pkommini** [comment]
Yup issue is resolved now. Thank you.

Also, how do I make someone (or myself) admin? Is the database a good way to change someone to admin? This is because our deployment is such that we can't SSH into our ECS containers.

**Comment by mvilanova** [comment]
You can run dispatch user update --role Admin <email> in the CLI

**Comment by sfc-gh-pkommini** [comment]
I was able to use the database to update roles as we don't have access to ECS fargate containers (By design). Would this have any unexpected consequences or does the command also do the same thing?

**Comment by kevgliss** [comment]
Modifying the database directly should be fine.

**Comment by sfc-gh-pkommini** [comment]
@kevgliss Thank you!
