### ISSUE TITLE
Executive report not received in email

### ISSUE THREAD

**Issue by rilutham** [Netflix/dispatch#844]
**To Reproduce**
1. Execute `/dispatch-report-executive` on Slack channel
![Screen Shot 2021-02-06 at 18 02 25](https://user-images.githubusercontent.com/1596026/107116419-b0cc3e80-68a5-11eb-865b-78efaab5d06d.png)

2. Not received any email about the executive report (incident notification and tactical report successfully sent to the email)

**Comment by mvilanova** [comment]
Strange... If the exec doc was created and you received the other emails, you should've received this one as well. Did you get any server errors? If so, can you share them?

**Comment by rilutham** [comment]
I pull latest code from the latest tag and it still happened. There is no server error logs or sentry records @mvilanova

**Comment by rilutham** [comment]
Sorry, I think I check the email in the Gmail user that is not registered to `incident-xxx-notification@domain.com`. How to register a user to the group @mvilanova ?

**Comment by mvilanova** [comment]
Short answer is, you shouldn't need to. 

Long answer, we create two Google groups for each incident. One for tactical communications (e.g. incident updates, tactical reports, etc.) and one for more high level, leadership style communications where executive reports are sent. Dispatch adds participants' emails to the tactical group and then the tactical group to the notifications one.

Can you check if your participant email account is a member of the tactical group incident-xxxx@ and if the tactical group is a member of the notifications one incident-xxxx-notifications@?

**Comment by mvilanova** [comment]
I just realized that we're having the same issue. I'm looking into it...

**Comment by rilutham** [comment]
Is there any way to add some email that is not the part of incident participant to the executive group, so that we can communicate the incident to them? In this case, let's say they are another department @mvilanova

**Comment by rilutham** [comment]
Sorry, I just found out that we can update the notification group by using the slack command `/dispatch-notifications-group`.

However, the member of the notification group can edit the report in Google Docs, IMHO ideally they should not edit access to the docs, WDYT @mvilanova ?

**Comment by mvilanova** [comment]
We have a very strong culture of freedom and responsibility here at Netflix. We decided to give everyone in the tactical and notification groups the role of contributor (aka writer) to simplify things and avoid having to manage permissions during an incident. So far it hasn't caused any issues.
