### ISSUE TITLE
CLI 

### ISSUE THREAD

**Issue by alexa-kelley-vim** [Netflix/dispatch#866]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mvilanova** [comment]
Dupe. Closing it out.

**Comment by alexa-kelley-vim** [comment]
My apology for the above post, I must have made a mistake entering my other issue. Thank you for closing it.
