### ISSUE TITLE
CLI "dispatch database dump" not working

### ISSUE THREAD

**Issue by alexa-kelley-vim** [Netflix/dispatch#867]
Unfortunately I can't go into my usual amount of detail because I'm in the middle of a migration. However I wanted to let you know ASAP that it appears there is a significant version mismatch occurring in stock Dispatch. 

In the source Dockerfile it is built off from python:3.8-slim-buster & python:3.8-buster. Both of these limit the psql client to version 11. This can be manually changed by introducing the repo. 
(here are the quick steps for debian https://computingforgeeks.com/install-postgresql-12-on-debian/)

That said the docker-compose pulls the latest version. Which is currently ~13. 

When attempting to run dispatch database dump from the CLI it will error out because of the difference. You should be able to recreate it with the sample DB. 

My suggested fix is to explicitly state the major version in both the Dockerfile and Docker-Compose.yml. If I can get to it in time after my migration I'll share a copy of the specific edits as a PR.

**Comment by kevgliss** [comment]
I think I understand what's going on. For your use case, does it matter which major version we pin to? Afaik Dispatch seems to work fine between Postgres 10-13 (as we didn't notice any issues). We're currently running 12 as that's the most recent version supported by aurora.

**Comment by alexa-kelley-vim** [comment]
The major version does seem to matter. Dispatch seems to be able to mostly function with 12/13. However the python:buster image is based off from debian:buster image and is limited to postgres-client-11 unless you update the dockerfile to include the postgres-12 repo. That said I did some experiments with the postgres 12 client and I did experience some instability. Primarily with the dispatch database CLI commands. The important part seems to be when there is a mismatch between major versions. 

With the assumption that most of the code appears to be built around postgres client 11 it seems to make sense to hardcode to major version 11. This will still allow minor version increases for security patches/etc. I have found some difficulty in migrating the DB between major versions so you may instead also consider hardcoding to major version 12. I do suggest extra testing if you go that route, and I can also provide the modifications I used to introduce the version 12 client to the source. 

I had a moment earlier and was working on typing this example up already. Below are some suggested changes for hardcoding dispatch to postgres major version 11. 


**In this repo**
change this:
https://github.com/Netflix/dispatch/blob/ab2625b3aacd8c7ca0e57ef51a940ead2496ea5a/docker/Dockerfile#L134
to:
`pkg-config postgresql-client-11\`

change this:
https://github.com/Netflix/dispatch/blob/ab2625b3aacd8c7ca0e57ef51a940ead2496ea5a/docker/docker-compose.yml#L4
to:
`image: postgres:11`

**In https://github.com/Netflix/dispatch-docker repo**
Change this:
https://github.com/Netflix/dispatch-docker/blob/28b90d0ea78bc8c92435aacc4f52136f142e996c/docker-compose.yml#L9
To this:
`image: postgres:11`

I would also suggest updating the ./install file in:
https://github.com/Netflix/dispatch-docker/blob/28b90d0ea78bc8c92435aacc4f52136f142e996c/install.sh#L100-L104
To reference postgres 11 instead of postgres 12. This difference is part of what brought this to my attention to begin with.

**Comment by alexa-kelley-vim** [comment]
It occurred to me that this may work better as a PR submission. 

If you would like me to submit a PR for hardcoding to 11 please let me know.

**Comment by kevgliss** [comment]
I'm testing out the changes now. I think I will have to migrate the example data as well for new folks.

**Comment by kevgliss** [comment]
I ended up landing on postgres-12 as this was likely the "latest" for the longest and is least likely to affect users. 

I was able to confirm the clients were in sync by running `docker-compose run --rm web database dump` which was able to complete successfully. 

See #873 for details.

Thanks for the report!
