### ISSUE TITLE
Documentation for Setting Up Email Delivery

### ISSUE THREAD

**Issue by mrthankyou** [Netflix/dispatch#870]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
This is actually a general question and a rather stupid one at that. I was reviewing your documentation but was unable to find how one set's up Dispatch to send emails out. Is that in part of the GSuite plugin? Thanks for all your help guys!

**Comment by mvilanova** [comment]
Correct. You can find instructions on how to configure the gsuite plugin here: https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-g-suite

**Comment by mrthankyou** [comment]
Thanks! I'll close this ticket then.
