### ISSUE TITLE
Documenting seed user dispatch@example.com password

### ISSUE THREAD

**Issue by mrthankyou** [Netflix/dispatch#876]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Is it possible to mention somewhere in the documentation the password to the `dispatch@example.com` user account created in the sample database? Providing this password would allow new users to demo the application from the viewpoint of an admin user.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kevgliss** [comment]
I don't know it offhand, and I don't think I necessarily want to have a "default" known password documented. That said, that user's password can be easily changed or your user can have its role modified with a dispatch cli user commands:

```
dispatch user --help
```

**Comment by mrthankyou** [comment]
Ahh fair enough. I might find a relevant point in the documentation somewhere to mention that command. Every time I want to access `dispatch@example.com` I don't know the password, get stuck, and just have to create an admin user.

**Comment by kevgliss** [comment]
Yes, we can add them. We didn't enumerate all commands because they should be fairly self-describing.

**Comment by mrthankyou** [comment]
I reviewed the docs and the closest place I thought to mention how to change the password for dispatch@example.com is [here](https://github.com/Netflix/dispatch/blob/7e58018d912714d372e3c06d13489e6da4e98d5a/docs/configuration/app.md#dispatch_authentication_default_user-default-dispatchexamplecom). 

Obviously your team has a better feel for where this could go. That said, if you think that's a good place I have no problem creating a PR that updates that md file. Let me know. 

Thanks for all your guys help!

**Comment by kevgliss** [comment]
That looks like a good place to add a hint and link back to the CLI page with the actual command and description? If you'd be willing to put a PR in that'd be super!

**Comment by mrthankyou** [comment]
I'll pull something together in the next day or two!

**Comment by mrthankyou** [comment]
I'm still doing this. Just a bit occupied atm :(

**Comment by dimuit86** [comment]
> Update: I'm still doing this. Just a bit occupied atm :(

Yes having the same issue. Were you able to figure it out?

**Comment by mrthankyou** [comment]
@dimuit86, 

The solution for now is to run inside the dispatch-web docker container the `dispatch user` command which will allow you to update the password for dispatch@example.com. I don't know the exact command so you'll have to run `dispatch user --help` to see what's available.

**Comment by cyber1998** [comment]
Hey! I am a new contributor and was wondering if I can take this if this isn't done yet? Thanks :)

**Comment by mrthankyou** [comment]
@cyber1998 All yours. I'm on vacation right now but if it's not done by next Monday I'll do it. :)
