### ISSUE TITLE
Incident MTTD (Mean Time To Detection)

### ISSUE THREAD

**Issue by rilutham** [Netflix/dispatch#877]
**Is your feature request related to a problem? Please describe.**
We are using dispatch not only for security vulnerability but also for reliability incidents. We want to measure the MTTD of the incident.

**Describe the solution you'd like**
Adding DateTime field for detection time in the incident table and UI. It is accessible to update via admin web.

**Comment by kevgliss** [comment]
Would allowing you to modify the incident timeline to add this type of metadata fit your use case? We've heard some other similar use-cases but were hesitant to add a lot of more top-level metadata to the incident object. 

The idea would be to provide a more robust/flexible timeline, that you could add these types of timing-related metadata.
