### ISSUE TITLE
Creating incident fails with 401 Unauthorized

### ISSUE THREAD

**Issue by Harsha-kumar-654** [Netflix/dispatch#879]
Hi all,

I'm Facing the issue, when I trying to creating an incident from dispatch tool, Following is the error please help with this.

![image](https://user-images.githubusercontent.com/78466893/108040556-757afe00-7063-11eb-8efa-cefbc89c130d.png)

"401 unauthorized"

**Comment by mvilanova** [comment]
@Harsha-kumar-654 can you elaborate a little bit more on the steps you took to create the incident and provide any server logs with errors?

**Comment by Harsha-kumar-654** [comment]
@mvilanova Please Find the screenshot server logs with errors. 
![image](https://user-images.githubusercontent.com/78466893/108174024-ed5d2d00-7124-11eb-98d9-7943564f512f.png)
![image](https://user-images.githubusercontent.com/78466893/108174035-f1894a80-7124-11eb-817b-9a44a7f0a4dc.png)

**Comment by mvilanova** [comment]
Thanks for the logs. Please, follow the instructions [here](https://hawkins.gitbook.io/dispatch/configuration/app#authentication) to set up authentication properly.

**Comment by Harsha-kumar-654** [comment]
Hello mvilanova,

we are generating an incident on the UI and getting a "401" error on every API and defined required params in the .env file for authentication but still, it didn't help.

could you please have a look at the below logs and share your further advice on the same.

web_1        | 2021-02-23T07:00:09.215868207Z NoneType: None
web_1        | 2021-02-23T07:00:09.347416073Z INFO:     49.206.16.26:53054 - "GET /favicon.ico HTTP/1.1" 200 OK
web_1        | 2021-02-23T07:00:09.503582065Z ERROR:dispatch.plugins.dispatch_core.plugin:Malformed authorization header. Scheme:  Param:  Authorization: None
web_1        | 2021-02-23T07:00:09.503615307Z NoneType: None
web_1        | 2021-02-23T07:00:09.503782705Z ERROR:dispatch.auth.service:Unable to determine user email based on configured auth provider or no default auth user email defined. Provider: dispatch-auth-provider-basic
web_1        | 2021-02-23T07:00:09.503816452Z NoneType: None

![image](https://user-images.githubusercontent.com/78466893/108811497-6819c280-75d3-11eb-9867-e43b7ceb7872.png)

**Comment by kevgliss** [comment]
How are you logging in? Are you being sent to `/login` in the UI? Did you register a new user?

**Comment by Harsha-kumar-654** [comment]
Yes, I have a registered few users in the application . Then I'm trying to login .

**Comment by mvilanova** [comment]
Can you share a redacted version of your `.env` file?

**Comment by Harsha-kumar-654** [comment]
My .env looks like that:
# General
COMPOSE_PROJECT_NAME=dispatch
DISPATCH_HELP_EMAIL=some@user.c0m
DISPATCH_HELP_SLACK_CHANNEL=#general
DISPATCH_UI_URL=http://public_ip

#Authentication
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=""
DISPATCH_JWT_SECRET=""
SECRET_KEY=""
DISPATCH_AUTHENTICATION_DEFAULT_USER="default"
DISPATCH_JWT_ALG="HS256"
DISPATCH_JWT_EXP="86400"

**Comment by mvilanova** [comment]
The following error makes me think that there's something wrong with the way you're sending the request to the server.

> web_1 | 2021-02-23T07:00:09.503582065Z ERROR:dispatch.plugins.dispatch_core.plugin:Malformed authorization header. Scheme: Param: Authorization: None

Could you add `log.debug(request.headers)` before [this](https://github.com/Netflix/dispatch/blob/master/src/dispatch/plugins/dispatch_core/plugin.py#L58) line and paste the output here?

**Comment by mvilanova** [comment]
Can you add a value to `DISPATCH_JWT_SECRET` in your `.env`? You don't need to set `DISPATCH_JWT_ALG` and `DISPATCH_JWT_EXP` to these values. They are already the defaults. You can also remove `DISPATCH_AUTHENTICATION_PROVIDER_SLUG=""` if you want to use its default `dispatch-auth-provider-basic`.  I'd suggest to set `DISPATCH_AUTHENTICATION_DEFAULT_USER` to an email address. For more insight into default values for env vars check [this](https://github.com/Netflix/dispatch/blob/master/src/dispatch/config.py) file.

**Comment by mvilanova** [comment]
Here's the auth part of my `.env`:
```
# Authentication
DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic
DISPATCH_AUTHENTICATION_DEFAULT_USER="mvilanova@netflix.com"
DISPATCH_JWT_SECRET="SOME_PASSWORD"

# Frontend
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-basic
```

**Comment by mvilanova** [comment]
@Harsha-kumar-654 still having issues?

**Comment by Harsha-kumar-654** [comment]
@mvilanova Still, I'm facing some issues attached screenshots for your reference. Kindly suggest to me what action needs to be taken.

![image](https://user-images.githubusercontent.com/78466893/110740696-803b4400-8259-11eb-8f7a-cdfbe36a612d.png)
![image](https://user-images.githubusercontent.com/78466893/110740701-829d9e00-8259-11eb-9ba7-6d699602e864.png)
![image](https://user-images.githubusercontent.com/78466893/110740712-85988e80-8259-11eb-98b8-e1ddfa010cf6.png)
![image](https://user-images.githubusercontent.com/78466893/110740725-88937f00-8259-11eb-898b-fe3dd15201e7.png)
![image](https://user-images.githubusercontent.com/78466893/110740736-8b8e6f80-8259-11eb-8291-94dac586e729.png)

**Comment by mvilanova** [comment]
Thanks for the screenshots, but we can't troubleshoot the issue(s) unless you provide us with the server logs showing the error(s).

**Comment by Harsha-kumar-654** [comment]
Find the screenshot of server logs for your reference. 
![image](https://user-images.githubusercontent.com/78466893/110924123-accd8980-8347-11eb-8c62-10d881679703.png)

**Comment by mvilanova** [comment]
Sorry, but I don't see any errors in this screenshot. Please, provide logs showing the errors you're experiencing in text, not image format.
