### ISSUE TITLE
fix even handler in slack socket mode

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#882]
**Describe the bug**
need to fix event handler from slack in socket mode https://github.com/Netflix/dispatch/blob/master/src/dispatch/plugins/dispatch_slack/socket_mode.py#L43
function handle_slack_event don't have argument 'request'
**To Reproduce**
1. Go to slack and make some event 
4. See an error
5. TypeError: handle_slack_event() got an unexpected keyword argument 'request'

**Comment by mvilanova** [comment]
Seems like we forgot to rename `request` parameter to `event`. We will put out a fix for it.

**Comment by kevgliss** [comment]
This should be fixed in #899 please let us know if you run into any other issues.
