### ISSUE TITLE
postgres / Dispatch DB credential handling

### ISSUE THREAD

**Issue by alexa-kelley-vim** [Netflix/dispatch#884]
**Describe the bug**
Postgres credentials that contain a `%` results in CLI failure. 

**To Reproduce**
1. Create a stock/example instance of dispatch
2. in .env make sure that that postgres password contains a `%` in it
3. build/install as usual

**Screenshots**
This is a sample from a stock install with the password for postgres set to `%%%dispatch%%%`

> Do you want to load example data (WARNING: this will remove all existing database data) (y/N)?n
> Running standard database migrations...
> Creating dispatch_core_1 ... done
> Creating dispatch_web_run ... done
> /usr/local/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
>   from cryptography.utils import int_from_bytes, int_to_bytes
> Traceback (most recent call last):
>   File "/usr/local/bin/dispatch", line 8, in <module>
>     sys.exit(entrypoint())
>   File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 636, in entrypoint
>     dispatch_cli()
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 372, in upgrade_database
>     alembic_command.stamp(alembic_cfg, "head")
>   File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 570, in stamp
>     script.run_env()
>   File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 481, in run_env
>     util.load_python_file(self.dir, "env.py")
>   File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
>     module = load_module_py(module_id, path)
>   File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 182, in load_module_py
>     spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 18, in <module>
>     config.set_main_option("sqlalchemy.url", str(SQLALCHEMY_DATABASE_URI))
>   File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 231, in set_main_option
>     self.set_section_option(self.config_ini_section, name, value)
>   File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 258, in set_section_option
>     self.file_config.set(section, name, value)
>   File "/usr/local/lib/python3.8/configparser.py", line 1201, in set
>     super().set(section, option, value)
>   File "/usr/local/lib/python3.8/configparser.py", line 894, in set
>     value = self._interpolation.before_set(self, section, option,
>   File "/usr/local/lib/python3.8/configparser.py", line 402, in before_set
>     raise ValueError("invalid interpolation syntax in %r at "
> ValueError: invalid interpolation syntax in 'postgresql+psycopg2://dispatch:%%%dispatch%%%@postgres:5432/dispatch' at position 31
> Cleaning up...
> 

**Additional context**
I have not confirmed this behavior with other characters but I suspect this is a sanitization issues so it may apply to others. 

Please let me know if you need any further details or examples.

**Comment by kevgliss** [comment]
Looks like Postgres accepts URL encoded strings: https://www.postgresql.org/docs/11/libpq-connect.html#id-1.7.3.8.3.6

That should be a pretty easy fix.

**Comment by alexa-kelley-vim** [comment]
Good to hear. Thank you for the quick identification & response. 

Brief housekeeping note I'll be switching future responses & reporting to come from @AlexaKelley. Same me, just unified account.

**Comment by AlexaKelley** [comment]
^ confirming that this is me.
