### ISSUE TITLE
db_sesssion is None, Using BasicAuth and only a subset of GSuite Plugins

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [Netflix/dispatch#885]
**Describe the bug**
Towards #686 I've made all the changes to use the service account without any delegation to do all the GSuite API calls. However, I found a bug while creating an incident.
This is the state of what plugins are enabled, since without Domain-Wide Delegation we can't get gmail and calendar plugins to work, I've disabled them.
![image](https://user-images.githubusercontent.com/72515998/108258889-5b99f380-7115-11eb-93af-d5d1496cbdce.png)

```
DEBUG:Updated the external ticket DT-40.:/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py:update_external_incident_ticket:167
DEBUG:Incident created notifications sent.:/usr/local/lib/python3.8/site-packages/dispatch/incident/messaging.py:send_incident_created_notifications:270
INFO:Dispatch Core App: Incident notifications sent:/usr/local/lib/python3.8/site-packages/dispatch/event/service.py:log:154
DEBUG:Recommendation: Documents: [] Individuals: [] Teams: [] Services: []:/usr/local/lib/python3.8/site-packages/dispatch/route/service.py:create_recommendation:128
ERROR:'NoneType' object has no attribute 'query':/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py:incident_create_flow:716
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/flows.py", line 702, in incident_create_flow
    send_incident_participant_announcement_message(
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/messaging.py", line 391, in send_incident_participant_announcement_message
    participant_info = contact_plugin.instance.get(participant_email)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_core/plugin.py", line 214, in get
    individual_service.get_by_email(db_session=db_session, email=email),
  File "/usr/local/lib/python3.8/site-packages/dispatch/individual/service.py", line 32, in get_by_email
    db_session.query(IndividualContact).filter(IndividualContact.email == email).one_or_none()
AttributeError: 'NoneType' object has no attribute 'query'
```

Looking closely at the function below:
```python
class DispatchContactPlugin(ContactPlugin):
    title = "Dispatch Plugin - Contact plugin"
    slug = "dispatch-contact"
    description = "Uses dispatch itself to resolve incident participants."
    version = dispatch_plugin.__version__

    author = "Netflix"
    author_url = "https://github.com/netflix/dispatch.git"

    def get(self, email, db_session=None):
        print(f"db_session is: {db_session}")
        return getattr(
            individual_service.get_by_email(db_session=db_session, email=email),
            "__dict__",
            {"email": email, "fullname": email},
        )
```
I found that db_session if not passed is set to None in this call:
```
  File "/usr/local/lib/python3.8/site-packages/dispatch/incident/messaging.py", line 391, in send_incident_participant_announcement_message
    participant_info = contact_plugin.instance.get(participant_email)
```

My question is:

Does this warrant the change for this line of code from:

```python
         participant_info = contact_plugin.instance.get(participant_email)
```
to
```python
        participant_info = contact_plugin.instance.get(participant_email, db_session)
```
to pass the db_session as needed by the `get()` method, because the log suggests it's passed as none or am I missing something?

**Comment by mvilanova** [comment]
You're right. I'll put out a fix for it.

**Comment by sfc-gh-pkommini** [comment]
@mvilanova:

So since I have docs plugin enabled and I'm using a service account for authenticating with the workspace APIs, I was testing the incident creation workflow, I seem to be stuck with this screen:

![image](https://user-images.githubusercontent.com/72515998/108266158-9c4a3a80-711e-11eb-9fa1-f6aa1097fec0.png)

For the bug above I made the change I proposed and was able to eliminate that particular error, However, I still see the above screen and I see no real bugs on the logs side.

I was wondering if there is a default document created for every incident? Is there any artifact created using the Docs API at incident creation time?

**Comment by mvilanova** [comment]
We do try to create the incident collaboration documents on incident create if the storage plugin is enabled (see [here](https://github.com/Netflix/dispatch/blob/master/src/dispatch/incident/flows.py#L551)). Did you add the document template(s) in the UI and map them to the incident type(s)?

https://github.com/Netflix/dispatch/pull/886 fixes the first issue.

**Comment by mvilanova** [comment]
If you have templates, does your service account have access to them, so the storage plugin can copy them to the incident folder?

**Comment by sfc-gh-pkommini** [comment]
Ah I see @mvilanova . I don't believe I setup any templates. Are there any sample templates you can share?

**Comment by kevgliss** [comment]
We do [here](https://github.com/Netflix/dispatch/issues/579), it looks like I didn't add them to the documentation yet though :-(

**Comment by sfc-gh-pkommini** [comment]
I'll test and get back to you. Thank you!

**Comment by sfc-gh-pkommini** [comment]
> If you have templates, does your service account have access to them, so the storage plugin can copy them to the incident folder?

@mvilanova When you say add them to the UI, I've to add the document in the `Knowledge -> Documents` and then link that document in the `Configuration -> Incident Type`?

**Comment by kevgliss** [comment]
Yes, that's correct @sfc-gh-pkommini

**Comment by sfc-gh-pkommini** [comment]
So @kevgliss @mvilanova while adding a document, I see these items to fill out:
![image](https://user-images.githubusercontent.com/72515998/108275745-a45ca700-712b-11eb-941a-537b646584db.png)
I have the following questions regarding this form:
- May I know what are the possible `document types`?
- Also, I'm guessing `Owner` is an email address? so, for adding `Generic Incident Document` what should I enter for owner? It is my email address as I copied the document into our shared drive?
- Finally, why does the document owner need a reminder and in what context is this reminder sent out?
- Does the reminder only apply if the Evergreen box is checked? This evengreen feature is not fully clear, Could you clarify what is the purpose of this checkbox?

**Comment by kevgliss** [comment]
All of the evergreen stuff is optional (enabled, owner, reminder). Evergreen is a feature for documents that should be kept up to date, for instance, if you have a runbook that you want to be reviewed once a quarter, you would set an individual or team DL to receive an email reminder notification to update the document after 90 days. 

Document type is optional as well and is just used for you to define the type of document. As documents are just links it's useful to give them some additional metadata e.g. google doc, confluence doc

**Comment by sfc-gh-pkommini** [comment]
Oh that helps. Thank you! Makes perfect sense to have a frequency to update the runbook/playbook.

**Comment by sfc-gh-pkommini** [comment]
@kevgliss, Final question,
```
INCIDENT_CONVERSATION_COMMANDS_REFERENCE_DOCUMENT_ID=INCIDENT_CONVERSATION_COMMANDS_REFERENCE_DOCUMENT_ID
INCIDENT_ONCALL_SERVICE_ID=None
INCIDENT_DOCUMENT_INVESTIGATION_SHEET_ID=INCIDENT_DOCUMENT_INVESTIGATION_SHEET_ID
INCIDENT_FAQ_DOCUMENT_ID=INCIDENT_FAQ_DOCUMENT_ID
INCIDENT_NOTIFICATION_CONVERSATIONS=
INCIDENT_NOTIFICATION_DISTRIBUTION_LISTS=incidents@example.com
INCIDENT_RESOURCE_CONVERSATION_COMMANDS_REFERENCE_DOCUMENT=google-docs-conversation-commands-reference-document
INCIDENT_RESOURCE_FAQ_DOCUMENT=google-docs-faq-document
INCIDENT_RESOURCE_INCIDENT_REVIEW_DOCUMENT=google-docs-incident-review-document
INCIDENT_RESOURCE_INCIDENT_TASK=google-docs-incident-task
INCIDENT_RESOURCE_INVESTIGATION_DOCUMENT=google-docs-investigation-document
INCIDENT_RESOURCE_INVESTIGATION_SHEET=google-docs-investigation-sheet
INCIDENT_RESOURCE_NOTIFICATIONS_GROUP=google-group-participant-notifications-group
INCIDENT_RESOURCE_TACTICAL_GROUP=google-group-participant-tactical-group
```
For these configs, Should I create a document in `Knowledge -> Documents` with name `google-docs-faq-document` and `google-docs-investigation-document` and so on? Is the name the link that uses that config and then uses the corresponding name to review the corresponding google doc?

**Comment by kevgliss** [comment]
Yes, that is how they are associated today (you shouldn't need to set any IDs in the configuration file anymore).

In the future, we will likely make this easier and more straightforward in the UI and abstract this detail from the users.

**Comment by sfc-gh-pkommini** [comment]
@kevgliss Do you have any template that you can share for the configs below?

```
INCIDENT_RESOURCE_INCIDENT_TASK=google-docs-incident-task
INCIDENT_RESOURCE_INVESTIGATION_DOCUMENT=google-docs-investigation-document
```

**Comment by sfc-gh-pkommini** [comment]
How is investigation document different from investigation sheet? I see that the investigation sheet is shared here: https://docs.google.com/spreadsheets/d/1Odk4KlL7uMF_yd7OvTOCaPWmtTA_WzFBIA4lMeU5cGY, but didn't see one for investigation document.

**Comment by kevgliss** [comment]
> @kevgliss Do you have any template that you can share for the configs below?
> 
> ```
> INCIDENT_RESOURCE_INCIDENT_TASK=google-docs-incident-task
> INCIDENT_RESOURCE_INVESTIGATION_DOCUMENT=google-docs-investigation-document
> ```

I'm not sure what you mean, these are just strings used to denote which documents are of a given type.


> How is investigation document different from investigation sheet? I see that the investigation sheet is shared here: https://docs.google.com/spreadsheets/d/1Odk4KlL7uMF_yd7OvTOCaPWmtTA_WzFBIA4lMeU5cGY, but didn't see one for investigation document.

The sheet is just a generic sheet created for all incidents, the templates for the other documents can be found here:

Incident Investigation Document:
https://docs.google.com/document/d/1fv--CrGpWJJ4nyPR0N0hq4JchHJPuqsXN4azE9CGQiE

Incident Review Document:
https://docs.google.com/document/d/1-VwcEpVVdymoojdUg9e5XP8QGam0-B5Djxh-guuPpEc

Executive Report:
https://docs.google.com/document/d/1dab6k14p5ageo5B_d1YlB_zS9hMGHDMXy9RUbIZous4

**Comment by sfc-gh-pkommini** [comment]
@kevgliss 
I see so `investigation document == generic incident document`.

My question regarding the configs below was assuming that if I have the `INCIDENT_RESOURCE_INCIDENT_TASK` config variable = `google-docs-incident-task`, then we have a document created under `Knowledge -> Documents` named `google-docs-incident-task`, and so I was requesting for the template related to `google-docs-incident-task`.

```
INCIDENT_RESOURCE_INCIDENT_TASK=google-docs-incident-task
INCIDENT_RESOURCE_INVESTIGATION_DOCUMENT=google-docs-investigation-document
```

Is that not how it works?

**Comment by kevgliss** [comment]
That is how it works, but confusingly, tasks don't have their own document. 

Tasks have their own types to help us understand where they originate from. In this case, tasks default to originate from google doc. 

So while 

> INCIDENT_RESOURCE_INCIDENT_TASK=google-docs-incident-task
> INCIDENT_RESOURCE_INVESTIGATION_DOCUMENT=google-docs-investigation-document

seem related they are not.

**Comment by sfc-gh-pkommini** [comment]
Ah I see. So that's just alluding to google docs being the source of the tasks. Gotcha.

I think I have everything to continue testing the creation of docs during the incident flow. I'll let you know if I'm able to get past the screen where I'm stuck at right now that shows `Creating Incident Documents ...`, but doesn't really throw any error either.

**Comment by kevgliss** [comment]
If it's just waiting on `Creating Incident Documents ...` from a UI it's just waiting for any document to be created:

https://github.com/Netflix/dispatch/blob/master/src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue#L153 

We probably need to add a check to this similar to `<span v-if="activeResourcePlugins.storage">` to ensure that you actually have a plugin with the type `document` enabled before showing the loading bar.

I would double-check that you have that plugin enabled and see if you have any errors on the backend.
