### ISSUE TITLE
Dispatch install.sh fails: Service 'web' failed to build

### ISSUE THREAD

**Issue by karymau** [Netflix/dispatch#89]
Hi,

When I run `install.sh` it fails with the following error:
```
...
Step 10/43 : RUN for key in     B42F6819007F00F88E364FD4036A9C25BF357DD4     595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7     94AE36675C464D64BAFA68DD7434390BDBE9B9C5     FD3A5288F042B6850C66B31F09FE44734EB7990E     71DCFD284A79C3B38668286BC97EC7A07EDE3FC1     DD8F2338BAE7501E3DD5AC78C273792F7D83545D     C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8     B9AE9905FFD7803F25714661B63B535A4C206CA9     77984A986EBC2AA786BC0F66B01FBB92821C587A     8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600     4ED778F539E3634C779C87C6D7062848A1AB005C     A48C2BEE680E841632CD4E44F07496B3EB3C1762     B9E2F5981AA6E0CD28160D9FF13993A75599653C     ; do     gpg --batch --keyserver hkps://mattrobenolt-keyserver.global.ssl.fastly.net:443 --recv-keys "$key";     done
 ---> Running in 5b7fc432e312
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: Server indicated a failure
gpg: keyserver receive failed: Server indicated a failure
...
gpg: keyserver receive failed: Server indicated a failure
Removing intermediate container 5b7fc432e312
ERROR: Service 'web' failed to build: The command '/bin/sh -c for key in...
```
Running on `KDE neon User Edition 5.18 (18.04)`, `Docker version 19.03.7` and `docker-compose version 1.25.4`.

**Comment by mvilanova** [comment]
@karymau hmm... seems like a problem with the PGP keyserver (`hkps://mattrobenolt-keyserver.global.ssl.fastly.net`) than Dispatch: `gpg: keyserver receive failed: Server indicated a failure`. Can you try again with a different keyserver?

In the future, please report issues with Dispatch docker here: https://github.com/Netflix/dispatch-docker

**Comment by karymau** [comment]
> Can you try again with a different keyserver?

Yes, of course, but could you please advise how to do it?

**Comment by mvilanova** [comment]
The issue could be `dirmngr` and/ or `DNS` related: https://unix.stackexchange.com/questions/399027/gpg-keyserver-receive-failed-server-indicated-a-failure

Good luck!
