### ISSUE TITLE
Incident don't show up in dashboard

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [Netflix/dispatch#890]
**Describe the bug**
I have a bunch of incidents but I don't see results on the dashboard.
![image](https://user-images.githubusercontent.com/72515998/108459510-a86fee00-722b-11eb-9e84-604f8e66a9e9.png)

![image](https://user-images.githubusercontent.com/72515998/108459273-2f709680-722b-11eb-81d3-9edfe56d854a.png)

I have the latest code from master.

**Comment by kevgliss** [comment]
What's your filter set to? Also, do you have that incident type set to "exclude from metrics"?

![2021-02-19_09-01](https://user-images.githubusercontent.com/2262214/108536314-2f0ae680-7291-11eb-8a2b-fd9af70f4b9a.png)

**Comment by sfc-gh-pkommini** [comment]
Vulnerability is the incident type and this is as given in the sample data. Only change I made was to connect the incident type to the investigation document.

![image](https://user-images.githubusercontent.com/72515998/108538834-12bc7900-7294-11eb-9d3c-37a8f23550f1.png)

**Comment by kevgliss** [comment]
What's the timeframe for your dashboard filter? Perhaps your tickets aren't in that range?
![2021-02-19_09-43](https://user-images.githubusercontent.com/2262214/108541149-f968fc00-7296-11eb-8de5-fdf08524e5a4.png).

Also, does the browser console show any errors?

**Comment by sfc-gh-pkommini** [comment]
I remember checking and finding they were in range and looking at the console to browser console to find no errors but let me re-check and confirm.

**Comment by sfc-gh-pkommini** [comment]
I think the default filter was missing something. But I can confirm it was filter issue. Closing as nothing needs to be changed.
