### ISSUE TITLE
Incident Type dropdown just show 5 records

### ISSUE THREAD

**Issue by rilutham** [Netflix/dispatch#891]
We are setting the incident type as a list of our applications which is more than 10 apps. On the dashboard filter and notification configuration filter, it's just showing 5 type.

<img width="1433" alt="Screen Shot 2021-02-19 at 17 33 23" src="https://user-images.githubusercontent.com/1596026/108493510-fdb60900-72d8-11eb-8352-7e79b990f515.png">

<img width="832" alt="Screen Shot 2021-02-19 at 17 36 56" src="https://user-images.githubusercontent.com/1596026/108493608-16beba00-72d9-11eb-8528-fcf336bfb91c.png">

**Comment by kevgliss** [comment]
I've made some fixes that should allow an arbitrary number of incident types (including "load more" in the case that search matches a bunch).

Let me know if you have further issues.
