### ISSUE TITLE
CryptographyDeprecationWarning when execute dispatch command

### ISSUE THREAD

**Issue by rilutham** [Netflix/dispatch#916]
My scheduler seems not working, I tried to restart the scheduler using `dispatch scheduler start` and got the following error:

```
/usr/local/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes, int_to_bytes
```

**Comment by kevgliss** [comment]
That's just a warning... are there any other errors?

**Comment by rilutham** [comment]
There is no error, the scheduler service is started but all scheduler such as `calculate-incidents-cost` and `incident-daily-report` is not working

**Comment by rilutham** [comment]
However, it constantly produce warning:

```
WARNING:dispatch.plugin.service:Attempted to fetch active plugin, but none were found. PluginType: workflow
WARNING:dispatch.workflow.scheduled:No workflow plugin is enabled.
```

**Comment by kevgliss** [comment]
The easiest way to test is to pick an individual task you want to try and run with the `--eager` flag to run it immediately.

e.g. 

Get available scheduler tasks
`dispatch scheduler list`

Run what you would like:
`dispatch scheduler start incident-daily-report --eager`

For the daily summary, you will also need to define a notification in the UI to determine, which slack channel/dl it should be sent to.

**Comment by rilutham** [comment]
![Screen Shot 2021-02-24 at 06 24 16](https://user-images.githubusercontent.com/1596026/108921455-f2603600-7668-11eb-9d47-274ecd77e527.png)

It's just hanging with no error message in the server or sentry. I pull the code from 4474e2f8556c92ac53d5711d138bd354effd3704 . It was good at adabeb21e8ec8f26c05689f12fc9ae42e7c749a1

**Comment by rilutham** [comment]
One of the impacts is the incident dashboard not updated while having some new incident in the past 24 hours.

**Comment by kevgliss** [comment]
It's not hanging, it looks like it's running successfully and just waiting for the next task it needs to run. There is no "scheduler running" text (although we could add it). 

Can you revert to that older commit and get an output? Unfortunately, nothing really jumps out at me that could cause a regression: https://github.com/Netflix/dispatch/compare/master..adabeb2
