### ISSUE TITLE
Error On Fresh Install - could not translate host name "postgres" 

### ISSUE THREAD

**Issue by mrthankyou** [Netflix/dispatch#925]
**Describe the bug**
The dispatch_postgres_1 docker container is consistently restarting for me. When I start the Dispatch server via `docker-compose up` I'm unable to go beyond the register or login pages due to the Postgres container staying in restarting mode.

**To Reproduce**
1. Git pull the latest version of dispatch-docker
2. Run install.sh
3. Confirm you want to create a seed database
4. Run `docker-compose up`.
5. Visit `localhost:8000/auth/register`. Register the account and you'll experience a failure. 

**Expected behavior**
The postgres container should be working as expected and I should be able to register users.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7

**Smartphone (please complete the following information):**
N/A

**Additional context**
The logs I'm seeing in docker are below:

<details>
  <summary>Logs</summary>
  postgres_1   | 
postgres_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1   | 
postgres_1   | 2021-02-26 01:11:42.461 UTC [1] FATAL:  database files are incompatible with server
postgres_1   | 2021-02-26 01:11:42.461 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 12.6 (Debian 12.6-1.pgdg100+1).
dispatch_postgres_1 exited with code 1
scheduler_1  | /usr/local/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
scheduler_1  |   from cryptography.utils import int_from_bytes, int_to_bytes
scheduler_1  | ERROR:dispatch.decorators:(psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution
scheduler_1  | 
scheduler_1  | (Background on this error at: http://sqlalche.me/e/13/e3q8)
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
scheduler_1  |     return fn()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
scheduler_1  |     return _ConnectionFairy._checkout(self)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
scheduler_1  |     fairy = _ConnectionRecord.checkout(pool)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
scheduler_1  |     rec = pool._do_get()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
scheduler_1  |     self._dec_overflow()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
scheduler_1  |     compat.raise_(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
scheduler_1  |     raise exception
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
scheduler_1  |     return self._create_connection()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
scheduler_1  |     return _ConnectionRecord(self)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
scheduler_1  |     self.__connect(first_connect_check=True)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
scheduler_1  |     pool.logger.debug("Error on connect(): %s", e)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
scheduler_1  |     compat.raise_(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
scheduler_1  |     raise exception
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
scheduler_1  |     connection = pool._invoke_creator(self)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
scheduler_1  |     return dialect.connect(*cargs, **cparams)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
scheduler_1  |     return self.dbapi.connect(*cargs, **cparams)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
scheduler_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
scheduler_1  | psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution
scheduler_1  | 
scheduler_1  | 
scheduler_1  | The above exception was the direct cause of the following exception:
scheduler_1  | 
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/decorators.py", line 37, in wrapper
scheduler_1  |     result = func(*args, **kwargs)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/task/scheduled.py", line 136, in sync_active_stable_tasks
scheduler_1  |     active_incidents = incident_service.get_all_by_status(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/dispatch/incident/service.py", line 95, in get_all_by_status
scheduler_1  |     db_session.query(Incident).filter(Incident.status == status).offset(skip).limit(limit).all()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
scheduler_1  |     return list(self)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
scheduler_1  |     return self._execute_and_instances(context)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances
scheduler_1  |     conn = self._get_bind_args(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args
scheduler_1  |     return fn(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
scheduler_1  |     conn = self.session.connection(**kw)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1142, in connection
scheduler_1  |     return self._connection_for_bind(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind
scheduler_1  |     return self.transaction._connection_for_bind(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
scheduler_1  |     conn = bind._contextual_connect()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
scheduler_1  |     self._wrap_pool_connect(self.pool.connect, None),
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
scheduler_1  |     Connection._handle_dbapi_exception_noconnection(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
scheduler_1  |     util.raise_(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
scheduler_1  |     raise exception
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
scheduler_1  |     return fn()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
scheduler_1  |     return _ConnectionFairy._checkout(self)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
scheduler_1  |     fairy = _ConnectionRecord.checkout(pool)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
scheduler_1  |     rec = pool._do_get()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
scheduler_1  |     self._dec_overflow()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
scheduler_1  |     compat.raise_(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
scheduler_1  |     raise exception
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
scheduler_1  |     return self._create_connection()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
scheduler_1  |     return _ConnectionRecord(self)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
scheduler_1  |     self.__connect(first_connect_check=True)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
scheduler_1  |     pool.logger.debug("Error on connect(): %s", e)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
scheduler_1  |     compat.raise_(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
scheduler_1  |     raise exception
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
scheduler_1  |     connection = pool._invoke_creator(self)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
scheduler_1  |     return dialect.connect(*cargs, **cparams)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
scheduler_1  |     return self.dbapi.connect(*cargs, **cparams)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
scheduler_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
scheduler_1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution
scheduler_1  | 
scheduler_1  | (Background on this error at: http://sqlalche.me/e/13/e3q8)
scheduler_1  | ERROR:dispatch.decorators:(psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution
scheduler_1  | 

</details>

**Comment by kevgliss** [comment]
Are you sure this is a fresh install?

> 2021-02-26 01:11:42.461 UTC [1] FATAL: database files are incompatible with server postgres_1 | 2021-02-26 01:11:42.461 UTC [1] DETAIL: The data directory was initialized by PostgreSQL version 13

Looks like you still have a postgres data volume left over from a previous build. Which you might need to delete/migrate. We've since aligned on postgres 12 instead taking whatever the latest postgres is. See: https://github.com/Netflix/dispatch/pull/873

**Comment by mrthankyou** [comment]
Hmm interesting. I swore I deleted the postgres data volume from Docker's app. I'll take a look again. Thanks for the point in the right direction!

**Comment by mrthankyou** [comment]
Short update:

After removing all containers and images from docker and re-running `install.sh` I'm encountering the following error after loading the seed data:

```
Setting up database...
Do you want to load example data (WARNING: this will remove all existing database data) (y/N)?y
Downloading example data from Dispatch repository...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  137k  100  137k    0     0   576k      0 --:--:-- --:--:-- --:--:--  576k
Dropping database dispatch if it already exists...
Creating dispatch_postgres_run ... done
dropdb: error: could not connect to database template1: could not translate host name "postgres" to address: Temporary failure in name resolution
Cleaning up...
```

I'll continue researching what is wrong on my end.

**Comment by mrthankyou** [comment]
I was able to get this working after going to my Docker App's troubleshoot page and deleting all running the "Clean / Purge data" command. 

Thanks again @kevgliss for the advice!
