### ISSUE TITLE
Save button disabled making it impossible to create/edit an Incident Type

### ISSUE THREAD

**Issue by mrthankyou** [Netflix/dispatch#937]
**Describe the bug**
When attempting to create or edit an incident type I am unable to do either. The save button is disabled.

**To Reproduce**
1. Do a fresh install loading in the sample data.
2. Sign up as a user and upgrade the user to an admin (I don't think this step is required but wanted to paste this anyways)
3. Go to `http://localhost:8000/configuration/incidentTypes`
4. Edit the existing incident type named "Vulnerability". Even if I change something as simple as the title of the incident type the save icon disk stays disabled.

**Expected behavior**
I would expect something as simple as an incident type title change to allow me to update the incident type.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Firefox 86.0
 - Latest pull from EOD March 8th.

**Smartphone (please complete the following information):**
N/A

**Additional context**
I believe there can be two causes here:

1. Something is wrong with the VueJS front-end validation. I'm not super familiar with VueJS so I was unable to see if this was actually the cause.
2. There is something bigger I'm missing about creating/editing incident types. Maybe there is a requirement for IncidentType records that the seed data doesn't have. But that wouldn't make sense because I'm also unable to create new incident types.

**Comment by mvilanova** [comment]
I was able to repro this issue in the `master` branch, but not on `latest`. A change since our most recent release must have introduced the issue. We will get it fixed.

**Comment by mvilanova** [comment]
I also noticed that we're not showing the values of the commander and liaison service when viewing/ editing an incident type.

**Comment by mrthankyou** [comment]
Confirmed the fix works on my end. Thanks again @mvilanova!

**Comment by mvilanova** [comment]
Awesome. Thanks for confirming!
