### ISSUE TITLE
Support for SQLAlchemy v1.4

### ISSUE THREAD

**Issue by usarnjain** [Netflix/dispatch#953]
Installation results in an error with sqlalchemy.orm.query - the '_ColumnEntity' component requires sqlalchemy.orm-context instead of the current library.

1. Pull from the dispatch-docker repository.
2. Run .sh installation file. 

Should install, instead errors out with the variable.

![image](https://user-images.githubusercontent.com/70347928/111394793-69e21d80-8689-11eb-9a4d-c23c1f68787c.png)

Potential fix: push a new Docker container in which the requirements-base.txt file with the revised value for sqlalchemy<1.4.0 to Docker registry.

**Comment by mvilanova** [comment]
We fixed this issue in https://github.com/Netflix/dispatch/pull/946 yesterday. You can replace `latest` with `master` [here](https://github.com/Netflix/dispatch-docker/blob/master/docker-compose.yml#L22) to build the core image until we cut a new release.
