### ISSUE TITLE
Unable to name an incident

### ISSUE THREAD

**Issue by dnandakumarcyber** [Netflix/dispatch#971]
How would I name an incident? 

The current incident report button does not allow me to name an incident, which leads to incidents with 'null' names that I cannot view or edit. Is there a particular process I have to follow to name incidents? 

![dispatch](https://user-images.githubusercontent.com/71340363/111705818-86539680-87fe-11eb-9310-7a5478a13007.PNG)

The incident report button also does not redirect me to a reporting page once I submit a new incident

**Comment by mvilanova** [comment]
@dnandakumarcyber did something go wrong when you created the incident? The incident name gets set by Dispatch based on what the ticket plugin returns and can't be edited using the Web UI.
