### ISSUE TITLE
 QueuePool limit Error

### ISSUE THREAD

**Issue by bender92** [Netflix/dispatch#993]
**Describe the bug**
some times I see problem with slack integration, after some command I get meesage from Slack
/dispatch-list-tasks failed with the error "dispatch_failed"

**To Reproduce**
1. Go to slack
2. run any / command 

> ERROR:Failed to run a request listener: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r):/usr/local/lib/python3.8/site-packages/slack_sdk/socket_mode/async_client.py:run_message_listeners:135
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/slack_sdk/socket_mode/async_client.py", line 133, in run_message_listeners
>     await listener(self, request)
>   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/socket_mode.py", line 48, in process
>     response = await handle_slack_command(
>   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_slack/commands.py", line 163, in handle_slack_command
>     conversation = conversation_service.get_by_channel_id_ignoring_channel_type(
>   File "/usr/local/lib/python3.8/site-packages/dispatch/conversation/service.py", line 26, in get_by_channel_id_ignoring_channel_type
>     db_session.query(Conversation)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
>     ret = list(self)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
>     return self._execute_and_instances(context)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances
>     conn = self._get_bind_args(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args
>     return fn(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
>     conn = self.session.connection(**kw)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1142, in connection
>     return self._connection_for_bind(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind
>     return self.transaction._connection_for_bind(
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
>     conn = bind._contextual_connect()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
>     self._wrap_pool_connect(self.pool.connect, None),
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
>     return fn()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
>     return _ConnectionFairy._checkout(self)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
>     fairy = _ConnectionRecord.checkout(pool)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
>     rec = pool._do_get()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 128, in _do_get
>     raise exc.TimeoutError(
> sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)

**Expected behavior**
run command 

**Additional context**
recreate pod help resolve problem, but it's not a solution

**Comment by kevgliss** [comment]
Any more info on your environment? We haven't seen this error on our Postgres RDS instances.

**Comment by bender92** [comment]
psql (PostgreSQL) 13.0 
dispatch, version 0.1.0.dev0
